/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type {
  HttpMethod,
  IHttpResponse,
  IRawHttpHeader,
  IRawHttpQuery,
  IRawHttpRequest,
} from "@rexeus/typeweaver-core";
import { createFetchBodyLimitPolicy } from "./BodyLimitPolicy.js";
import { parseFetchRequestBody } from "./fetchRequestBody.js";
import { buildFetchResponseHeaders, serializeFetchResponseBody } from "./fetchResponse.js";
import { appendRequestRecordValue } from "./requestRecord.js";
import type { BodyLimitPolicy } from "./BodyLimitPolicy.js";

export type FetchApiAdapterOptions = {
  readonly maxBodySize?: number;
  readonly bodyLimitPolicy?: BodyLimitPolicy;
};

/**
 * Converts between Fetch API `Request`/`Response` and typeweaver's
 * `IRawHttpRequest`/`IHttpResponse` at the server boundary.
 *
 * This is the **only** place where framework-specific types exist.
 * Everything inside the middleware pipeline and handlers works
 * exclusively with typeweaver's native types.
 */
export class FetchApiAdapter {
  private readonly bodyLimitPolicy: BodyLimitPolicy;

  public constructor(options?: FetchApiAdapterOptions) {
    this.bodyLimitPolicy =
      options?.bodyLimitPolicy ?? createFetchBodyLimitPolicy(options?.maxBodySize);
  }

  public async toRequest(request: Request, url?: URL): Promise<IRawHttpRequest> {
    const parsedUrl = url ?? new URL(request.url);
    return {
      method: request.method.toUpperCase() as HttpMethod,
      path: parsedUrl.pathname,
      header: FetchApiAdapter.extractHeaders(request.headers),
      query: FetchApiAdapter.extractQueryParams(parsedUrl),
      body: await parseFetchRequestBody(request, this.bodyLimitPolicy),
    };
  }

  public toResponse(response: IHttpResponse): Response {
    return new Response(serializeFetchResponseBody(response.body), {
      status: response.statusCode,
      headers: buildFetchResponseHeaders(response.header, response.body),
    });
  }

  private static extractHeaders(headers: Headers): IRawHttpHeader {
    const result: Record<string, string | string[]> = Object.create(null) as Record<
      string,
      string | string[]
    >;
    headers.forEach((value, key) => appendRequestRecordValue(result, key, value));
    return Object.keys(result).length > 0 ? result : undefined;
  }

  private static extractQueryParams(url: URL): IRawHttpQuery {
    const result: Record<string, string | string[]> = Object.create(null) as Record<
      string,
      string | string[]
    >;
    url.searchParams.forEach((value, key) => appendRequestRecordValue(result, key, value));
    return Object.keys(result).length > 0 ? result : undefined;
  }
}
