/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { PayloadTooLargeError } from "./Errors";
import type { TypeweaverApp } from "./TypeweaverApp";
import type { IncomingMessage, ServerResponse } from "node:http";

/**
 * Adapts a `TypeweaverApp` to Node.js `http.createServer`.
 *
 * Converts `IncomingMessage` to a Fetch API `Request`, calls `app.fetch()`,
 * and writes the `Response` back to `ServerResponse`.
 *
 * @example
 * ```typescript
 * import { createServer } from "node:http";
 * import { nodeAdapter } from "./generated/lib/server";
 * import app from "./server";
 *
 * createServer(nodeAdapter(app)).listen(3000);
 * ```
 */
const DEFAULT_MAX_BODY_SIZE = 1_048_576; // 1 MB

export type NodeAdapterOptions = {
  readonly maxBodySize?: number;
};

export function nodeAdapter(
  app: TypeweaverApp<any>,
  options?: NodeAdapterOptions,
): (req: IncomingMessage, res: ServerResponse) => void {
  const maxBodySize = options?.maxBodySize ?? DEFAULT_MAX_BODY_SIZE;
  return (req, res) => {
    void handleRequest(app, req, res, maxBodySize);
  };
}

async function handleRequest(
  app: TypeweaverApp<any>,
  req: IncomingMessage,
  res: ServerResponse,
  maxBodySize: number,
): Promise<void> {
  try {
    const url = new URL(req.url ?? "/", `http://${req.headers.host}`);
    const isBodyless = req.method === "GET" || req.method === "HEAD";
    const body = isBodyless ? undefined : await collectBody(req, maxBodySize);

    const request = new Request(url, {
      method: req.method,
      headers: req.headers as Record<string, string>,
      body,
    });

    const response = await app.fetch(request);

    response.headers.forEach((value, key) => {
      if (key.toLowerCase() !== "set-cookie") {
        res.setHeader(key, value);
      }
    });
    const cookies = response.headers.getSetCookie();
    if (cookies.length > 0) {
      res.setHeader("set-cookie", cookies);
    }
    res.writeHead(response.status);
    res.end(Buffer.from(await response.arrayBuffer()));
  } catch (error) {
    if (error instanceof PayloadTooLargeError) {
      if (!res.headersSent) {
        res.writeHead(413, { "content-type": "application/json" });
      }
      res.end(
        JSON.stringify({
          code: "PAYLOAD_TOO_LARGE",
          message: "Request body exceeds the size limit",
        }),
      );
      return;
    }

    console.error(error);
    if (!res.headersSent) {
      res.writeHead(500, { "content-type": "application/json" });
    }
    res.end(
      JSON.stringify({
        code: "INTERNAL_SERVER_ERROR",
        message: "An unexpected error occurred",
      }),
    );
  }
}

function collectBody(req: IncomingMessage, maxBodySize: number): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    let totalBytes = 0;

    req.on("data", (chunk: Buffer) => {
      totalBytes += chunk.byteLength;
      if (totalBytes > maxBodySize) {
        req.destroy();
        reject(new PayloadTooLargeError(totalBytes, maxBodySize));
        return;
      }
      chunks.push(chunk);
    });

    req.on("end", () => resolve(Buffer.concat(chunks, totalBytes)));
    req.on("error", reject);
  });
}
