/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { BodyLimitPolicy } from "./BodyLimitPolicy.js";
import type { TypeweaverApp } from "./TypeweaverApp.js";

/** Runtime context shared privately between TypeweaverApp and adapters. */
export type TypeweaverRuntimeContext = {
  readonly bodyLimitPolicy: BodyLimitPolicy;
  readonly reportError: (error: unknown) => void;
};

const appRuntimeContextRegistry = new WeakMap<TypeweaverApp<any>, TypeweaverRuntimeContext>();

function fallbackReportError(error: unknown): void {
  console.error(error);
}

export function setTypeweaverAppRuntimeContext(
  app: TypeweaverApp<any>,
  runtimeContext: TypeweaverRuntimeContext,
): void {
  appRuntimeContextRegistry.set(app, runtimeContext);
}

export function getTypeweaverAppRuntimeContext(
  app: TypeweaverApp<any>,
): TypeweaverRuntimeContext | undefined {
  return appRuntimeContextRegistry.get(app);
}

export function getTypeweaverAppErrorReporter(app: TypeweaverApp<any>): (error: unknown) => void {
  return getTypeweaverAppRuntimeContext(app)?.reportError ?? fallbackReportError;
}
