/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

// oxlint-disable import/max-dependencies
import {
  badRequestDefaultError,
  createDefaultErrorResponse,
  payloadTooLargeDefaultError,
} from "@rexeus/typeweaver-core";
import type { IHttpResponse } from "@rexeus/typeweaver-core";
import {
  BodyParseError,
  MissingRouterForPrefixedMountError,
  PayloadTooLargeError,
} from "./errors/index.js";
import { Router } from "./Router.js";
import { createInternalServerErrorResponse, reportAppError } from "./TypeweaverAppErrorHandling.js";
import { processAppRequest } from "./TypeweaverAppRequestPipeline.js";
import { mountAppRouter } from "./TypeweaverAppRouting.js";
import { initializeTypeweaverAppRuntime } from "./TypeweaverAppRuntime.js";
import type { FetchApiAdapter } from "./FetchApiAdapter.js";
import type { Middleware } from "./Middleware.js";
import type { ErasedRequestHandler } from "./RequestHandler.js";
import type { StateRequirementError, TypedMiddleware } from "./TypedMiddleware.js";
import type { TypeweaverRouter } from "./TypeweaverRouter.js";

/**
 * The main application class that provides routing, middleware, and
 * request handling using typeweaver's raw-request and typed-response contracts.
 *
 * Exposes a single `fetch()` method compatible with Bun, Deno, Cloudflare Workers,
 * and adaptable to Node.js `http.createServer`.
 *
 * Internally, middleware operates on `IRawHttpRequest`/`IHttpResponse`.
 * Conversion from/to Fetch API `Request`/`Response` happens **only** at the boundary.
 *
 * Middleware is return-based: each middleware returns an `IHttpResponse`
 * instead of mutating shared state.
 *
 * Middleware runs for **all** requests, including 404s and 405s, so global
 * concerns like logging and CORS always execute.
 *
 * @example
 * ```typescript
 * const app = new TypeweaverApp()
 *   .use(authMiddleware)       // defineMiddleware<{ userId: string }>
 *   .use(permissionsMiddleware) // defineMiddleware<{ perms: string[] }, { userId: string }>
 *   .route(new TodoRouter({ requestHandlers: { ... } }));
 *
 * Bun.serve({ fetch: app.fetch, port: 3000 });
 * ```
 */
export type TypeweaverAppOptions = {
  readonly maxBodySize?: number;
  readonly onError?: (error: unknown) => void;
};

export class TypeweaverApp<TState extends Record<string, unknown> = {}> {
  private readonly router = new Router();
  private readonly middlewares: Middleware[] = [];
  private readonly adapter: FetchApiAdapter;
  private readonly onError: (error: unknown) => void;

  public constructor(options?: TypeweaverAppOptions) {
    this.onError = options?.onError ?? ((error) => console.error(error));
    this.adapter = initializeTypeweaverAppRuntime({
      app: this,
      options,
      reportError: (error) => reportAppError(this.onError, error),
    });
  }

  /**
   * Register a typed middleware that provides state to downstream handlers.
   *
   * Returns a new `TypeweaverApp` type with the accumulated state.
   * Produces a compile-time error if the middleware's requirements are not met
   * by the currently accumulated state.
   *
   * Use {@link defineMiddleware} to create typed middleware.
   */
  public use<TProv extends Record<string, unknown>, TReq extends Record<string, unknown>>(
    middleware: TypedMiddleware<TProv, TReq> &
      ([TState] extends [TReq] ? unknown : StateRequirementError<TReq, TState>),
  ): TypeweaverApp<TState & TProv> {
    this.middlewares.push(middleware.handler);
    return this as TypeweaverApp<TState & TProv>;
  }

  /**
   * Mount a generated `TypeweaverRouter` instance.
   *
   * Registers all routes from the router into the app.
   * Multiple routers can be mounted on the same app.
   *
   * Optionally accepts a prefix to prepend to all routes from the router.
   *
   * @example
   * ```typescript
   * app.route(new AccountRouter({ requestHandlers: { ... } }));
   * app.route("/api/v1", new TodoRouter({ requestHandlers: { ... } }));
   * ```
   */
  public route(router: TypeweaverRouter<Record<string, ErasedRequestHandler>>): this;
  public route(
    prefix: string,
    router: TypeweaverRouter<Record<string, ErasedRequestHandler>>,
  ): this;
  public route(
    prefixOrRouter: string | TypeweaverRouter<Record<string, ErasedRequestHandler>>,
    router?: TypeweaverRouter<Record<string, ErasedRequestHandler>>,
  ): this {
    if (typeof prefixOrRouter === "string") {
      if (!router) {
        throw new MissingRouterForPrefixedMountError(prefixOrRouter);
      }
      mountAppRouter(this.router, router, prefixOrRouter);
      return this;
    }
    mountAppRouter(this.router, prefixOrRouter);
    return this;
  }

  /**
   * Universal request handler compatible with Fetch API runtimes.
   *
   * The entire pipeline works with `IHttpRequest`/`IHttpResponse`.
   * Conversion from/to Fetch API `Request`/`Response` happens only here, at the boundary.
   *
   * Middleware runs for all requests (including 404s and 405s).
   * HEAD requests automatically fall back to GET handlers with body stripped from the response.
   *
   * @example
   * ```typescript
   * // Bun
   * Bun.serve({ fetch: app.fetch, port: 3000 });
   *
   * // Deno
   * Deno.serve({ port: 3000 }, app.fetch);
   * ```
   */
  public fetch = async (request: Request): Promise<Response> => {
    try {
      const response = await this.processRequest(request);
      return this.adapter.toResponse(response);
    } catch (error) {
      if (error instanceof PayloadTooLargeError) {
        reportAppError(this.onError, error);
        return this.adapter.toResponse(createDefaultErrorResponse(payloadTooLargeDefaultError));
      }
      if (error instanceof BodyParseError) {
        return this.adapter.toResponse(createDefaultErrorResponse(badRequestDefaultError));
      }
      reportAppError(this.onError, error);
      return createInternalServerErrorResponse();
    }
  };

  private processRequest(request: Request): Promise<IHttpResponse> {
    return processAppRequest({
      request,
      adapter: this.adapter,
      router: this.router,
      middlewares: this.middlewares,
      safeOnError: (error) => reportAppError(this.onError, error),
    });
  }
}
