/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

export class RequestBodyReadAbortedError extends Error {
  public override readonly name = "RequestBodyReadAbortedError";

  public constructor(
    public readonly bytesRead: number,
    public readonly maxBodySize: number,
  ) {
    super(
      `Request was aborted while reading the body after ${bytesRead} bytes; maximum allowed body size is ${maxBodySize} bytes.`,
    );
  }
}
