/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { Context } from "hono";
import {
  TypeweaverHono,
  type HonoRequestHandler,
  type TypeweaverHonoOptions,
} from "../../lib/hono/index.js";

import type { IRegisterAccountRequest } from "../../types/account/RegisterAccountRequest.js";
import { RegisterAccountRequestValidator } from "../../types/account/RegisterAccountRequestValidator.js";
import type { RegisterAccountResponse } from "../../types/account/RegisterAccountResponse.js";
import { RegisterAccountResponseValidator } from "../../types/account/RegisterAccountResponseValidator.js";

export type HonoAccountApiHandler = {
  handleRegisterAccountRequest: HonoRequestHandler<
    IRegisterAccountRequest,
    RegisterAccountResponse
  >;
};

export class AccountHono extends TypeweaverHono<HonoAccountApiHandler> {
  public constructor(options: TypeweaverHonoOptions<HonoAccountApiHandler>) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.post("/accounts", async (context: Context) =>
      this.handleRequest(
        context,
        "RegisterAccount",
        new RegisterAccountRequestValidator(),
        new RegisterAccountResponseValidator(),
        this.requestHandlers.handleRegisterAccountRequest.bind(this.requestHandlers),
      ),
    );
  }
}
