/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod, type IHttpRequest, type IRawHttpRequestFor } from "@rexeus/typeweaver-core";

export type IGetMetricLabelsRequestHeader = Readonly<Record<string, boolean> | undefined>;

export type IGetMetricLabelsRequestParam = Readonly<{
  metricId: number;
}>;

export type IGetMetricLabelsRequestQuery = Readonly<Record<string, number> | undefined>;

/**
 * Read dynamic metric label records
 */
export type IGetMetricLabelsRequest = IHttpRequest<
  IGetMetricLabelsRequestHeader,
  IGetMetricLabelsRequestParam,
  IGetMetricLabelsRequestQuery,
  undefined
> & {
  readonly path: string;
  readonly method: HttpMethod.GET;
  readonly header: IGetMetricLabelsRequestHeader;
  readonly param: IGetMetricLabelsRequestParam;
  readonly query: IGetMetricLabelsRequestQuery;
};

export type IRawGetMetricLabelsRequest = IRawHttpRequestFor<IGetMetricLabelsRequest>;
