/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients/index.js";
import { getOperationDefinition } from "../lib/types/index.js";
import { GetMetricLabelsResponseValidator } from "./GetMetricLabelsResponseValidator.js";
import type {
  IGetMetricLabelsRequest,
  IGetMetricLabelsRequestHeader,
  IGetMetricLabelsRequestParam,
  IGetMetricLabelsRequestQuery,
} from "./GetMetricLabelsRequest.js";
import type { GetMetricLabelsResponse } from "./GetMetricLabelsResponse.js";

const definition = getOperationDefinition(spec, "metric", "GetMetricLabels");
const responseValidator = new GetMetricLabelsResponseValidator();

/**
 * Read dynamic metric label records
 */
export class GetMetricLabelsRequestCommand
  extends RequestCommand<
    IGetMetricLabelsRequestHeader,
    IGetMetricLabelsRequestParam,
    IGetMetricLabelsRequestQuery,
    undefined
  >
  implements IGetMetricLabelsRequest
{
  public override readonly operationId = definition.operationId;
  public override readonly method = HttpMethod.GET;
  public override readonly path = definition.path;

  public override readonly header: IGetMetricLabelsRequestHeader;
  public override readonly param: IGetMetricLabelsRequestParam;
  public override readonly query: IGetMetricLabelsRequestQuery;
  declare public readonly body: undefined;

  public constructor(input: Omit<IGetMetricLabelsRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.param = input.param;

    this.query = input.query;
  }

  public processResponse(response: IHttpResponse): GetMetricLabelsResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
