/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { IGetMetricKeyedLabelsSuccessResponse } from "../responses/GetMetricKeyedLabelsSuccessResponse.js";

export type GetMetricKeyedLabelsResponse = IGetMetricKeyedLabelsSuccessResponse;
