/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  getOperationDefinition,
  getResponseDefinition,
  type ResponseEntry,
  ResponseValidator,
} from "../lib/types/index.js";
import type { GetMetricSamplesResponse } from "./GetMetricSamplesResponse.js";

const definition = getOperationDefinition(spec, "metric", "GetMetricSamples");

const getMetricSamplesSuccessDefinition = getResponseDefinition(
  definition.responses,
  "GetMetricSamplesSuccess",
);

export class GetMetricSamplesResponseValidator extends ResponseValidator<GetMetricSamplesResponse> {
  protected override readonly expectedStatusCodes = [200];

  protected override readonly responseEntries: readonly ResponseEntry[] = [
    {
      name: "GetMetricSamplesSuccess",
      statusCode: 200,
      headerSchema: getMetricSamplesSuccessDefinition.header,
      bodySchema: getMetricSamplesSuccessDefinition.body,
    },
  ];
}
