/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { IGetMetricSamplesSuccessResponse } from "../responses/GetMetricSamplesSuccessResponse.js";

export type GetMetricSamplesResponse = IGetMetricSamplesSuccessResponse;
