/* eslint-disable */
/**
 * This file was automatically generated by TypeWeaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import definition from "../../definition/specimen/PutSpecimenDefinition";
import type { ZodSafeParseResult } from "zod/v4";
import {
  type IHttpResponse,
  type SafeResponseValidationResult,
  ResponseValidationError,
} from "@rexeus/typeweaver-core";
import { ResponseValidator, assert } from "../lib/types";
import {
  type PutSpecimenResponse,
  type IPutSpecimenSuccessResponse,
  PutSpecimenSuccessResponse,
  type IPutSpecimenSuccessResponseBody,
  type IPutSpecimenSuccessResponseHeader,
} from "./PutSpecimenResponse";

import {
  type ISpecimenConflictErrorResponse,
  SpecimenConflictErrorResponse,
  type ISpecimenConflictErrorResponseBody,
  type ISpecimenConflictErrorResponseHeader,
} from "./SpecimenConflictErrorResponse";

import {
  type ISpecimenNotFoundErrorResponse,
  SpecimenNotFoundErrorResponse,
  type ISpecimenNotFoundErrorResponseBody,
  type ISpecimenNotFoundErrorResponseHeader,
} from "./SpecimenNotFoundErrorResponse";

import {
  type ISpecimenUnprocessableEntityErrorResponse,
  SpecimenUnprocessableEntityErrorResponse,
  type ISpecimenUnprocessableEntityErrorResponseBody,
  type ISpecimenUnprocessableEntityErrorResponseHeader,
} from "./SpecimenUnprocessableEntityErrorResponse";

import {
  type IForbiddenErrorResponse,
  ForbiddenErrorResponse,
  type IForbiddenErrorResponseBody,
  type IForbiddenErrorResponseHeader,
} from "../shared/ForbiddenErrorResponse";

import {
  type IInternalServerErrorResponse,
  InternalServerErrorResponse,
  type IInternalServerErrorResponseBody,
  type IInternalServerErrorResponseHeader,
} from "../shared/InternalServerErrorResponse";

import {
  type ITooManyRequestsErrorResponse,
  TooManyRequestsErrorResponse,
  type ITooManyRequestsErrorResponseBody,
  type ITooManyRequestsErrorResponseHeader,
} from "../shared/TooManyRequestsErrorResponse";

import {
  type IUnauthorizedErrorResponse,
  UnauthorizedErrorResponse,
  type IUnauthorizedErrorResponseBody,
  type IUnauthorizedErrorResponseHeader,
} from "../shared/UnauthorizedErrorResponse";

import {
  type IUnsupportedMediaTypeErrorResponse,
  UnsupportedMediaTypeErrorResponse,
  type IUnsupportedMediaTypeErrorResponseBody,
  type IUnsupportedMediaTypeErrorResponseHeader,
} from "../shared/UnsupportedMediaTypeErrorResponse";

import {
  type IValidationErrorResponse,
  ValidationErrorResponse,
  type IValidationErrorResponseBody,
  type IValidationErrorResponseHeader,
} from "../shared/ValidationErrorResponse";

export class PutSpecimenResponseValidator extends ResponseValidator {
  public safeValidate(
    response: IHttpResponse,
  ): SafeResponseValidationResult<PutSpecimenResponse> {
    const result = this.validateAgainstDefinedResponses(response);

    if (!result.isValid && !result.error.hasResponseIssues()) {
      result.error.addStatusCodeIssue([
        200, 400, 401, 403, 404, 409, 415, 422, 429, 500,
      ]);
    }

    return result;
  }

  public validate(response: IHttpResponse): PutSpecimenResponse {
    const result = this.safeValidate(response);

    if (!result.isValid) {
      throw result.error;
    }

    return result.data;
  }

  private validateAgainstDefinedResponses(
    response: IHttpResponse,
  ): SafeResponseValidationResult<PutSpecimenResponse> {
    const error = new ResponseValidationError(response.statusCode);

    if (response.statusCode === 200) {
      const validatePutSpecimenSuccessResponseResult =
        this.validatePutSpecimenSuccessResponse(response, error);
      if (validatePutSpecimenSuccessResponseResult.isValid) {
        return validatePutSpecimenSuccessResponseResult;
      }
    }

    if (response.statusCode === 409) {
      const validateSpecimenConflictErrorResponseResult =
        this.validateSpecimenConflictErrorResponse(response, error);
      if (validateSpecimenConflictErrorResponseResult.isValid) {
        return validateSpecimenConflictErrorResponseResult;
      }
    }

    if (response.statusCode === 404) {
      const validateSpecimenNotFoundErrorResponseResult =
        this.validateSpecimenNotFoundErrorResponse(response, error);
      if (validateSpecimenNotFoundErrorResponseResult.isValid) {
        return validateSpecimenNotFoundErrorResponseResult;
      }
    }

    if (response.statusCode === 422) {
      const validateSpecimenUnprocessableEntityErrorResponseResult =
        this.validateSpecimenUnprocessableEntityErrorResponse(response, error);
      if (validateSpecimenUnprocessableEntityErrorResponseResult.isValid) {
        return validateSpecimenUnprocessableEntityErrorResponseResult;
      }
    }

    if (response.statusCode === 403) {
      const validateForbiddenErrorResponseResult =
        this.validateForbiddenErrorResponse(response, error);
      if (validateForbiddenErrorResponseResult.isValid) {
        return validateForbiddenErrorResponseResult;
      }
    }

    if (response.statusCode === 500) {
      const validateInternalServerErrorResponseResult =
        this.validateInternalServerErrorResponse(response, error);
      if (validateInternalServerErrorResponseResult.isValid) {
        return validateInternalServerErrorResponseResult;
      }
    }

    if (response.statusCode === 429) {
      const validateTooManyRequestsErrorResponseResult =
        this.validateTooManyRequestsErrorResponse(response, error);
      if (validateTooManyRequestsErrorResponseResult.isValid) {
        return validateTooManyRequestsErrorResponseResult;
      }
    }

    if (response.statusCode === 401) {
      const validateUnauthorizedErrorResponseResult =
        this.validateUnauthorizedErrorResponse(response, error);
      if (validateUnauthorizedErrorResponseResult.isValid) {
        return validateUnauthorizedErrorResponseResult;
      }
    }

    if (response.statusCode === 415) {
      const validateUnsupportedMediaTypeErrorResponseResult =
        this.validateUnsupportedMediaTypeErrorResponse(response, error);
      if (validateUnsupportedMediaTypeErrorResponseResult.isValid) {
        return validateUnsupportedMediaTypeErrorResponseResult;
      }
    }

    if (response.statusCode === 400) {
      const validateValidationErrorResponseResult =
        this.validateValidationErrorResponse(response, error);
      if (validateValidationErrorResponseResult.isValid) {
        return validateValidationErrorResponseResult;
      }
    }

    return {
      isValid: false,
      error,
    };
  }

  private validatePutSpecimenSuccessResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<PutSpecimenSuccessResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[0] &&
        "body" in definition.responses[0] &&
        definition.responses[0].body,
      "'PutSpecimenSuccessResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[0].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<IPutSpecimenSuccessResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues(
        "PutSpecimenSuccess",
        validateBodyResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[0] &&
        "header" in definition.responses[0] &&
        definition.responses[0].header,
      "'PutSpecimenSuccessResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[0].header.shape,
    );
    const validateHeaderResult = definition.responses[0].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<IPutSpecimenSuccessResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "PutSpecimenSuccess",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new PutSpecimenSuccessResponse(
        validatedResponse as IPutSpecimenSuccessResponse,
      ),
    };
  }

  private validateSpecimenConflictErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<SpecimenConflictErrorResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[1] &&
        "body" in definition.responses[1] &&
        definition.responses[1].body,
      "'SpecimenConflictErrorResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[1].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<ISpecimenConflictErrorResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues(
        "SpecimenConflictError",
        validateBodyResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[1] &&
        "header" in definition.responses[1] &&
        definition.responses[1].header,
      "'SpecimenConflictErrorResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[1].header.shape,
    );
    const validateHeaderResult = definition.responses[1].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<ISpecimenConflictErrorResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "SpecimenConflictError",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new SpecimenConflictErrorResponse(
        validatedResponse as ISpecimenConflictErrorResponse,
      ),
    };
  }

  private validateSpecimenNotFoundErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<SpecimenNotFoundErrorResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[2] &&
        "body" in definition.responses[2] &&
        definition.responses[2].body,
      "'SpecimenNotFoundErrorResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[2].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<ISpecimenNotFoundErrorResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues(
        "SpecimenNotFoundError",
        validateBodyResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[2] &&
        "header" in definition.responses[2] &&
        definition.responses[2].header,
      "'SpecimenNotFoundErrorResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[2].header.shape,
    );
    const validateHeaderResult = definition.responses[2].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<ISpecimenNotFoundErrorResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "SpecimenNotFoundError",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new SpecimenNotFoundErrorResponse(
        validatedResponse as ISpecimenNotFoundErrorResponse,
      ),
    };
  }

  private validateSpecimenUnprocessableEntityErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<SpecimenUnprocessableEntityErrorResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[3] &&
        "body" in definition.responses[3] &&
        definition.responses[3].body,
      "'SpecimenUnprocessableEntityErrorResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[3].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<ISpecimenUnprocessableEntityErrorResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues(
        "SpecimenUnprocessableEntityError",
        validateBodyResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[3] &&
        "header" in definition.responses[3] &&
        definition.responses[3].header,
      "'SpecimenUnprocessableEntityErrorResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[3].header.shape,
    );
    const validateHeaderResult = definition.responses[3].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<ISpecimenUnprocessableEntityErrorResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "SpecimenUnprocessableEntityError",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new SpecimenUnprocessableEntityErrorResponse(
        validatedResponse as ISpecimenUnprocessableEntityErrorResponse,
      ),
    };
  }

  private validateForbiddenErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<ForbiddenErrorResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[4] &&
        "body" in definition.responses[4] &&
        definition.responses[4].body,
      "'ForbiddenErrorResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[4].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<IForbiddenErrorResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues("ForbiddenError", validateBodyResult.error.issues);
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[4] &&
        "header" in definition.responses[4] &&
        definition.responses[4].header,
      "'ForbiddenErrorResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[4].header.shape,
    );
    const validateHeaderResult = definition.responses[4].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<IForbiddenErrorResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "ForbiddenError",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new ForbiddenErrorResponse(
        validatedResponse as IForbiddenErrorResponse,
      ),
    };
  }

  private validateInternalServerErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<InternalServerErrorResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[5] &&
        "body" in definition.responses[5] &&
        definition.responses[5].body,
      "'InternalServerErrorResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[5].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<IInternalServerErrorResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues(
        "InternalServerError",
        validateBodyResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[5] &&
        "header" in definition.responses[5] &&
        definition.responses[5].header,
      "'InternalServerErrorResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[5].header.shape,
    );
    const validateHeaderResult = definition.responses[5].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<IInternalServerErrorResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "InternalServerError",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new InternalServerErrorResponse(
        validatedResponse as IInternalServerErrorResponse,
      ),
    };
  }

  private validateTooManyRequestsErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<TooManyRequestsErrorResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[6] &&
        "body" in definition.responses[6] &&
        definition.responses[6].body,
      "'TooManyRequestsErrorResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[6].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<ITooManyRequestsErrorResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues(
        "TooManyRequestsError",
        validateBodyResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[6] &&
        "header" in definition.responses[6] &&
        definition.responses[6].header,
      "'TooManyRequestsErrorResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[6].header.shape,
    );
    const validateHeaderResult = definition.responses[6].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<ITooManyRequestsErrorResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "TooManyRequestsError",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new TooManyRequestsErrorResponse(
        validatedResponse as ITooManyRequestsErrorResponse,
      ),
    };
  }

  private validateUnauthorizedErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<UnauthorizedErrorResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[7] &&
        "body" in definition.responses[7] &&
        definition.responses[7].body,
      "'UnauthorizedErrorResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[7].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<IUnauthorizedErrorResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues("UnauthorizedError", validateBodyResult.error.issues);
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[7] &&
        "header" in definition.responses[7] &&
        definition.responses[7].header,
      "'UnauthorizedErrorResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[7].header.shape,
    );
    const validateHeaderResult = definition.responses[7].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<IUnauthorizedErrorResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "UnauthorizedError",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new UnauthorizedErrorResponse(
        validatedResponse as IUnauthorizedErrorResponse,
      ),
    };
  }

  private validateUnsupportedMediaTypeErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<UnsupportedMediaTypeErrorResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[8] &&
        "body" in definition.responses[8] &&
        definition.responses[8].body,
      "'UnsupportedMediaTypeErrorResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[8].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<IUnsupportedMediaTypeErrorResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues(
        "UnsupportedMediaTypeError",
        validateBodyResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[8] &&
        "header" in definition.responses[8] &&
        definition.responses[8].header,
      "'UnsupportedMediaTypeErrorResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[8].header.shape,
    );
    const validateHeaderResult = definition.responses[8].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<IUnsupportedMediaTypeErrorResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "UnsupportedMediaTypeError",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new UnsupportedMediaTypeErrorResponse(
        validatedResponse as IUnsupportedMediaTypeErrorResponse,
      ),
    };
  }

  private validateValidationErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<ValidationErrorResponse> {
    let isValid = true;
    const validatedResponse: IHttpResponse = {
      statusCode: response.statusCode,
      header: undefined,
      body: undefined,
    };

    assert(
      definition.responses[9] &&
        "body" in definition.responses[9] &&
        definition.responses[9].body,
      "'ValidationErrorResponseBody' has to be defined in the definition",
    );
    const validateBodyResult = definition.responses[9].body.safeParse(
      response.body,
    ) as unknown as ZodSafeParseResult<IValidationErrorResponseBody>;

    if (!validateBodyResult.success) {
      error.addBodyIssues("ValidationError", validateBodyResult.error.issues);
      isValid = false;
    } else {
      validatedResponse.body = validateBodyResult.data;
    }

    assert(
      definition.responses[9] &&
        "header" in definition.responses[9] &&
        definition.responses[9].header,
      "'ValidationErrorResponseHeader' has to be defined in the definition",
    );
    const coercedHeader = this.coerceHeaderToSchema(
      response.header,
      definition.responses[9].header.shape,
    );
    const validateHeaderResult = definition.responses[9].header.safeParse(
      coercedHeader,
    ) as unknown as ZodSafeParseResult<IValidationErrorResponseHeader>;

    if (!validateHeaderResult.success) {
      error.addHeaderIssues(
        "ValidationError",
        validateHeaderResult.error.issues,
      );
      isValid = false;
    } else {
      validatedResponse.header = validateHeaderResult.data;
    }

    if (!isValid) {
      return { isValid: false, error };
    }

    return {
      isValid: true,
      data: new ValidationErrorResponse(
        validatedResponse as IValidationErrorResponse,
      ),
    };
  }
}
