/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients/index.js";
import { getOperationDefinition } from "../lib/types/index.js";
import { CreateSubTodoResponseValidator } from "./CreateSubTodoResponseValidator.js";
import type {
  ICreateSubTodoRequest,
  ICreateSubTodoRequestHeader,
  ICreateSubTodoRequestParam,
  ICreateSubTodoRequestBody,
} from "./CreateSubTodoRequest.js";
import type { CreateSubTodoResponse } from "./CreateSubTodoResponse.js";

const definition = getOperationDefinition(spec, "todo", "CreateSubTodo");
const responseValidator = new CreateSubTodoResponseValidator();

const defaultHeader = {
  Accept: "application/json",

  "Content-Type": "application/json",
} as const;

export type CreateSubTodoRequestCommandInput = Omit<
  ICreateSubTodoRequest,
  "method" | "path" | "header"
> & {
  readonly header: Omit<ICreateSubTodoRequestHeader, "Accept" | "Content-Type"> &
    Partial<Pick<ICreateSubTodoRequestHeader, "Accept" | "Content-Type">>;
};

/**
 * Create new subtodo
 */
export class CreateSubTodoRequestCommand extends RequestCommand implements ICreateSubTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.POST;
  public override readonly path = definition.path;

  public override readonly header: ICreateSubTodoRequestHeader;
  public override readonly param: ICreateSubTodoRequestParam;
  declare public readonly query: undefined;
  public override readonly body: ICreateSubTodoRequestBody;

  public constructor(input: CreateSubTodoRequestCommandInput) {
    super();

    this.header = { ...defaultHeader, ...input.header };

    this.param = input.param;

    this.body = input.body;
  }

  public processResponse(response: IHttpResponse): CreateSubTodoResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
