/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod, type IHttpRequest, type IRawHttpRequestFor } from "@rexeus/typeweaver-core";

export type ICreateTodoRequestHeader = Readonly<{
  "Content-Type": "application/json";
  Accept: "application/json";
  Authorization: string;
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
}>;

export type ICreateTodoRequestBody = {
  title: string;
  description?: string | undefined;
  dueDate?: string | undefined;
  tags?: string[] | undefined;
  priority?: ("LOW" | "MEDIUM" | "HIGH") | undefined;
};

/**
 * Create new todo
 */
export type ICreateTodoRequest = IHttpRequest<
  ICreateTodoRequestHeader,
  undefined,
  undefined,
  ICreateTodoRequestBody
> & {
  readonly path: string;
  readonly method: HttpMethod.POST;
  readonly header: ICreateTodoRequestHeader;

  readonly body: ICreateTodoRequestBody;
};

export type IRawCreateTodoRequest = IRawHttpRequestFor<ICreateTodoRequest>;
