/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpResponse, HttpStatusCode } from "@rexeus/typeweaver-core";

import type { ISharedErrorResponse, SharedErrorResponse } from "../shared/SharedErrorResponses";

import type {
  ISubTodoNotFoundErrorResponse,
  SubTodoNotFoundErrorResponse,
} from "./SubTodoNotFoundErrorResponse";

import type {
  ITodoNotFoundErrorResponse,
  TodoNotFoundErrorResponse,
} from "./TodoNotFoundErrorResponse";

export type IDeleteSubTodoSuccessResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IDeleteSubTodoSuccessResponseBody = {
  message: string;
};

export type IDeleteSubTodoSuccessResponse = {
  statusCode: HttpStatusCode.OK;
  header: IDeleteSubTodoSuccessResponseHeader;
  body: IDeleteSubTodoSuccessResponseBody;
};

export class DeleteSubTodoSuccessResponse
  extends HttpResponse<IDeleteSubTodoSuccessResponseHeader, IDeleteSubTodoSuccessResponseBody>
  implements IDeleteSubTodoSuccessResponse
{
  public override readonly statusCode: HttpStatusCode.OK;

  public constructor(response: IDeleteSubTodoSuccessResponse) {
    super(response.statusCode, response.header, response.body);

    if (response.statusCode !== HttpStatusCode.OK) {
      throw new Error(
        `Invalid status code: '${response.statusCode}' for DeleteSubTodoSuccessResponse`,
      );
    }

    this.statusCode = response.statusCode;
  }
}

export type IDeleteSubTodoSuccessResponses = IDeleteSubTodoSuccessResponse;

export type DeleteSubTodoSuccessResponses = DeleteSubTodoSuccessResponse;

export type IDeleteSubTodoResponse =
  | IDeleteSubTodoSuccessResponse
  | ISharedErrorResponse
  | ISubTodoNotFoundErrorResponse
  | ITodoNotFoundErrorResponse;

export type DeleteSubTodoResponse =
  | DeleteSubTodoSuccessResponse
  | SharedErrorResponse
  | SubTodoNotFoundErrorResponse
  | TodoNotFoundErrorResponse;
