/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  getOperationDefinition,
  getResponseDefinition,
  type ResponseEntry,
  ResponseValidator,
} from "../lib/types/index.js";
import type { DeleteTodoResponse } from "./DeleteTodoResponse.js";

const definition = getOperationDefinition(spec, "todo", "DeleteTodo");

const deleteTodoSuccessDefinition = getResponseDefinition(
  definition.responses,
  "DeleteTodoSuccess",
);

const deleteTodoBodyOnlyDefinition = getResponseDefinition(
  definition.responses,
  "DeleteTodoBodyOnly",
);

const deleteTodoNoContentDefinition = getResponseDefinition(
  definition.responses,
  "DeleteTodoNoContent",
);

const todoNotFoundErrorDefinition = getResponseDefinition(
  definition.responses,
  "TodoNotFoundError",
);

const forbiddenErrorDefinition = getResponseDefinition(definition.responses, "ForbiddenError");

const internalServerErrorDefinition = getResponseDefinition(
  definition.responses,
  "InternalServerError",
);

const tooManyRequestsErrorDefinition = getResponseDefinition(
  definition.responses,
  "TooManyRequestsError",
);

const unauthorizedErrorDefinition = getResponseDefinition(
  definition.responses,
  "UnauthorizedError",
);

const unsupportedMediaTypeErrorDefinition = getResponseDefinition(
  definition.responses,
  "UnsupportedMediaTypeError",
);

const validationErrorDefinition = getResponseDefinition(definition.responses, "ValidationError");

export class DeleteTodoResponseValidator extends ResponseValidator<DeleteTodoResponse> {
  protected override readonly expectedStatusCodes = [200, 204, 400, 401, 403, 404, 415, 429, 500];

  protected override readonly responseEntries: readonly ResponseEntry[] = [
    {
      name: "DeleteTodoSuccess",
      statusCode: 204,
      headerSchema: deleteTodoSuccessDefinition.header,
      bodySchema: deleteTodoSuccessDefinition.body,
    },

    {
      name: "DeleteTodoBodyOnly",
      statusCode: 200,
      headerSchema: deleteTodoBodyOnlyDefinition.header,
      bodySchema: deleteTodoBodyOnlyDefinition.body,
    },

    {
      name: "DeleteTodoNoContent",
      statusCode: 204,
      headerSchema: deleteTodoNoContentDefinition.header,
      bodySchema: deleteTodoNoContentDefinition.body,
    },

    {
      name: "TodoNotFoundError",
      statusCode: 404,
      headerSchema: todoNotFoundErrorDefinition.header,
      bodySchema: todoNotFoundErrorDefinition.body,
    },

    {
      name: "ForbiddenError",
      statusCode: 403,
      headerSchema: forbiddenErrorDefinition.header,
      bodySchema: forbiddenErrorDefinition.body,
    },

    {
      name: "InternalServerError",
      statusCode: 500,
      headerSchema: internalServerErrorDefinition.header,
      bodySchema: internalServerErrorDefinition.body,
    },

    {
      name: "TooManyRequestsError",
      statusCode: 429,
      headerSchema: tooManyRequestsErrorDefinition.header,
      bodySchema: tooManyRequestsErrorDefinition.body,
    },

    {
      name: "UnauthorizedError",
      statusCode: 401,
      headerSchema: unauthorizedErrorDefinition.header,
      bodySchema: unauthorizedErrorDefinition.body,
    },

    {
      name: "UnsupportedMediaTypeError",
      statusCode: 415,
      headerSchema: unsupportedMediaTypeErrorDefinition.header,
      bodySchema: unsupportedMediaTypeErrorDefinition.body,
    },

    {
      name: "ValidationError",
      statusCode: 400,
      headerSchema: validationErrorDefinition.header,
      bodySchema: validationErrorDefinition.body,
    },
  ];
}
