/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod } from "@rexeus/typeweaver-core";
import { type DeleteSubTodoResponse } from "./DeleteSubTodoResponse";

import { ForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import { InternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import { TooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import { UnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import { UnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import { ValidationErrorResponse } from "../shared/ValidationErrorResponse";

import { SubTodoNotFoundErrorResponse } from "./SubTodoNotFoundErrorResponse";

import { TodoNotFoundErrorResponse } from "./TodoNotFoundErrorResponse";

export type IDeleteSubTodoRequestHeader = {
  Accept: "application/json";
  Authorization: string;
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IDeleteSubTodoRequestParam = {
  todoId: string;
  subtodoId: string;
};

export type IDeleteSubTodoRequest = {
  path: string;
  method: HttpMethod.DELETE;
  header: IDeleteSubTodoRequestHeader;
  param: IDeleteSubTodoRequestParam;
};

export type SuccessfulDeleteSubTodoResponse = Exclude<
  DeleteSubTodoResponse,
  | ForbiddenErrorResponse
  | InternalServerErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse
  | UnsupportedMediaTypeErrorResponse
  | ValidationErrorResponse
  | SubTodoNotFoundErrorResponse
  | TodoNotFoundErrorResponse
>;
