/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IRawHttpRequest,
  type SafeRequestValidationResult,
  RequestValidationError,
} from "@rexeus/typeweaver-core";
import { getOperationDefinition, RequestValidator } from "../lib/types/index.js";
import type {
  IDeleteTodoRequest,
  IDeleteTodoRequestHeader,
  IDeleteTodoRequestParam,
} from "./DeleteTodoRequest.js";

const definition = getOperationDefinition(spec, "todo", "DeleteTodo");

export class DeleteTodoRequestValidator extends RequestValidator<IDeleteTodoRequest> {
  public safeValidate(request: IRawHttpRequest): SafeRequestValidationResult<IDeleteTodoRequest> {
    const error = new RequestValidationError();

    const headerSchema = this.requireRequestSchema(definition.request.header, "header");
    const coercedHeader = this.coerceHeaderToSchema(request.header, headerSchema);
    const headerMultiplicityIssues = this.findMultiplicityIssues(
      request.header,
      headerSchema,
      false,
    );
    if (headerMultiplicityIssues.length > 0) {
      error.addHeaderIssues(headerMultiplicityIssues);
    }
    const headerResult = this.safeParseAs<IDeleteTodoRequestHeader>(headerSchema, coercedHeader);
    if (!headerResult.success) {
      error.addHeaderIssues(headerResult.error.issues);
    }

    const paramSchema = this.requireRequestSchema(definition.request.param, "param");
    const paramResult = this.safeParseAs<IDeleteTodoRequestParam>(paramSchema, request.param);
    if (!paramResult.success) {
      error.addPathParamIssues(paramResult.error.issues);
    }

    if (error.hasIssues() || !headerResult.success || !paramResult.success) {
      return {
        isValid: false,
        error,
      };
    }

    return {
      isValid: true,
      data: {
        method: HttpMethod.DELETE,
        path: request.path,

        header: headerResult.data,
        param: paramResult.data,
      },
    };
  }

  public validate(request: IRawHttpRequest): IDeleteTodoRequest {
    const result = this.safeValidate(request);

    if (!result.isValid) {
      throw result.error;
    }

    return result.data;
  }
}
