/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpResponse, HttpStatusCode } from "@rexeus/typeweaver-core";

import type {
  IForbiddenErrorResponse,
  ForbiddenErrorResponse,
} from "../shared/ForbiddenErrorResponse";

import type {
  IInternalServerErrorResponse,
  InternalServerErrorResponse,
} from "../shared/InternalServerErrorResponse";

import type {
  ITooManyRequestsErrorResponse,
  TooManyRequestsErrorResponse,
} from "../shared/TooManyRequestsErrorResponse";

import type {
  IUnauthorizedErrorResponse,
  UnauthorizedErrorResponse,
} from "../shared/UnauthorizedErrorResponse";

import type {
  IUnsupportedMediaTypeErrorResponse,
  UnsupportedMediaTypeErrorResponse,
} from "../shared/UnsupportedMediaTypeErrorResponse";

import type {
  IValidationErrorResponse,
  ValidationErrorResponse,
} from "../shared/ValidationErrorResponse";

import type {
  ITodoNotFoundErrorResponse,
  TodoNotFoundErrorResponse,
} from "./TodoNotFoundErrorResponse";

export type IDeleteTodoSuccessResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IDeleteTodoSuccessResponse = {
  statusCode: HttpStatusCode.NO_CONTENT;
  header: IDeleteTodoSuccessResponseHeader;
};

export class DeleteTodoSuccessResponse
  extends HttpResponse<IDeleteTodoSuccessResponseHeader, undefined>
  implements IDeleteTodoSuccessResponse
{
  public override readonly statusCode = HttpStatusCode.NO_CONTENT;

  public constructor(response: Omit<IDeleteTodoSuccessResponse, "statusCode">) {
    super(HttpStatusCode.NO_CONTENT, response.header, undefined);
  }
}

export type IDeleteTodoSuccessResponses = IDeleteTodoSuccessResponse;

export type DeleteTodoSuccessResponses = DeleteTodoSuccessResponse;

export type IDeleteTodoResponse =
  | IDeleteTodoSuccessResponse
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse
  | ITodoNotFoundErrorResponse;

export type DeleteTodoResponse =
  | DeleteTodoSuccessResponse
  | ForbiddenErrorResponse
  | InternalServerErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse
  | UnsupportedMediaTypeErrorResponse
  | ValidationErrorResponse
  | TodoNotFoundErrorResponse;
