/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod } from "@rexeus/typeweaver-core";
import { type GetTodoResponse } from "./GetTodoResponse";

import type { SharedErrorResponse } from "../shared/SharedErrorResponses";

import { TodoNotFoundErrorResponse } from "./TodoNotFoundErrorResponse";

export type IGetTodoRequestHeader = {
  Accept: "application/json";
  Authorization: string;
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IGetTodoRequestParam = {
  todoId: string;
};

export type IGetTodoRequest = {
  path: string;
  method: HttpMethod.GET;
  header: IGetTodoRequestHeader;
  param: IGetTodoRequestParam;
};

export type SuccessfulGetTodoResponse = Exclude<
  GetTodoResponse,
  SharedErrorResponse | TodoNotFoundErrorResponse
>;
