/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients/index.js";
import { getOperationDefinition } from "../lib/types/index.js";
import { GetTodoResponseValidator } from "./GetTodoResponseValidator.js";
import type {
  IGetTodoRequest,
  IGetTodoRequestHeader,
  IGetTodoRequestParam,
} from "./GetTodoRequest.js";
import type { GetTodoResponse } from "./GetTodoResponse.js";

const definition = getOperationDefinition(spec, "todo", "GetTodo");
const responseValidator = new GetTodoResponseValidator();

const defaultHeader = {
  Accept: "application/json",
} as const;

export type GetTodoRequestCommandInput = Omit<IGetTodoRequest, "method" | "path" | "header"> & {
  readonly header: Omit<IGetTodoRequestHeader, "Accept"> &
    Partial<Pick<IGetTodoRequestHeader, "Accept">>;
};

/**
 * Get todo
 */
export class GetTodoRequestCommand extends RequestCommand implements IGetTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.GET;
  public override readonly path = definition.path;

  public override readonly header: IGetTodoRequestHeader;
  public override readonly param: IGetTodoRequestParam;
  declare public readonly query: undefined;
  declare public readonly body: undefined;

  public constructor(input: GetTodoRequestCommandInput) {
    super();

    this.header = { ...defaultHeader, ...input.header };

    this.param = input.param;
  }

  public processResponse(response: IHttpResponse): GetTodoResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
