/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import definition from "../definition/todo/queries/HeadTodoDefinition";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  createUnknownResponse,
} from "@rexeus/typeweaver-core";
import { RequestCommand, type ProcessResponseOptions } from "../lib/clients";
import { HeadTodoResponseValidator } from "./HeadTodoResponseValidator";
import type {
  IHeadTodoRequest,
  IHeadTodoRequestHeader,
  IHeadTodoRequestParam,
  SuccessfulHeadTodoResponse,
} from "./HeadTodoRequest";

export class HeadTodoRequestCommand extends RequestCommand implements IHeadTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.HEAD;
  public override readonly path = definition.path;

  public override readonly header: IHeadTodoRequestHeader;
  public override readonly param: IHeadTodoRequestParam;
  declare public readonly query: undefined;
  declare public readonly body: undefined;

  private readonly responseValidator: HeadTodoResponseValidator;

  public constructor(input: Omit<IHeadTodoRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.param = input.param;

    this.responseValidator = new HeadTodoResponseValidator();
  }

  public processResponse(
    response: IHttpResponse,
    options: ProcessResponseOptions,
  ): SuccessfulHeadTodoResponse {
    try {
      const result = this.responseValidator.validate(response);

      if (result._tag === "HeadTodoSuccess") {
        return result as SuccessfulHeadTodoResponse;
      }

      throw result;
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        const unknownResponse = createUnknownResponse(
          response.statusCode,
          response.header,
          response.body,
          error,
        );

        if (
          options.unknownResponseHandling === "passthrough" &&
          options.isSuccessStatusCode(response.statusCode)
        ) {
          return unknownResponse as any;
        }

        throw unknownResponse;
      }
      throw error;
    }
  }
}
