/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpResponse, HttpStatusCode } from "@rexeus/typeweaver-core";

import type { ISharedErrorResponse, SharedErrorResponse } from "../shared/SharedErrorResponses";

import type {
  ITodoNotFoundErrorResponse,
  TodoNotFoundErrorResponse,
} from "./TodoNotFoundErrorResponse";

export type IHeadTodoSuccessResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IHeadTodoSuccessResponse = {
  statusCode: HttpStatusCode.OK;
  header: IHeadTodoSuccessResponseHeader;
};

export class HeadTodoSuccessResponse
  extends HttpResponse<IHeadTodoSuccessResponseHeader, undefined>
  implements IHeadTodoSuccessResponse
{
  public override readonly statusCode: HttpStatusCode.OK;

  public constructor(response: IHeadTodoSuccessResponse) {
    super(response.statusCode, response.header, undefined);

    if (response.statusCode !== HttpStatusCode.OK) {
      throw new Error(`Invalid status code: '${response.statusCode}' for HeadTodoSuccessResponse`);
    }

    this.statusCode = response.statusCode;
  }
}

export type IHeadTodoSuccessResponses = IHeadTodoSuccessResponse;

export type HeadTodoSuccessResponses = HeadTodoSuccessResponse;

export type IHeadTodoResponse =
  | IHeadTodoSuccessResponse
  | ISharedErrorResponse
  | ITodoNotFoundErrorResponse;

export type HeadTodoResponse =
  | HeadTodoSuccessResponse
  | SharedErrorResponse
  | TodoNotFoundErrorResponse;
