/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients/index.js";
import { getOperationDefinition } from "../lib/types/index.js";
import { HeadTodoResponseValidator } from "./HeadTodoResponseValidator.js";
import type {
  IHeadTodoRequest,
  IHeadTodoRequestHeader,
  IHeadTodoRequestParam,
} from "./HeadTodoRequest.js";
import type { HeadTodoResponse } from "./HeadTodoResponse.js";

const definition = getOperationDefinition(spec, "todo", "HeadTodo");
const responseValidator = new HeadTodoResponseValidator();

export class HeadTodoRequestCommand extends RequestCommand implements IHeadTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.HEAD;
  public override readonly path = definition.path;

  public override readonly header: IHeadTodoRequestHeader;
  public override readonly param: IHeadTodoRequestParam;
  declare public readonly query: undefined;
  declare public readonly body: undefined;

  public constructor(input: Omit<IHeadTodoRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.param = input.param;
  }

  public processResponse(response: IHttpResponse): HeadTodoResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
