/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod } from "@rexeus/typeweaver-core";
import { type ListTodosResponse } from "./ListTodosResponse";

import type { SharedErrorResponse } from "../shared/SharedErrorResponses";

export type IListTodosRequestHeader = {
  Accept: "application/json";
  Authorization: string;
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IListTodosRequestQuery = {
  status?: ("TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED") | undefined;
  priority?: ("LOW" | "MEDIUM" | "HIGH") | undefined;
  tags?: string[] | undefined;
  limit?: string | undefined;
  nextToken?: string | undefined;
  sortBy?: ("title" | "dueDate" | "priority" | "createdAt" | "modifiedAt") | undefined;
  sortOrder?: ("asc" | "desc") | undefined;
  search?: string | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
};

export type IListTodosRequest = {
  path: string;
  method: HttpMethod.GET;
  header: IListTodosRequestHeader;

  query: IListTodosRequestQuery;
};

export type SuccessfulListTodosResponse = Exclude<ListTodosResponse, SharedErrorResponse>;
