/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients/index.js";
import { getOperationDefinition } from "../lib/types/index.js";
import { ListSubTodosResponseValidator } from "./ListSubTodosResponseValidator.js";
import type {
  IListSubTodosRequest,
  IListSubTodosRequestHeader,
  IListSubTodosRequestParam,
  IListSubTodosRequestQuery,
} from "./ListSubTodosRequest.js";
import type { ListSubTodosResponse } from "./ListSubTodosResponse.js";

const definition = getOperationDefinition(spec, "todo", "ListSubTodos");
const responseValidator = new ListSubTodosResponseValidator();

const defaultHeader = {
  Accept: "application/json",
} as const;

export type ListSubTodosRequestCommandInput = Omit<
  IListSubTodosRequest,
  "method" | "path" | "header"
> & {
  readonly header: Omit<IListSubTodosRequestHeader, "Accept"> &
    Partial<Pick<IListSubTodosRequestHeader, "Accept">>;
};

/**
 * List subtodos for a specific todo
 */
export class ListSubTodosRequestCommand extends RequestCommand implements IListSubTodosRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.GET;
  public override readonly path = definition.path;

  public override readonly header: IListSubTodosRequestHeader;
  public override readonly param: IListSubTodosRequestParam;
  public override readonly query: IListSubTodosRequestQuery;
  declare public readonly body: undefined;

  public constructor(input: ListSubTodosRequestCommandInput) {
    super();

    this.header = { ...defaultHeader, ...input.header };

    this.param = input.param;

    this.query = input.query;
  }

  public processResponse(response: IHttpResponse): ListSubTodosResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
