/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod, type IHttpRequest, type IRawHttpRequestFor } from "@rexeus/typeweaver-core";

export type IListSubTodosRequestHeader = Readonly<{
  Accept: "application/json";
  Authorization: string;
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
}>;

export type IListSubTodosRequestParam = Readonly<{
  todoId: string;
}>;

export type IListSubTodosRequestQuery = Readonly<
  | {
      limit?: string | undefined;
      nextToken?: string | undefined;
      sortBy?: ("title" | "dueDate" | "priority" | "createdAt" | "modifiedAt") | undefined;
      sortOrder?: ("asc" | "desc") | undefined;
    }
  | undefined
>;

/**
 * List subtodos for a specific todo
 */
export type IListSubTodosRequest = IHttpRequest<
  IListSubTodosRequestHeader,
  IListSubTodosRequestParam,
  IListSubTodosRequestQuery,
  undefined
> & {
  readonly path: string;
  readonly method: HttpMethod.GET;
  readonly header: IListSubTodosRequestHeader;
  readonly param: IListSubTodosRequestParam;
  readonly query: IListSubTodosRequestQuery;
};

export type IRawListSubTodosRequest = IRawHttpRequestFor<IListSubTodosRequest>;
