/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod } from "@rexeus/typeweaver-core";
import type { OptionsTodoResponse } from "./OptionsTodoResponse";

import type { IForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../shared/ValidationErrorResponse";

import type { ITodoNotFoundErrorResponse } from "./TodoNotFoundErrorResponse";

export type IOptionsTodoRequestHeader = {
  Accept: "application/json";
  Authorization: string;
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
  "Access-Control-Request-Method"?: string | undefined;
  "Access-Control-Request-Headers"?: string[] | undefined;
};

export type IOptionsTodoRequestParam = {
  todoId: string;
};

export type IOptionsTodoRequest = {
  path: string;
  method: HttpMethod.OPTIONS;
  header: IOptionsTodoRequestHeader;
  param: IOptionsTodoRequestParam;
};

export type SuccessfulOptionsTodoResponse = Exclude<
  OptionsTodoResponse,
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse
  | ITodoNotFoundErrorResponse
>;
