/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import spec from "../spec/spec";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients";
import { OptionsTodoResponseValidator } from "./OptionsTodoResponseValidator";
import type {
  IOptionsTodoRequest,
  IOptionsTodoRequestHeader,
  IOptionsTodoRequestParam,
} from "./OptionsTodoRequest";
import type { OptionsTodoResponse } from "./OptionsTodoResponse";

const definition = spec.resources["todo"]!.operations.find(
  (operation) => operation.operationId === "OptionsTodo",
)!;
const responseValidator = new OptionsTodoResponseValidator();

export class OptionsTodoRequestCommand extends RequestCommand implements IOptionsTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.OPTIONS;
  public override readonly path = definition.path;

  public override readonly header: IOptionsTodoRequestHeader;
  public override readonly param: IOptionsTodoRequestParam;
  declare public readonly query: undefined;
  declare public readonly body: undefined;

  public constructor(input: Omit<IOptionsTodoRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.param = input.param;
  }

  public processResponse(response: IHttpResponse): OptionsTodoResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
