/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

import type { IForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../shared/ValidationErrorResponse";

import type { ITodoNotFoundErrorResponse } from "./TodoNotFoundErrorResponse";

export type IOptionsTodoSuccessResponseHeader = {
  Allow: string[];
  "Access-Control-Allow-Origin"?: string | undefined;
  "Access-Control-Allow-Methods"?: string[] | undefined;
  "Access-Control-Allow-Headers"?: string[] | undefined;
  "Access-Control-Max-Age"?: string | undefined;
};

export type IOptionsTodoSuccessResponse = ITypedHttpResponse<
  "OptionsTodoSuccess",
  HttpStatusCode.OK,
  IOptionsTodoSuccessResponseHeader,
  undefined
>;

export const createOptionsTodoSuccessResponse = (
  input: Omit<IOptionsTodoSuccessResponse, "type" | "statusCode">,
): IOptionsTodoSuccessResponse => ({
  ...input,
  type: "OptionsTodoSuccess",
  statusCode: HttpStatusCode.OK,
});

export type OptionsTodoResponse =
  | IOptionsTodoSuccessResponse
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse
  | ITodoNotFoundErrorResponse;
