/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients/index.js";
import { getOperationDefinition } from "../lib/types/index.js";
import { PutTodoResponseValidator } from "./PutTodoResponseValidator.js";
import type {
  IPutTodoRequest,
  IPutTodoRequestHeader,
  IPutTodoRequestParam,
  IPutTodoRequestBody,
} from "./PutTodoRequest.js";
import type { PutTodoResponse } from "./PutTodoResponse.js";

const definition = getOperationDefinition(spec, "todo", "PutTodo");
const responseValidator = new PutTodoResponseValidator();

const defaultHeader = {
  Accept: "application/json",

  "Content-Type": "application/json",
} as const;

export type PutTodoRequestCommandInput = Omit<IPutTodoRequest, "method" | "path" | "header"> & {
  readonly header: Omit<IPutTodoRequestHeader, "Accept" | "Content-Type"> &
    Partial<Pick<IPutTodoRequestHeader, "Accept" | "Content-Type">>;
};

/**
 * Replace todo completely
 */
export class PutTodoRequestCommand extends RequestCommand implements IPutTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.PUT;
  public override readonly path = definition.path;

  public override readonly header: IPutTodoRequestHeader;
  public override readonly param: IPutTodoRequestParam;
  declare public readonly query: undefined;
  public override readonly body: IPutTodoRequestBody;

  public constructor(input: PutTodoRequestCommandInput) {
    super();

    this.header = { ...defaultHeader, ...input.header };

    this.param = input.param;

    this.body = input.body;
  }

  public processResponse(response: IHttpResponse): PutTodoResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
