/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod } from "@rexeus/typeweaver-core";

export type IPutTodoRequestHeader = {
  "Content-Type": "application/json";
  Accept: "application/json";
  Authorization: string;
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IPutTodoRequestParam = {
  todoId: string;
};

export type IPutTodoRequestBody = {
  accountId: string;
  parentId?: string | undefined;
  title: string;
  description?: string | undefined;
  status: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
  dueDate?: string | undefined;
  tags?: string[] | undefined;
  priority?: ("LOW" | "MEDIUM" | "HIGH") | undefined;
};

/**
 * Replace todo completely
 */
export type IPutTodoRequest = {
  path: string;
  method: HttpMethod.PUT;
  header: IPutTodoRequestHeader;
  param: IPutTodoRequestParam;

  body: IPutTodoRequestBody;
};
