/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec";
import {
  type IHttpRequest,
  type SafeRequestValidationResult,
  RequestValidationError,
} from "@rexeus/typeweaver-core";
import { getOperationDefinition, RequestValidator } from "../lib/types";
import type { IQueryTodoRequest } from "./QueryTodoRequest";

const definition = getOperationDefinition(spec, "todo", "QueryTodo");

export class QueryTodoRequestValidator extends RequestValidator {
  public safeValidate(request: IHttpRequest): SafeRequestValidationResult<IQueryTodoRequest> {
    const error = new RequestValidationError();
    const validatedRequest: IHttpRequest = {
      method: request.method,
      path: request.path,
      query: undefined,
      header: undefined,
      body: undefined,
      param: undefined,
    };

    if (definition.request.body) {
      const result = definition.request.body.safeParse(request.body);

      if (!result.success) {
        error.addBodyIssues(result.error.issues);
      } else {
        validatedRequest.body = result.data;
      }
    }

    if (definition.request.header) {
      const coercedHeader = this.coerceHeaderToSchema(
        request.header,
        this.getSchema(definition.request.header),
      );
      const result = definition.request.header.safeParse(coercedHeader);

      if (!result.success) {
        error.addHeaderIssues(result.error.issues);
      } else {
        validatedRequest.header = result.data as IHttpRequest["header"];
      }
    }

    if (definition.request.query) {
      const coercedQuery = this.coerceQueryToSchema(
        request.query,
        this.getSchema(definition.request.query),
      );
      const result = definition.request.query.safeParse(coercedQuery);

      if (!result.success) {
        error.addQueryIssues(result.error.issues);
      } else {
        validatedRequest.query = result.data as IHttpRequest["query"];
      }
    }

    if (error.hasIssues()) {
      return {
        isValid: false,
        error,
      };
    }

    return {
      isValid: true,
      data: validatedRequest as IQueryTodoRequest,
    };
  }

  public validate(request: IHttpRequest): IQueryTodoRequest {
    const result = this.safeValidate(request);

    if (!result.isValid) {
      throw result.error;
    }

    return result.data;
  }
}
