/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients/index.js";
import { getOperationDefinition } from "../lib/types/index.js";
import { QueryTodoResponseValidator } from "./QueryTodoResponseValidator.js";
import type {
  IQueryTodoRequest,
  IQueryTodoRequestHeader,
  IQueryTodoRequestQuery,
  IQueryTodoRequestBody,
} from "./QueryTodoRequest.js";
import type { QueryTodoResponse } from "./QueryTodoResponse.js";

const definition = getOperationDefinition(spec, "todo", "QueryTodo");
const responseValidator = new QueryTodoResponseValidator();

const defaultHeader = {
  Accept: "application/json",

  "Content-Type": "application/json",
} as const;

export type QueryTodoRequestCommandInput = Omit<IQueryTodoRequest, "method" | "path" | "header"> & {
  readonly header: Omit<IQueryTodoRequestHeader, "Accept" | "Content-Type"> &
    Partial<Pick<IQueryTodoRequestHeader, "Accept" | "Content-Type">>;
};

/**
 * Query todos with advanced search criteria
 */
export class QueryTodoRequestCommand extends RequestCommand implements IQueryTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.POST;
  public override readonly path = definition.path;

  public override readonly header: IQueryTodoRequestHeader;
  declare public readonly param: undefined;
  public override readonly query: IQueryTodoRequestQuery;
  public override readonly body: IQueryTodoRequestBody;

  public constructor(input: QueryTodoRequestCommandInput) {
    super();

    this.header = { ...defaultHeader, ...input.header };

    this.query = input.query;

    this.body = input.body;
  }

  public processResponse(response: IHttpResponse): QueryTodoResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
