/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import definition from "../definition/todo/queries/QueryTodoDefinition";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients";
import { QueryTodoResponseValidator } from "./QueryTodoResponseValidator";
import type {
  IQueryTodoRequest,
  IQueryTodoRequestHeader,
  IQueryTodoRequestQuery,
  IQueryTodoRequestBody,
} from "./QueryTodoRequest";
import type { QueryTodoResponse } from "./QueryTodoResponse";

const responseValidator = new QueryTodoResponseValidator();

export class QueryTodoRequestCommand extends RequestCommand implements IQueryTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.POST;
  public override readonly path = definition.path;

  public override readonly header: IQueryTodoRequestHeader;
  declare public readonly param: undefined;
  public override readonly query: IQueryTodoRequestQuery;
  public override readonly body: IQueryTodoRequestBody;

  public constructor(input: Omit<IQueryTodoRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.query = input.query;

    this.body = input.body;
  }

  public processResponse(response: IHttpResponse): QueryTodoResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
