/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type ISubTodoStatusTransitionInvalidErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type ISubTodoStatusTransitionInvalidErrorResponseBody = {
  message: "SubTodo status transition is conflicting with its status or parent todo status";
  code: "SUBTODO_STATUS_TRANSITION_INVALID_ERROR";
  context: {
    todoId: string;
    subtodoId: string;
    currentTodoStatus: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
    currentSubtodoStatus: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
  };
  actualValues: {
    requestedSubtodoStatus: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
  };
  expectedValues: {
    allowedSubtodoStatuses: ("TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED")[];
  };
};

export type ISubTodoStatusTransitionInvalidErrorResponse = ITypedHttpResponse<
  "SubTodoStatusTransitionInvalidError",
  ISubTodoStatusTransitionInvalidErrorResponseHeader,
  ISubTodoStatusTransitionInvalidErrorResponseBody
> & {
  readonly statusCode: HttpStatusCode.CONFLICT;
  readonly header: ISubTodoStatusTransitionInvalidErrorResponseHeader;
  readonly body: ISubTodoStatusTransitionInvalidErrorResponseBody;
};

export const createSubTodoStatusTransitionInvalidErrorResponse = (
  input: Omit<ISubTodoStatusTransitionInvalidErrorResponse, "type" | "statusCode">,
): ISubTodoStatusTransitionInvalidErrorResponse => ({
  type: "SubTodoStatusTransitionInvalidError",
  statusCode: HttpStatusCode.CONFLICT,
  ...input,
});
