/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITaggedHttpResponse } from "@rexeus/typeweaver-core";

export type ISubTodoNotChangeableErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type ISubTodoNotChangeableErrorResponseBody = {
  message: "SubTodo in current status or because of parent todo status cannot be changed";
  code: "SUBTODO_NOT_CHANGEABLE_ERROR";
  context: {
    todoId: string;
    subtodoId: string;
    currentTodoStatus: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
    currentSubtodoStatus: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
  };
  expectedValues: {
    allowedTodoStatuses: ("TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED")[];
    allowedSubtodoStatuses: ("TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED")[];
  };
};

export type ISubTodoNotChangeableErrorResponse = ITaggedHttpResponse<
  "SubTodoNotChangeableError",
  ISubTodoNotChangeableErrorResponseHeader,
  ISubTodoNotChangeableErrorResponseBody
> & {
  readonly statusCode: HttpStatusCode.CONFLICT;
  readonly header: ISubTodoNotChangeableErrorResponseHeader;
  readonly body: ISubTodoNotChangeableErrorResponseBody;
};

export const createSubTodoNotChangeableErrorResponse = (
  input: Omit<ISubTodoNotChangeableErrorResponse, "_tag" | "statusCode">,
): ISubTodoNotChangeableErrorResponse => ({
  _tag: "SubTodoNotChangeableError",
  statusCode: HttpStatusCode.CONFLICT,
  ...input,
});
