/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import {
  TypeweaverRouter,
  type RequestHandler,
  type TypeweaverRouterOptions,
} from "../lib/server";

import type { IListTodosRequest } from "./ListTodosRequest";
import { ListTodosRequestValidator } from "./ListTodosRequestValidator";
import type { ListTodosResponse } from "./ListTodosResponse";

import type { ICreateTodoRequest } from "./CreateTodoRequest";
import { CreateTodoRequestValidator } from "./CreateTodoRequestValidator";
import type { CreateTodoResponse } from "./CreateTodoResponse";

import type { IQueryTodoRequest } from "./QueryTodoRequest";
import { QueryTodoRequestValidator } from "./QueryTodoRequestValidator";
import type { QueryTodoResponse } from "./QueryTodoResponse";

import type { IGetTodoRequest } from "./GetTodoRequest";
import { GetTodoRequestValidator } from "./GetTodoRequestValidator";
import type { GetTodoResponse } from "./GetTodoResponse";

import type { IPutTodoRequest } from "./PutTodoRequest";
import { PutTodoRequestValidator } from "./PutTodoRequestValidator";
import type { PutTodoResponse } from "./PutTodoResponse";

import type { IUpdateTodoRequest } from "./UpdateTodoRequest";
import { UpdateTodoRequestValidator } from "./UpdateTodoRequestValidator";
import type { UpdateTodoResponse } from "./UpdateTodoResponse";

import type { IDeleteTodoRequest } from "./DeleteTodoRequest";
import { DeleteTodoRequestValidator } from "./DeleteTodoRequestValidator";
import type { DeleteTodoResponse } from "./DeleteTodoResponse";

import type { IOptionsTodoRequest } from "./OptionsTodoRequest";
import { OptionsTodoRequestValidator } from "./OptionsTodoRequestValidator";
import type { OptionsTodoResponse } from "./OptionsTodoResponse";

import type { IUpdateTodoStatusRequest } from "./UpdateTodoStatusRequest";
import { UpdateTodoStatusRequestValidator } from "./UpdateTodoStatusRequestValidator";
import type { UpdateTodoStatusResponse } from "./UpdateTodoStatusResponse";

import type { IListSubTodosRequest } from "./ListSubTodosRequest";
import { ListSubTodosRequestValidator } from "./ListSubTodosRequestValidator";
import type { ListSubTodosResponse } from "./ListSubTodosResponse";

import type { ICreateSubTodoRequest } from "./CreateSubTodoRequest";
import { CreateSubTodoRequestValidator } from "./CreateSubTodoRequestValidator";
import type { CreateSubTodoResponse } from "./CreateSubTodoResponse";

import type { IQuerySubTodoRequest } from "./QuerySubTodoRequest";
import { QuerySubTodoRequestValidator } from "./QuerySubTodoRequestValidator";
import type { QuerySubTodoResponse } from "./QuerySubTodoResponse";

import type { IUpdateSubTodoRequest } from "./UpdateSubTodoRequest";
import { UpdateSubTodoRequestValidator } from "./UpdateSubTodoRequestValidator";
import type { UpdateSubTodoResponse } from "./UpdateSubTodoResponse";

import type { IDeleteSubTodoRequest } from "./DeleteSubTodoRequest";
import { DeleteSubTodoRequestValidator } from "./DeleteSubTodoRequestValidator";
import type { DeleteSubTodoResponse } from "./DeleteSubTodoResponse";

export type TodoApiHandler = {
  handleListTodosRequest: RequestHandler<IListTodosRequest, ListTodosResponse>;

  handleCreateTodoRequest: RequestHandler<
    ICreateTodoRequest,
    CreateTodoResponse
  >;

  handleQueryTodoRequest: RequestHandler<IQueryTodoRequest, QueryTodoResponse>;

  handleGetTodoRequest: RequestHandler<IGetTodoRequest, GetTodoResponse>;

  handlePutTodoRequest: RequestHandler<IPutTodoRequest, PutTodoResponse>;

  handleUpdateTodoRequest: RequestHandler<
    IUpdateTodoRequest,
    UpdateTodoResponse
  >;

  handleDeleteTodoRequest: RequestHandler<
    IDeleteTodoRequest,
    DeleteTodoResponse
  >;

  handleOptionsTodoRequest: RequestHandler<
    IOptionsTodoRequest,
    OptionsTodoResponse
  >;

  handleUpdateTodoStatusRequest: RequestHandler<
    IUpdateTodoStatusRequest,
    UpdateTodoStatusResponse
  >;

  handleListSubTodosRequest: RequestHandler<
    IListSubTodosRequest,
    ListSubTodosResponse
  >;

  handleCreateSubTodoRequest: RequestHandler<
    ICreateSubTodoRequest,
    CreateSubTodoResponse
  >;

  handleQuerySubTodoRequest: RequestHandler<
    IQuerySubTodoRequest,
    QuerySubTodoResponse
  >;

  handleUpdateSubTodoRequest: RequestHandler<
    IUpdateSubTodoRequest,
    UpdateSubTodoResponse
  >;

  handleDeleteSubTodoRequest: RequestHandler<
    IDeleteSubTodoRequest,
    DeleteSubTodoResponse
  >;
};

export class TodoRouter extends TypeweaverRouter<TodoApiHandler> {
  public constructor(options: TypeweaverRouterOptions<TodoApiHandler>) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.route(
      "GET",
      "/todos",
      new ListTodosRequestValidator(),
      this.requestHandlers.handleListTodosRequest.bind(this.requestHandlers),
    );

    this.route(
      "POST",
      "/todos",
      new CreateTodoRequestValidator(),
      this.requestHandlers.handleCreateTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "POST",
      "/todos/query",
      new QueryTodoRequestValidator(),
      this.requestHandlers.handleQueryTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "GET",
      "/todos/:todoId",
      new GetTodoRequestValidator(),
      this.requestHandlers.handleGetTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "PUT",
      "/todos/:todoId",
      new PutTodoRequestValidator(),
      this.requestHandlers.handlePutTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "PATCH",
      "/todos/:todoId",
      new UpdateTodoRequestValidator(),
      this.requestHandlers.handleUpdateTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "DELETE",
      "/todos/:todoId",
      new DeleteTodoRequestValidator(),
      this.requestHandlers.handleDeleteTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "OPTIONS",
      "/todos/:todoId",
      new OptionsTodoRequestValidator(),
      this.requestHandlers.handleOptionsTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "PUT",
      "/todos/:todoId/status",
      new UpdateTodoStatusRequestValidator(),
      this.requestHandlers.handleUpdateTodoStatusRequest.bind(
        this.requestHandlers,
      ),
    );

    this.route(
      "GET",
      "/todos/:todoId/subtodos",
      new ListSubTodosRequestValidator(),
      this.requestHandlers.handleListSubTodosRequest.bind(this.requestHandlers),
    );

    this.route(
      "POST",
      "/todos/:todoId/subtodos",
      new CreateSubTodoRequestValidator(),
      this.requestHandlers.handleCreateSubTodoRequest.bind(
        this.requestHandlers,
      ),
    );

    this.route(
      "POST",
      "/todos/:todoId/subtodos/query",
      new QuerySubTodoRequestValidator(),
      this.requestHandlers.handleQuerySubTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "PUT",
      "/todos/:todoId/subtodos/:subtodoId",
      new UpdateSubTodoRequestValidator(),
      this.requestHandlers.handleUpdateSubTodoRequest.bind(
        this.requestHandlers,
      ),
    );

    this.route(
      "DELETE",
      "/todos/:todoId/subtodos/:subtodoId",
      new DeleteSubTodoRequestValidator(),
      this.requestHandlers.handleDeleteSubTodoRequest.bind(
        this.requestHandlers,
      ),
    );
  }
}
