/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITaggedHttpResponse } from "@rexeus/typeweaver-core";

export type ITodoStatusTransitionInvalidErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type ITodoStatusTransitionInvalidErrorResponseBody = {
  message: "Todo status transition is conflicting with current status";
  code: "TODO_STATUS_TRANSITION_INVALID_ERROR";
  context: {
    todoId: string;
    currentStatus: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
  };
  actualValues: {
    requestedStatus: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
  };
  expectedValues: {
    allowedStatuses: ("TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED")[];
  };
};

export type ITodoStatusTransitionInvalidErrorResponse = ITaggedHttpResponse<
  "TodoStatusTransitionInvalidError",
  ITodoStatusTransitionInvalidErrorResponseHeader,
  ITodoStatusTransitionInvalidErrorResponseBody
> & {
  readonly statusCode: HttpStatusCode.CONFLICT;
  readonly header: ITodoStatusTransitionInvalidErrorResponseHeader;
  readonly body: ITodoStatusTransitionInvalidErrorResponseBody;
};

export const createTodoStatusTransitionInvalidErrorResponse = (
  input: Omit<ITodoStatusTransitionInvalidErrorResponse, "_tag" | "statusCode">,
): ITodoStatusTransitionInvalidErrorResponse => ({
  _tag: "TodoStatusTransitionInvalidError",
  statusCode: HttpStatusCode.CONFLICT,
  ...input,
});
