/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import {
  HttpMethod,
  TypeweaverRouter,
  type RequestHandler,
  type TypeweaverRouterOptions,
} from "./../lib/server";

import type { IListTodosRequest } from "./ListTodosRequest";
import { ListTodosRequestValidator } from "./ListTodosRequestValidator";
import type { ListTodosResponse } from "./ListTodosResponse";
import { ListTodosResponseValidator } from "./ListTodosResponseValidator";

import type { ICreateTodoRequest } from "./CreateTodoRequest";
import { CreateTodoRequestValidator } from "./CreateTodoRequestValidator";
import type { CreateTodoResponse } from "./CreateTodoResponse";
import { CreateTodoResponseValidator } from "./CreateTodoResponseValidator";

import type { IQueryTodoRequest } from "./QueryTodoRequest";
import { QueryTodoRequestValidator } from "./QueryTodoRequestValidator";
import type { QueryTodoResponse } from "./QueryTodoResponse";
import { QueryTodoResponseValidator } from "./QueryTodoResponseValidator";

import type { IGetTodoRequest } from "./GetTodoRequest";
import { GetTodoRequestValidator } from "./GetTodoRequestValidator";
import type { GetTodoResponse } from "./GetTodoResponse";
import { GetTodoResponseValidator } from "./GetTodoResponseValidator";

import type { IPutTodoRequest } from "./PutTodoRequest";
import { PutTodoRequestValidator } from "./PutTodoRequestValidator";
import type { PutTodoResponse } from "./PutTodoResponse";
import { PutTodoResponseValidator } from "./PutTodoResponseValidator";

import type { IUpdateTodoRequest } from "./UpdateTodoRequest";
import { UpdateTodoRequestValidator } from "./UpdateTodoRequestValidator";
import type { UpdateTodoResponse } from "./UpdateTodoResponse";
import { UpdateTodoResponseValidator } from "./UpdateTodoResponseValidator";

import type { IDeleteTodoRequest } from "./DeleteTodoRequest";
import { DeleteTodoRequestValidator } from "./DeleteTodoRequestValidator";
import type { DeleteTodoResponse } from "./DeleteTodoResponse";
import { DeleteTodoResponseValidator } from "./DeleteTodoResponseValidator";

import type { IOptionsTodoRequest } from "./OptionsTodoRequest";
import { OptionsTodoRequestValidator } from "./OptionsTodoRequestValidator";
import type { OptionsTodoResponse } from "./OptionsTodoResponse";
import { OptionsTodoResponseValidator } from "./OptionsTodoResponseValidator";

import type { IUpdateTodoStatusRequest } from "./UpdateTodoStatusRequest";
import { UpdateTodoStatusRequestValidator } from "./UpdateTodoStatusRequestValidator";
import type { UpdateTodoStatusResponse } from "./UpdateTodoStatusResponse";
import { UpdateTodoStatusResponseValidator } from "./UpdateTodoStatusResponseValidator";

import type { IListSubTodosRequest } from "./ListSubTodosRequest";
import { ListSubTodosRequestValidator } from "./ListSubTodosRequestValidator";
import type { ListSubTodosResponse } from "./ListSubTodosResponse";
import { ListSubTodosResponseValidator } from "./ListSubTodosResponseValidator";

import type { ICreateSubTodoRequest } from "./CreateSubTodoRequest";
import { CreateSubTodoRequestValidator } from "./CreateSubTodoRequestValidator";
import type { CreateSubTodoResponse } from "./CreateSubTodoResponse";
import { CreateSubTodoResponseValidator } from "./CreateSubTodoResponseValidator";

import type { IQuerySubTodoRequest } from "./QuerySubTodoRequest";
import { QuerySubTodoRequestValidator } from "./QuerySubTodoRequestValidator";
import type { QuerySubTodoResponse } from "./QuerySubTodoResponse";
import { QuerySubTodoResponseValidator } from "./QuerySubTodoResponseValidator";

import type { IUpdateSubTodoRequest } from "./UpdateSubTodoRequest";
import { UpdateSubTodoRequestValidator } from "./UpdateSubTodoRequestValidator";
import type { UpdateSubTodoResponse } from "./UpdateSubTodoResponse";
import { UpdateSubTodoResponseValidator } from "./UpdateSubTodoResponseValidator";

import type { IDeleteSubTodoRequest } from "./DeleteSubTodoRequest";
import { DeleteSubTodoRequestValidator } from "./DeleteSubTodoRequestValidator";
import type { DeleteSubTodoResponse } from "./DeleteSubTodoResponse";
import { DeleteSubTodoResponseValidator } from "./DeleteSubTodoResponseValidator";

export type ServerTodoApiHandler<TState extends Record<string, unknown> = Record<string, unknown>> =
  {
    handleListTodosRequest: RequestHandler<IListTodosRequest, ListTodosResponse, TState>;

    handleCreateTodoRequest: RequestHandler<ICreateTodoRequest, CreateTodoResponse, TState>;

    handleQueryTodoRequest: RequestHandler<IQueryTodoRequest, QueryTodoResponse, TState>;

    handleGetTodoRequest: RequestHandler<IGetTodoRequest, GetTodoResponse, TState>;

    handlePutTodoRequest: RequestHandler<IPutTodoRequest, PutTodoResponse, TState>;

    handleUpdateTodoRequest: RequestHandler<IUpdateTodoRequest, UpdateTodoResponse, TState>;

    handleDeleteTodoRequest: RequestHandler<IDeleteTodoRequest, DeleteTodoResponse, TState>;

    handleOptionsTodoRequest: RequestHandler<IOptionsTodoRequest, OptionsTodoResponse, TState>;

    handleUpdateTodoStatusRequest: RequestHandler<
      IUpdateTodoStatusRequest,
      UpdateTodoStatusResponse,
      TState
    >;

    handleListSubTodosRequest: RequestHandler<IListSubTodosRequest, ListSubTodosResponse, TState>;

    handleCreateSubTodoRequest: RequestHandler<
      ICreateSubTodoRequest,
      CreateSubTodoResponse,
      TState
    >;

    handleQuerySubTodoRequest: RequestHandler<IQuerySubTodoRequest, QuerySubTodoResponse, TState>;

    handleUpdateSubTodoRequest: RequestHandler<
      IUpdateSubTodoRequest,
      UpdateSubTodoResponse,
      TState
    >;

    handleDeleteSubTodoRequest: RequestHandler<
      IDeleteSubTodoRequest,
      DeleteSubTodoResponse,
      TState
    >;
  };

export class TodoRouter<
  TState extends Record<string, unknown> = Record<string, unknown>,
> extends TypeweaverRouter<ServerTodoApiHandler<TState>> {
  public constructor(options: TypeweaverRouterOptions<ServerTodoApiHandler<TState>>) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.route(
      "ListTodos",
      HttpMethod.GET,
      "/todos",
      new ListTodosRequestValidator(),
      new ListTodosResponseValidator(),
      this.requestHandlers.handleListTodosRequest.bind(this.requestHandlers),
    );

    this.route(
      "CreateTodo",
      HttpMethod.POST,
      "/todos",
      new CreateTodoRequestValidator(),
      new CreateTodoResponseValidator(),
      this.requestHandlers.handleCreateTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "QueryTodo",
      HttpMethod.POST,
      "/todos/query",
      new QueryTodoRequestValidator(),
      new QueryTodoResponseValidator(),
      this.requestHandlers.handleQueryTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "GetTodo",
      HttpMethod.GET,
      "/todos/:todoId",
      new GetTodoRequestValidator(),
      new GetTodoResponseValidator(),
      this.requestHandlers.handleGetTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "PutTodo",
      HttpMethod.PUT,
      "/todos/:todoId",
      new PutTodoRequestValidator(),
      new PutTodoResponseValidator(),
      this.requestHandlers.handlePutTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "UpdateTodo",
      HttpMethod.PATCH,
      "/todos/:todoId",
      new UpdateTodoRequestValidator(),
      new UpdateTodoResponseValidator(),
      this.requestHandlers.handleUpdateTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "DeleteTodo",
      HttpMethod.DELETE,
      "/todos/:todoId",
      new DeleteTodoRequestValidator(),
      new DeleteTodoResponseValidator(),
      this.requestHandlers.handleDeleteTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "OptionsTodo",
      HttpMethod.OPTIONS,
      "/todos/:todoId",
      new OptionsTodoRequestValidator(),
      new OptionsTodoResponseValidator(),
      this.requestHandlers.handleOptionsTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "UpdateTodoStatus",
      HttpMethod.PUT,
      "/todos/:todoId/status",
      new UpdateTodoStatusRequestValidator(),
      new UpdateTodoStatusResponseValidator(),
      this.requestHandlers.handleUpdateTodoStatusRequest.bind(this.requestHandlers),
    );

    this.route(
      "ListSubTodos",
      HttpMethod.GET,
      "/todos/:todoId/subtodos",
      new ListSubTodosRequestValidator(),
      new ListSubTodosResponseValidator(),
      this.requestHandlers.handleListSubTodosRequest.bind(this.requestHandlers),
    );

    this.route(
      "CreateSubTodo",
      HttpMethod.POST,
      "/todos/:todoId/subtodos",
      new CreateSubTodoRequestValidator(),
      new CreateSubTodoResponseValidator(),
      this.requestHandlers.handleCreateSubTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "QuerySubTodo",
      HttpMethod.POST,
      "/todos/:todoId/subtodos/query",
      new QuerySubTodoRequestValidator(),
      new QuerySubTodoResponseValidator(),
      this.requestHandlers.handleQuerySubTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "UpdateSubTodo",
      HttpMethod.PUT,
      "/todos/:todoId/subtodos/:subtodoId",
      new UpdateSubTodoRequestValidator(),
      new UpdateSubTodoResponseValidator(),
      this.requestHandlers.handleUpdateSubTodoRequest.bind(this.requestHandlers),
    );

    this.route(
      "DeleteSubTodo",
      HttpMethod.DELETE,
      "/todos/:todoId/subtodos/:subtodoId",
      new DeleteSubTodoRequestValidator(),
      new DeleteSubTodoResponseValidator(),
      this.requestHandlers.handleDeleteSubTodoRequest.bind(this.requestHandlers),
    );
  }
}
