/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { ApiClient, type ApiClientProps } from "../lib/clients";

import { CreateSubTodoRequestCommand } from "./CreateSubTodoRequestCommand";
import type { CreateSubTodoResponse } from "./CreateSubTodoResponse";

import { CreateTodoRequestCommand } from "./CreateTodoRequestCommand";
import type { CreateTodoResponse } from "./CreateTodoResponse";

import { DeleteSubTodoRequestCommand } from "./DeleteSubTodoRequestCommand";
import type { DeleteSubTodoResponse } from "./DeleteSubTodoResponse";

import { DeleteTodoRequestCommand } from "./DeleteTodoRequestCommand";
import type { DeleteTodoResponse } from "./DeleteTodoResponse";

import { GetTodoRequestCommand } from "./GetTodoRequestCommand";
import type { GetTodoResponse } from "./GetTodoResponse";

import { HeadTodoRequestCommand } from "./HeadTodoRequestCommand";
import type { HeadTodoResponse } from "./HeadTodoResponse";

import { ListSubTodosRequestCommand } from "./ListSubTodosRequestCommand";
import type { ListSubTodosResponse } from "./ListSubTodosResponse";

import { ListTodosRequestCommand } from "./ListTodosRequestCommand";
import type { ListTodosResponse } from "./ListTodosResponse";

import { OptionsTodoRequestCommand } from "./OptionsTodoRequestCommand";
import type { OptionsTodoResponse } from "./OptionsTodoResponse";

import { PutTodoRequestCommand } from "./PutTodoRequestCommand";
import type { PutTodoResponse } from "./PutTodoResponse";

import { QuerySubTodoRequestCommand } from "./QuerySubTodoRequestCommand";
import type { QuerySubTodoResponse } from "./QuerySubTodoResponse";

import { QueryTodoRequestCommand } from "./QueryTodoRequestCommand";
import type { QueryTodoResponse } from "./QueryTodoResponse";

import { UpdateSubTodoRequestCommand } from "./UpdateSubTodoRequestCommand";
import type { UpdateSubTodoResponse } from "./UpdateSubTodoResponse";

import { UpdateTodoRequestCommand } from "./UpdateTodoRequestCommand";
import type { UpdateTodoResponse } from "./UpdateTodoResponse";

import { UpdateTodoStatusRequestCommand } from "./UpdateTodoStatusRequestCommand";
import type { UpdateTodoStatusResponse } from "./UpdateTodoStatusResponse";

export type TodoRequestCommands =
  | CreateSubTodoRequestCommand
  | CreateTodoRequestCommand
  | DeleteSubTodoRequestCommand
  | DeleteTodoRequestCommand
  | GetTodoRequestCommand
  | HeadTodoRequestCommand
  | ListSubTodosRequestCommand
  | ListTodosRequestCommand
  | OptionsTodoRequestCommand
  | PutTodoRequestCommand
  | QuerySubTodoRequestCommand
  | QueryTodoRequestCommand
  | UpdateSubTodoRequestCommand
  | UpdateTodoRequestCommand
  | UpdateTodoStatusRequestCommand;

export type TodoResponses =
  | CreateSubTodoResponse
  | CreateTodoResponse
  | DeleteSubTodoResponse
  | DeleteTodoResponse
  | GetTodoResponse
  | HeadTodoResponse
  | ListSubTodosResponse
  | ListTodosResponse
  | OptionsTodoResponse
  | PutTodoResponse
  | QuerySubTodoResponse
  | QueryTodoResponse
  | UpdateSubTodoResponse
  | UpdateTodoResponse
  | UpdateTodoStatusResponse;

export class TodoClient extends ApiClient {
  public constructor(props: ApiClientProps) {
    super(props);
  }

  public async send(command: CreateSubTodoRequestCommand): Promise<CreateSubTodoResponse>;

  public async send(command: CreateTodoRequestCommand): Promise<CreateTodoResponse>;

  public async send(command: DeleteSubTodoRequestCommand): Promise<DeleteSubTodoResponse>;

  public async send(command: DeleteTodoRequestCommand): Promise<DeleteTodoResponse>;

  public async send(command: GetTodoRequestCommand): Promise<GetTodoResponse>;

  public async send(command: HeadTodoRequestCommand): Promise<HeadTodoResponse>;

  public async send(command: ListSubTodosRequestCommand): Promise<ListSubTodosResponse>;

  public async send(command: ListTodosRequestCommand): Promise<ListTodosResponse>;

  public async send(command: OptionsTodoRequestCommand): Promise<OptionsTodoResponse>;

  public async send(command: PutTodoRequestCommand): Promise<PutTodoResponse>;

  public async send(command: QuerySubTodoRequestCommand): Promise<QuerySubTodoResponse>;

  public async send(command: QueryTodoRequestCommand): Promise<QueryTodoResponse>;

  public async send(command: UpdateSubTodoRequestCommand): Promise<UpdateSubTodoResponse>;

  public async send(command: UpdateTodoRequestCommand): Promise<UpdateTodoResponse>;

  public async send(command: UpdateTodoStatusRequestCommand): Promise<UpdateTodoStatusResponse>;

  public async send(command: TodoRequestCommands): Promise<TodoResponses> {
    const response = await this.execute(command);
    return command.processResponse(response);
  }
}
