/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import definition from "../definition/todo/mutations/UpdateTodoStatusDefinition";
import {
  type IHttpResponse,
  type SafeResponseValidationResult,
  ResponseValidationError,
} from "@rexeus/typeweaver-core";
import { ResponseValidator } from "../lib/types";
import {
  type UpdateTodoStatusResponse,
  type IUpdateTodoStatusSuccessResponse,
} from "./UpdateTodoStatusResponse";

import type { ITodoNotFoundErrorResponse } from "./TodoNotFoundErrorResponse";

import type { ITodoStatusTransitionInvalidErrorResponse } from "./TodoStatusTransitionInvalidErrorResponse";

import type { ITodoNotChangeableErrorResponse } from "./TodoNotChangeableErrorResponse";

import type { IForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../shared/ValidationErrorResponse";

export class UpdateTodoStatusResponseValidator extends ResponseValidator {
  public safeValidate(
    response: IHttpResponse,
  ): SafeResponseValidationResult<UpdateTodoStatusResponse> {
    const result = this.validateAgainstDefinedResponses(response);

    if (!result.isValid && !result.error.hasResponseIssues()) {
      result.error.addStatusCodeIssue([200, 400, 401, 403, 404, 409, 415, 429, 500]);
    }

    return result;
  }

  public validate(response: IHttpResponse): UpdateTodoStatusResponse {
    const result = this.safeValidate(response);

    if (!result.isValid) {
      throw result.error;
    }

    return result.data;
  }

  private validateAgainstDefinedResponses(
    response: IHttpResponse,
  ): SafeResponseValidationResult<UpdateTodoStatusResponse> {
    const error = new ResponseValidationError(response.statusCode);

    if (response.statusCode === 200) {
      const validateUpdateTodoStatusSuccessResponseResult =
        this.validateUpdateTodoStatusSuccessResponse(response, error);
      if (validateUpdateTodoStatusSuccessResponseResult.isValid) {
        return validateUpdateTodoStatusSuccessResponseResult;
      }
    }

    if (response.statusCode === 404) {
      const validateTodoNotFoundErrorResponseResult = this.validateTodoNotFoundErrorResponse(
        response,
        error,
      );
      if (validateTodoNotFoundErrorResponseResult.isValid) {
        return validateTodoNotFoundErrorResponseResult;
      }
    }

    if (response.statusCode === 409) {
      const validateTodoStatusTransitionInvalidErrorResponseResult =
        this.validateTodoStatusTransitionInvalidErrorResponse(response, error);
      if (validateTodoStatusTransitionInvalidErrorResponseResult.isValid) {
        return validateTodoStatusTransitionInvalidErrorResponseResult;
      }

      const validateTodoNotChangeableErrorResponseResult =
        this.validateTodoNotChangeableErrorResponse(response, error);
      if (validateTodoNotChangeableErrorResponseResult.isValid) {
        return validateTodoNotChangeableErrorResponseResult;
      }
    }

    if (response.statusCode === 403) {
      const validateForbiddenErrorResponseResult = this.validateForbiddenErrorResponse(
        response,
        error,
      );
      if (validateForbiddenErrorResponseResult.isValid) {
        return validateForbiddenErrorResponseResult;
      }
    }

    if (response.statusCode === 500) {
      const validateInternalServerErrorResponseResult = this.validateInternalServerErrorResponse(
        response,
        error,
      );
      if (validateInternalServerErrorResponseResult.isValid) {
        return validateInternalServerErrorResponseResult;
      }
    }

    if (response.statusCode === 429) {
      const validateTooManyRequestsErrorResponseResult = this.validateTooManyRequestsErrorResponse(
        response,
        error,
      );
      if (validateTooManyRequestsErrorResponseResult.isValid) {
        return validateTooManyRequestsErrorResponseResult;
      }
    }

    if (response.statusCode === 401) {
      const validateUnauthorizedErrorResponseResult = this.validateUnauthorizedErrorResponse(
        response,
        error,
      );
      if (validateUnauthorizedErrorResponseResult.isValid) {
        return validateUnauthorizedErrorResponseResult;
      }
    }

    if (response.statusCode === 415) {
      const validateUnsupportedMediaTypeErrorResponseResult =
        this.validateUnsupportedMediaTypeErrorResponse(response, error);
      if (validateUnsupportedMediaTypeErrorResponseResult.isValid) {
        return validateUnsupportedMediaTypeErrorResponseResult;
      }
    }

    if (response.statusCode === 400) {
      const validateValidationErrorResponseResult = this.validateValidationErrorResponse(
        response,
        error,
      );
      if (validateValidationErrorResponseResult.isValid) {
        return validateValidationErrorResponseResult;
      }
    }

    return {
      isValid: false,
      error,
    };
  }

  private validateUpdateTodoStatusSuccessResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<IUpdateTodoStatusSuccessResponse> {
    return this.validateResponseType<IUpdateTodoStatusSuccessResponse>(
      "UpdateTodoStatusSuccess",
      definition.responses[0] && "header" in definition.responses[0]
        ? definition.responses[0]!.header
        : undefined,
      definition.responses[0] && "body" in definition.responses[0]
        ? definition.responses[0]!.body
        : undefined,
    )(response, error);
  }

  private validateTodoNotFoundErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<ITodoNotFoundErrorResponse> {
    return this.validateResponseType<ITodoNotFoundErrorResponse>(
      "TodoNotFoundError",
      definition.responses[1] && "header" in definition.responses[1]
        ? definition.responses[1]!.header
        : undefined,
      definition.responses[1] && "body" in definition.responses[1]
        ? definition.responses[1]!.body
        : undefined,
    )(response, error);
  }

  private validateTodoStatusTransitionInvalidErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<ITodoStatusTransitionInvalidErrorResponse> {
    return this.validateResponseType<ITodoStatusTransitionInvalidErrorResponse>(
      "TodoStatusTransitionInvalidError",
      definition.responses[2] && "header" in definition.responses[2]
        ? definition.responses[2]!.header
        : undefined,
      definition.responses[2] && "body" in definition.responses[2]
        ? definition.responses[2]!.body
        : undefined,
    )(response, error);
  }

  private validateTodoNotChangeableErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<ITodoNotChangeableErrorResponse> {
    return this.validateResponseType<ITodoNotChangeableErrorResponse>(
      "TodoNotChangeableError",
      definition.responses[3] && "header" in definition.responses[3]
        ? definition.responses[3]!.header
        : undefined,
      definition.responses[3] && "body" in definition.responses[3]
        ? definition.responses[3]!.body
        : undefined,
    )(response, error);
  }

  private validateForbiddenErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<IForbiddenErrorResponse> {
    return this.validateResponseType<IForbiddenErrorResponse>(
      "ForbiddenError",
      definition.responses[4] && "header" in definition.responses[4]
        ? definition.responses[4]!.header
        : undefined,
      definition.responses[4] && "body" in definition.responses[4]
        ? definition.responses[4]!.body
        : undefined,
    )(response, error);
  }

  private validateInternalServerErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<IInternalServerErrorResponse> {
    return this.validateResponseType<IInternalServerErrorResponse>(
      "InternalServerError",
      definition.responses[5] && "header" in definition.responses[5]
        ? definition.responses[5]!.header
        : undefined,
      definition.responses[5] && "body" in definition.responses[5]
        ? definition.responses[5]!.body
        : undefined,
    )(response, error);
  }

  private validateTooManyRequestsErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<ITooManyRequestsErrorResponse> {
    return this.validateResponseType<ITooManyRequestsErrorResponse>(
      "TooManyRequestsError",
      definition.responses[6] && "header" in definition.responses[6]
        ? definition.responses[6]!.header
        : undefined,
      definition.responses[6] && "body" in definition.responses[6]
        ? definition.responses[6]!.body
        : undefined,
    )(response, error);
  }

  private validateUnauthorizedErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<IUnauthorizedErrorResponse> {
    return this.validateResponseType<IUnauthorizedErrorResponse>(
      "UnauthorizedError",
      definition.responses[7] && "header" in definition.responses[7]
        ? definition.responses[7]!.header
        : undefined,
      definition.responses[7] && "body" in definition.responses[7]
        ? definition.responses[7]!.body
        : undefined,
    )(response, error);
  }

  private validateUnsupportedMediaTypeErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<IUnsupportedMediaTypeErrorResponse> {
    return this.validateResponseType<IUnsupportedMediaTypeErrorResponse>(
      "UnsupportedMediaTypeError",
      definition.responses[8] && "header" in definition.responses[8]
        ? definition.responses[8]!.header
        : undefined,
      definition.responses[8] && "body" in definition.responses[8]
        ? definition.responses[8]!.body
        : undefined,
    )(response, error);
  }

  private validateValidationErrorResponse(
    response: IHttpResponse,
    error: ResponseValidationError,
  ): SafeResponseValidationResult<IValidationErrorResponse> {
    return this.validateResponseType<IValidationErrorResponse>(
      "ValidationError",
      definition.responses[9] && "header" in definition.responses[9]
        ? definition.responses[9]!.header
        : undefined,
      definition.responses[9] && "body" in definition.responses[9]
        ? definition.responses[9]!.body
        : undefined,
    )(response, error);
  }
}
