/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients/index.js";
import { getOperationDefinition } from "../lib/types/index.js";
import { UpdateTodoResponseValidator } from "./UpdateTodoResponseValidator.js";
import type {
  IUpdateTodoRequest,
  IUpdateTodoRequestHeader,
  IUpdateTodoRequestParam,
  IUpdateTodoRequestBody,
} from "./UpdateTodoRequest.js";
import type { UpdateTodoResponse } from "./UpdateTodoResponse.js";

const definition = getOperationDefinition(spec, "todo", "UpdateTodo");
const responseValidator = new UpdateTodoResponseValidator();

const defaultHeader = {
  Accept: "application/json",

  "Content-Type": "application/json",
} as const;

export type UpdateTodoRequestCommandInput = Omit<
  IUpdateTodoRequest,
  "method" | "path" | "header"
> & {
  readonly header: Omit<IUpdateTodoRequestHeader, "Accept" | "Content-Type"> &
    Partial<Pick<IUpdateTodoRequestHeader, "Accept" | "Content-Type">>;
};

/**
 * Update todo
 */
export class UpdateTodoRequestCommand extends RequestCommand implements IUpdateTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.PATCH;
  public override readonly path = definition.path;

  public override readonly header: IUpdateTodoRequestHeader;
  public override readonly param: IUpdateTodoRequestParam;
  declare public readonly query: undefined;
  public override readonly body: IUpdateTodoRequestBody;

  public constructor(input: UpdateTodoRequestCommandInput) {
    super();

    this.header = { ...input.header, ...defaultHeader };

    this.param = input.param;

    this.body = input.body;
  }

  public processResponse(response: IHttpResponse): UpdateTodoResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
