/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import spec from "../spec/spec";
import {
  getOperationDefinition,
  getResponseDefinition,
  type ResponseEntry,
  ResponseValidator,
} from "../lib/types";
import type { UpdateTodoResponse } from "./UpdateTodoResponse";

const definition = getOperationDefinition(spec, "todo", "UpdateTodo");

const updateTodoSuccessDefinition = getResponseDefinition(
  definition.responses,
  "UpdateTodoSuccess",
);

const todoNotFoundErrorDefinition = getResponseDefinition(
  definition.responses,
  "TodoNotFoundError",
);

const todoNotChangeableErrorDefinition = getResponseDefinition(
  definition.responses,
  "TodoNotChangeableError",
);

const forbiddenErrorDefinition = getResponseDefinition(definition.responses, "ForbiddenError");

const internalServerErrorDefinition = getResponseDefinition(
  definition.responses,
  "InternalServerError",
);

const tooManyRequestsErrorDefinition = getResponseDefinition(
  definition.responses,
  "TooManyRequestsError",
);

const unauthorizedErrorDefinition = getResponseDefinition(
  definition.responses,
  "UnauthorizedError",
);

const unsupportedMediaTypeErrorDefinition = getResponseDefinition(
  definition.responses,
  "UnsupportedMediaTypeError",
);

const validationErrorDefinition = getResponseDefinition(definition.responses, "ValidationError");

export class UpdateTodoResponseValidator extends ResponseValidator<UpdateTodoResponse> {
  protected override readonly expectedStatusCodes = [200, 400, 401, 403, 404, 409, 415, 429, 500];

  protected override readonly responseEntries: readonly ResponseEntry[] = [
    {
      name: "UpdateTodoSuccess",
      statusCode: 200,
      headerSchema: updateTodoSuccessDefinition.header,
      bodySchema: updateTodoSuccessDefinition.body,
    },

    {
      name: "TodoNotFoundError",
      statusCode: 404,
      headerSchema: todoNotFoundErrorDefinition.header,
      bodySchema: todoNotFoundErrorDefinition.body,
    },

    {
      name: "TodoNotChangeableError",
      statusCode: 409,
      headerSchema: todoNotChangeableErrorDefinition.header,
      bodySchema: todoNotChangeableErrorDefinition.body,
    },

    {
      name: "ForbiddenError",
      statusCode: 403,
      headerSchema: forbiddenErrorDefinition.header,
      bodySchema: forbiddenErrorDefinition.body,
    },

    {
      name: "InternalServerError",
      statusCode: 500,
      headerSchema: internalServerErrorDefinition.header,
      bodySchema: internalServerErrorDefinition.body,
    },

    {
      name: "TooManyRequestsError",
      statusCode: 429,
      headerSchema: tooManyRequestsErrorDefinition.header,
      bodySchema: tooManyRequestsErrorDefinition.body,
    },

    {
      name: "UnauthorizedError",
      statusCode: 401,
      headerSchema: unauthorizedErrorDefinition.header,
      bodySchema: unauthorizedErrorDefinition.body,
    },

    {
      name: "UnsupportedMediaTypeError",
      statusCode: 415,
      headerSchema: unsupportedMediaTypeErrorDefinition.header,
      bodySchema: unsupportedMediaTypeErrorDefinition.body,
    },

    {
      name: "ValidationError",
      statusCode: 400,
      headerSchema: validationErrorDefinition.header,
      bodySchema: validationErrorDefinition.body,
    },
  ];
}
