/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients/index.js";
import { getOperationDefinition } from "../lib/types/index.js";
import { UpdateTodoStatusResponseValidator } from "./UpdateTodoStatusResponseValidator.js";
import type {
  IUpdateTodoStatusRequest,
  IUpdateTodoStatusRequestHeader,
  IUpdateTodoStatusRequestParam,
  IUpdateTodoStatusRequestBody,
} from "./UpdateTodoStatusRequest.js";
import type { UpdateTodoStatusResponse } from "./UpdateTodoStatusResponse.js";

const definition = getOperationDefinition(spec, "todo", "UpdateTodoStatus");
const responseValidator = new UpdateTodoStatusResponseValidator();

const defaultHeader = {
  Accept: "application/json",

  "Content-Type": "application/json",
} as const;

export type UpdateTodoStatusRequestCommandInput = Omit<
  IUpdateTodoStatusRequest,
  "method" | "path" | "header"
> & {
  readonly header: Omit<IUpdateTodoStatusRequestHeader, "Accept" | "Content-Type"> &
    Partial<Pick<IUpdateTodoStatusRequestHeader, "Accept" | "Content-Type">>;
};

/**
 * Update todo status
 */
export class UpdateTodoStatusRequestCommand
  extends RequestCommand
  implements IUpdateTodoStatusRequest
{
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.PUT;
  public override readonly path = definition.path;

  public override readonly header: IUpdateTodoStatusRequestHeader;
  public override readonly param: IUpdateTodoStatusRequestParam;
  declare public readonly query: undefined;
  public override readonly body: IUpdateTodoStatusRequestBody;

  public constructor(input: UpdateTodoStatusRequestCommandInput) {
    super();

    this.header = { ...defaultHeader, ...input.header };

    this.param = input.param;

    this.body = input.body;
  }

  public processResponse(response: IHttpResponse): UpdateTodoStatusResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
