/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import spec from "../spec/spec";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients";
import { UpdateTodoResponseValidator } from "./UpdateTodoResponseValidator";
import type {
  IUpdateTodoRequest,
  IUpdateTodoRequestHeader,
  IUpdateTodoRequestParam,
  IUpdateTodoRequestBody,
} from "./UpdateTodoRequest";
import type { UpdateTodoResponse } from "./UpdateTodoResponse";

const definition = spec.resources["todo"]!.operations.find(
  (operation) => operation.operationId === "UpdateTodo",
)!;
const responseValidator = new UpdateTodoResponseValidator();

export class UpdateTodoRequestCommand extends RequestCommand implements IUpdateTodoRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.PATCH;
  public override readonly path = definition.path;

  public override readonly header: IUpdateTodoRequestHeader;
  public override readonly param: IUpdateTodoRequestParam;
  declare public readonly query: undefined;
  public override readonly body: IUpdateTodoRequestBody;

  public constructor(input: Omit<IUpdateTodoRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.param = input.param;

    this.body = input.body;
  }

  public processResponse(response: IHttpResponse): UpdateTodoResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
