/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import spec from "../spec/spec";
import { type ResponseEntry, ResponseValidator } from "../lib/types";
import type { UpdateSubTodoResponse } from "./UpdateSubTodoResponse";

const definition = spec.resources["todo"]!.operations.find(
  (operation) => operation.operationId === "UpdateSubTodo",
)!;
const responseDefinitions = new Map(
  definition.responses.map((response) => [response.name, response] as const),
);

export class UpdateSubTodoResponseValidator extends ResponseValidator<UpdateSubTodoResponse> {
  protected override readonly expectedStatusCodes = [200, 400, 401, 403, 404, 409, 415, 429, 500];

  protected override readonly responseEntries: readonly ResponseEntry[] = [
    {
      name: "UpdateSubTodoSuccess",
      statusCode: 200,
      headerSchema: responseDefinitions.get("UpdateSubTodoSuccess")?.header,
      bodySchema: responseDefinitions.get("UpdateSubTodoSuccess")?.body,
    },

    {
      name: "SubTodoNotFoundError",
      statusCode: 404,
      headerSchema: responseDefinitions.get("SubTodoNotFoundError")?.header,
      bodySchema: responseDefinitions.get("SubTodoNotFoundError")?.body,
    },

    {
      name: "SubTodoNotChangeableError",
      statusCode: 409,
      headerSchema: responseDefinitions.get("SubTodoNotChangeableError")?.header,
      bodySchema: responseDefinitions.get("SubTodoNotChangeableError")?.body,
    },

    {
      name: "SubTodoStatusTransitionInvalidError",
      statusCode: 409,
      headerSchema: responseDefinitions.get("SubTodoStatusTransitionInvalidError")?.header,
      bodySchema: responseDefinitions.get("SubTodoStatusTransitionInvalidError")?.body,
    },

    {
      name: "TodoNotFoundError",
      statusCode: 404,
      headerSchema: responseDefinitions.get("TodoNotFoundError")?.header,
      bodySchema: responseDefinitions.get("TodoNotFoundError")?.body,
    },

    {
      name: "ForbiddenError",
      statusCode: 403,
      headerSchema: responseDefinitions.get("ForbiddenError")?.header,
      bodySchema: responseDefinitions.get("ForbiddenError")?.body,
    },

    {
      name: "InternalServerError",
      statusCode: 500,
      headerSchema: responseDefinitions.get("InternalServerError")?.header,
      bodySchema: responseDefinitions.get("InternalServerError")?.body,
    },

    {
      name: "TooManyRequestsError",
      statusCode: 429,
      headerSchema: responseDefinitions.get("TooManyRequestsError")?.header,
      bodySchema: responseDefinitions.get("TooManyRequestsError")?.body,
    },

    {
      name: "UnauthorizedError",
      statusCode: 401,
      headerSchema: responseDefinitions.get("UnauthorizedError")?.header,
      bodySchema: responseDefinitions.get("UnauthorizedError")?.body,
    },

    {
      name: "UnsupportedMediaTypeError",
      statusCode: 415,
      headerSchema: responseDefinitions.get("UnsupportedMediaTypeError")?.header,
      bodySchema: responseDefinitions.get("UnsupportedMediaTypeError")?.body,
    },

    {
      name: "ValidationError",
      statusCode: 400,
      headerSchema: responseDefinitions.get("ValidationError")?.header,
      bodySchema: responseDefinitions.get("ValidationError")?.body,
    },
  ];
}
