/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../spec/spec.js";
import {
  HttpMethod,
  type IRawHttpRequest,
  type SafeRequestValidationResult,
  RequestValidationError,
} from "@rexeus/typeweaver-core";
import { getOperationDefinition, RequestValidator } from "../lib/types/index.js";
import type {
  IUpdateTodoRequest,
  IUpdateTodoRequestBody,
  IUpdateTodoRequestHeader,
  IUpdateTodoRequestParam,
} from "./UpdateTodoRequest.js";

const definition = getOperationDefinition(spec, "todo", "UpdateTodo");

export class UpdateTodoRequestValidator extends RequestValidator<IUpdateTodoRequest> {
  public safeValidate(request: IRawHttpRequest): SafeRequestValidationResult<IUpdateTodoRequest> {
    const error = new RequestValidationError();

    const bodySchema = this.requireRequestSchema(definition.request.body, "body");
    const bodyResult = this.safeParseAs<IUpdateTodoRequestBody>(bodySchema, request.body);
    if (!bodyResult.success) {
      error.addBodyIssues(bodyResult.error.issues);
    }

    const headerSchema = this.requireRequestSchema(definition.request.header, "header");
    const coercedHeader = this.coerceHeaderToSchema(request.header, headerSchema);
    const headerMultiplicityIssues = this.findMultiplicityIssues(
      request.header,
      headerSchema,
      false,
    );
    if (headerMultiplicityIssues.length > 0) {
      error.addHeaderIssues(headerMultiplicityIssues);
    }
    const headerResult = this.safeParseAs<IUpdateTodoRequestHeader>(headerSchema, coercedHeader);
    if (!headerResult.success) {
      error.addHeaderIssues(headerResult.error.issues);
    }

    const paramSchema = this.requireRequestSchema(definition.request.param, "param");
    const paramResult = this.safeParseAs<IUpdateTodoRequestParam>(paramSchema, request.param);
    if (!paramResult.success) {
      error.addPathParamIssues(paramResult.error.issues);
    }

    if (error.hasIssues() || !bodyResult.success || !headerResult.success || !paramResult.success) {
      return {
        isValid: false,
        error,
      };
    }

    return {
      isValid: true,
      data: {
        method: HttpMethod.PATCH,
        path: request.path,
        body: bodyResult.data,
        header: headerResult.data,
        param: paramResult.data,
      },
    };
  }

  public validate(request: IRawHttpRequest): IUpdateTodoRequest {
    const result = this.safeValidate(request);

    if (!result.isValid) {
      throw result.error;
    }

    return result.data;
  }
}
