/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod } from "@rexeus/typeweaver-core";
import type { UpdateTodoStatusResponse } from "./UpdateTodoStatusResponse";

import type { IForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../shared/ValidationErrorResponse";

import type { ITodoNotFoundErrorResponse } from "./TodoNotFoundErrorResponse";

import type { ITodoStatusTransitionInvalidErrorResponse } from "./TodoStatusTransitionInvalidErrorResponse";

import type { ITodoNotChangeableErrorResponse } from "./TodoNotChangeableErrorResponse";

export type IUpdateTodoStatusRequestHeader = {
  "Content-Type": "application/json";
  Accept: "application/json";
  Authorization: string;
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IUpdateTodoStatusRequestParam = {
  todoId: string;
};

export type IUpdateTodoStatusRequestBody = {
  value: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
};

export type IUpdateTodoStatusRequest = {
  path: string;
  method: HttpMethod.PUT;
  header: IUpdateTodoStatusRequestHeader;
  param: IUpdateTodoStatusRequestParam;

  body: IUpdateTodoStatusRequestBody;
};

export type SuccessfulUpdateTodoStatusResponse = Exclude<
  UpdateTodoStatusResponse,
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse
  | ITodoNotFoundErrorResponse
  | ITodoStatusTransitionInvalidErrorResponse
  | ITodoNotChangeableErrorResponse
>;
