/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type IConflictErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IConflictErrorResponseBody = {
  message: "Conflicted request";
  code: "CONFLICT_ERROR";
};

export type IConflictErrorResponse = ITypedHttpResponse<
  "ConflictError",
  IConflictErrorResponseHeader,
  IConflictErrorResponseBody
> & {
  readonly statusCode: HttpStatusCode.CONFLICT;
  readonly header: IConflictErrorResponseHeader;
  readonly body: IConflictErrorResponseBody;
};

export const createConflictErrorResponse = (
  input: Omit<IConflictErrorResponse, "type" | "statusCode">,
): IConflictErrorResponse => ({
  type: "ConflictError",
  statusCode: HttpStatusCode.CONFLICT,
  ...input,
});
