/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpResponse, HttpStatusCode } from "@rexeus/typeweaver-core";

export type IForbiddenErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IForbiddenErrorResponseBody = {
  message: "Forbidden request";
  code: "FORBIDDEN_ERROR";
};

export type IForbiddenErrorResponse = {
  statusCode: HttpStatusCode.FORBIDDEN;
  header: IForbiddenErrorResponseHeader;
  body: IForbiddenErrorResponseBody;
};

export class ForbiddenErrorResponse
  extends HttpResponse<IForbiddenErrorResponseHeader, IForbiddenErrorResponseBody>
  implements IForbiddenErrorResponse
{
  public override readonly statusCode = HttpStatusCode.FORBIDDEN;

  public constructor(response: Omit<IForbiddenErrorResponse, "statusCode">) {
    super(HttpStatusCode.FORBIDDEN, response.header, response.body);
  }
}
