/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type IForbiddenErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IForbiddenErrorResponseBody = {
  message: "Forbidden request";
  code: "FORBIDDEN_ERROR";
};

export type IForbiddenErrorResponse = ITypedHttpResponse<
  "ForbiddenError",
  HttpStatusCode.FORBIDDEN,
  IForbiddenErrorResponseHeader,
  IForbiddenErrorResponseBody
>;

export const createForbiddenErrorResponse = (
  input: Omit<IForbiddenErrorResponse, "type" | "statusCode">,
): IForbiddenErrorResponse => ({
  ...input,
  type: "ForbiddenError",
  statusCode: HttpStatusCode.FORBIDDEN,
});
