/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITaggedHttpResponse } from "@rexeus/typeweaver-core";

export type IInternalServerErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IInternalServerErrorResponseBody = {
  message: "Internal server error occurred";
  code: "INTERNAL_SERVER_ERROR";
};

export type IInternalServerErrorResponse = ITaggedHttpResponse<
  "InternalServerError",
  IInternalServerErrorResponseHeader,
  IInternalServerErrorResponseBody
> & {
  readonly statusCode: HttpStatusCode.INTERNAL_SERVER_ERROR;
  readonly header: IInternalServerErrorResponseHeader;
  readonly body: IInternalServerErrorResponseBody;
};

export const createInternalServerErrorResponse = (
  input: Omit<IInternalServerErrorResponse, "_tag" | "statusCode">,
): IInternalServerErrorResponse => ({
  _tag: "InternalServerError",
  statusCode: HttpStatusCode.INTERNAL_SERVER_ERROR,
  ...input,
});
