/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { IConflictErrorResponse, ConflictErrorResponse } from "./ConflictErrorResponse";

import type { IForbiddenErrorResponse, ForbiddenErrorResponse } from "./ForbiddenErrorResponse";

import type {
  IInternalServerErrorResponse,
  InternalServerErrorResponse,
} from "./InternalServerErrorResponse";

import type { INotFoundErrorResponse, NotFoundErrorResponse } from "./NotFoundErrorResponse";

import type {
  ITooManyRequestsErrorResponse,
  TooManyRequestsErrorResponse,
} from "./TooManyRequestsErrorResponse";

import type {
  IUnauthorizedErrorResponse,
  UnauthorizedErrorResponse,
} from "./UnauthorizedErrorResponse";

import type {
  IUnprocessableEntityErrorResponse,
  UnprocessableEntityErrorResponse,
} from "./UnprocessableEntityErrorResponse";

import type {
  IUnsupportedMediaTypeErrorResponse,
  UnsupportedMediaTypeErrorResponse,
} from "./UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse, ValidationErrorResponse } from "./ValidationErrorResponse";

export type ISharedErrorResponse =
  | IConflictErrorResponse
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | INotFoundErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnprocessableEntityErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse;

export type SharedErrorResponse =
  | ConflictErrorResponse
  | ForbiddenErrorResponse
  | InternalServerErrorResponse
  | NotFoundErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse
  | UnprocessableEntityErrorResponse
  | UnsupportedMediaTypeErrorResponse
  | ValidationErrorResponse;
