/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type IUnprocessableEntityErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IUnprocessableEntityErrorResponseBody = {
  message: "Unprocessable entity";
  code: "UNPROCESSABLE_ENTITY_ERROR";
};

export type IUnprocessableEntityErrorResponse = ITypedHttpResponse<
  "UnprocessableEntityError",
  HttpStatusCode.UNPROCESSABLE_ENTITY,
  IUnprocessableEntityErrorResponseHeader,
  IUnprocessableEntityErrorResponseBody
>;

export const createUnprocessableEntityErrorResponse = (
  input: Omit<IUnprocessableEntityErrorResponse, "type" | "statusCode">,
): IUnprocessableEntityErrorResponse => ({
  ...input,
  type: "UnprocessableEntityError",
  statusCode: HttpStatusCode.UNPROCESSABLE_ENTITY,
});
