/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITaggedHttpResponse } from "@rexeus/typeweaver-core";

export type IValidationErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IValidationErrorResponseBody = {
  message: "Request is invalid";
  code: "VALIDATION_ERROR";
  issues: {
    body?: any[] | undefined;
    query?: any[] | undefined;
    param?: any[] | undefined;
    header?: any[] | undefined;
  };
};

export type IValidationErrorResponse = ITaggedHttpResponse<
  "ValidationError",
  IValidationErrorResponseHeader,
  IValidationErrorResponseBody
> & {
  readonly statusCode: HttpStatusCode.BAD_REQUEST;
  readonly header: IValidationErrorResponseHeader;
  readonly body: IValidationErrorResponseBody;
};

export const createValidationErrorResponse = (
  input: Omit<IValidationErrorResponse, "_tag" | "statusCode">,
): IValidationErrorResponse => ({
  _tag: "ValidationError",
  statusCode: HttpStatusCode.BAD_REQUEST,
  ...input,
});
