/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { IHttpResponse } from "@rexeus/typeweaver-core";
import { createNetworkError, createResponse } from "./apiClientResponse.js";
import {
  createRequestHeaders,
  createRequestSignal,
  flattenHeaders,
  mergeRequestHeaders,
  serializeBody,
} from "./apiClientSerialization.js";
import {
  assertValidBaseUrl,
  buildFullUrl,
  createPath,
  createUrl,
} from "./apiClientUrl.js";
import { ApiClientConfigurationError } from "./errors/ApiClientConfigurationError.js";
import { RequestCommand } from "./RequestCommand.js";
import { RequestSerializationError } from "./RequestSerializationError.js";

/**
 * Configuration options for ApiClient initialization.
 */
export type ApiClientProps = {
  /** Custom fetch function for HTTP requests. Defaults to globalThis.fetch */
  readonly fetchFn?: typeof globalThis.fetch;
  /** Base URL for API requests */
  readonly baseUrl: string;
  /** Headers applied to every request unless the command supplies the same key */
  readonly defaultHeaders?: Readonly<Record<string, string>>;
  /** Query values applied to every request unless the command supplies the same key */
  readonly defaultQuery?: Readonly<Record<string, string>>;
  /** External cancellation signal forwarded to every request */
  readonly signal?: AbortSignal;
  /** Request timeout in milliseconds. When set, requests will be aborted after this duration */
  readonly timeoutMs?: number;
};

/**
 * Abstract base class for type-safe API clients.
 *
 * This class provides HTTP request execution with:
 * - Automatic path parameter substitution (`:param` style)
 * - Query string building with array support
 * - Network error handling with specific error messages
 * - Integration with RequestCommand pattern for type safety
 */
export abstract class ApiClient {
  private readonly fetchFn: typeof globalThis.fetch;
  public readonly baseUrl: string;
  private readonly defaultHeaders: Readonly<Record<string, string>>;
  private readonly defaultQuery: Readonly<Record<string, string>>;
  private readonly signal: AbortSignal | undefined;
  private readonly timeoutMs: number | undefined;

  protected constructor(props: ApiClientProps) {
    this.fetchFn = props.fetchFn ?? globalThis.fetch.bind(globalThis);

    assertValidBaseUrl(props.baseUrl);

    this.baseUrl = props.baseUrl;
    this.defaultHeaders = props.defaultHeaders ?? {};
    this.defaultQuery = props.defaultQuery ?? {};
    this.signal = props.signal;

    if (
      props.timeoutMs !== undefined &&
      (props.timeoutMs <= 0 || !Number.isFinite(props.timeoutMs))
    ) {
      throw new ApiClientConfigurationError("timeoutMs", "invalid-timeout", {
        timeoutMs: props.timeoutMs,
      });
    }

    this.timeoutMs = props.timeoutMs;
  }

  protected async execute(request: RequestCommand): Promise<IHttpResponse> {
    const { method, path, header, query, param, body } = request;

    assertNoReservedKeys(param, "path");
    assertNoReservedKeys(query, "query");
    assertNoReservedKeys(header, "header");
    assertNoReservedKeys(this.defaultQuery, "query");
    assertNoReservedKeys(this.defaultHeaders, "header");

    const pathWithParam = createPath(path, param);
    const relativeUrl = createUrl(pathWithParam, query, this.defaultQuery);
    const fullUrl = buildFullUrl(this.baseUrl, relativeUrl);

    const serializedBody = serializeBody(body);
    const headers = createRequestHeaders(
      mergeRequestHeaders(flattenHeaders(header), this.defaultHeaders),
      serializedBody.isJsonSerialized
    );

    const signal = createRequestSignal(this.signal, this.timeoutMs);
    const response = await this.performFetch(method, fullUrl, {
      method,
      ...(headers === undefined ? {} : { headers }),
      ...(serializedBody.body === undefined
        ? {}
        : { body: serializedBody.body }),
      ...(signal === undefined ? {} : { signal }),
    });

    return await createResponse(response, method, fullUrl);
  }

  private async performFetch(
    method: string,
    url: string,
    init: RequestInit
  ): Promise<Response> {
    try {
      return await this.fetchFn(url, init);
    } catch (error) {
      throw createNetworkError(error, method, url);
    }
  }
}

/**
 * Rejects an own `__proto__` key before URL or header construction.
 *
 * `__proto__` cannot be serialized or round-tripped as an ordinary HTTP
 * key, so failing explicitly is safer than dropping or mutating it.
 * `constructor` and `toString` are ordinary supported keys.
 */
function assertNoReservedKeys(
  record: Readonly<Record<string, unknown>> | undefined,
  location: "header" | "path" | "query"
): void {
  if (record === undefined || !Object.hasOwn(record, "__proto__")) {
    return;
  }

  const value: unknown = Object.getOwnPropertyDescriptor(
    record,
    "__proto__"
  )?.value;

  throw new RequestSerializationError(
    location,
    "__proto__",
    value,
    "reserved-key"
  );
}
