/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

/**
 * Typed error for response body parsing failures.
 *
 * Thrown when a JSON response body cannot be parsed. Provides structured
 * metadata via `statusCode` and `bodyPreview` properties for diagnostics
 * without relying on message string parsing.
 */
export class ResponseParseError extends Error {
  public override readonly name = "ResponseParseError";

  public constructor(
    message: string,
    public readonly statusCode: number,
    public readonly bodyPreview: string,
    options?: ErrorOptions
  ) {
    super(message, options);
  }
}
