/* eslint-disable */
/**
 * This file was automatically generated by TypeWeaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { ApiClient, type ApiClientProps } from "../lib/clients";

import { RegisterAccountRequestCommand } from "./RegisterAccountRequestCommand";
import type { SuccessfulRegisterAccountResponse } from "./RegisterAccountRequest";

export type AccountRequestCommands = RegisterAccountRequestCommand;

export type SuccessfulAccountResponses = SuccessfulRegisterAccountResponse;

export class AccountClient extends ApiClient {
  public constructor(props: ApiClientProps) {
    super(props);
  }

  public async send(
    command: RegisterAccountRequestCommand,
  ): Promise<SuccessfulRegisterAccountResponse>;

  public async send(
    command: AccountRequestCommands,
  ): Promise<SuccessfulAccountResponses> {
    const response = await this.execute(command);
    return command.processResponse(response, this.processResponseOptions);
  }
}
