/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { Context } from "hono";
import {
  TypeweaverHono,
  type HonoRequestHandler,
  type TypeweaverHonoOptions,
} from "../lib/hono";

import type { IRegisterAccountRequest } from "./RegisterAccountRequest";
import { RegisterAccountRequestValidator } from "./RegisterAccountRequestValidator";
import type { RegisterAccountResponse } from "./RegisterAccountResponse";

export type AccountApiHandler = {
  handleRegisterAccountRequest: HonoRequestHandler<
    IRegisterAccountRequest,
    RegisterAccountResponse
  >;
};

export class AccountHono extends TypeweaverHono<AccountApiHandler> {
  public constructor(options: TypeweaverHonoOptions<AccountApiHandler>) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.post("/accounts", async (context: Context) =>
      this.handleRequest(
        context,
        new RegisterAccountRequestValidator(),
        this.requestHandlers.handleRegisterAccountRequest.bind(
          this.requestHandlers,
        ),
      ),
    );
  }
}
