/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { Context } from "hono";
import type { BlankEnv, BlankSchema } from "hono/types";
import {
  TypeweaverHono,
  type HonoRequestHandler,
  type TypeweaverHonoOptions,
} from "../lib/hono/index.js";

import type {
  IRegisterAccountRequest,
  IRawRegisterAccountRequest,
} from "./RegisterAccountRequest.js";
import { RegisterAccountRequestValidator } from "./RegisterAccountRequestValidator.js";
import type { RegisterAccountResponse } from "./RegisterAccountResponse.js";
import { RegisterAccountResponseValidator } from "./RegisterAccountResponseValidator.js";

type HandlerRequest<TValidateRequests extends boolean, TValidated, TRaw> = [
  TValidateRequests,
] extends [true]
  ? TValidated
  : TRaw;

export type HonoAccountApiHandler<TValidateRequests extends boolean = true> = {
  /**
   * Register new account
   */
  handleRegisterAccountRequest: HonoRequestHandler<
    HandlerRequest<TValidateRequests, IRegisterAccountRequest, IRawRegisterAccountRequest>,
    RegisterAccountResponse
  >;
};

export class AccountHono<TValidateRequests extends boolean = true> extends TypeweaverHono<
  HonoAccountApiHandler<TValidateRequests>,
  BlankEnv,
  BlankSchema,
  "/",
  TValidateRequests
> {
  public constructor(
    options: TypeweaverHonoOptions<
      HonoAccountApiHandler<TValidateRequests>,
      BlankEnv,
      TValidateRequests
    >,
  ) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.post("/accounts", async (context: Context) =>
      this.handleRequest({
        context,
        operationId: "RegisterAccount",
        requestValidator: new RegisterAccountRequestValidator(),
        responseValidator: new RegisterAccountResponseValidator(),
        handler: this.requestHandlers.handleRegisterAccountRequest.bind(this.requestHandlers),
      }),
    );
  }
}
