/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import spec from "../spec/spec";
import {
  getOperationDefinition,
  getResponseDefinition,
  type ResponseEntry,
  ResponseValidator,
} from "../lib/types";
import type { RegisterAccountResponse } from "./RegisterAccountResponse";

const definition = getOperationDefinition(spec, "account", "RegisterAccount");

const registerAccountSuccessDefinition = getResponseDefinition(
  definition.responses,
  "RegisterAccountSuccess",
);

const forbiddenErrorDefinition = getResponseDefinition(definition.responses, "ForbiddenError");

const internalServerErrorDefinition = getResponseDefinition(
  definition.responses,
  "InternalServerError",
);

const tooManyRequestsErrorDefinition = getResponseDefinition(
  definition.responses,
  "TooManyRequestsError",
);

const unauthorizedErrorDefinition = getResponseDefinition(
  definition.responses,
  "UnauthorizedError",
);

const unsupportedMediaTypeErrorDefinition = getResponseDefinition(
  definition.responses,
  "UnsupportedMediaTypeError",
);

const validationErrorDefinition = getResponseDefinition(definition.responses, "ValidationError");

export class RegisterAccountResponseValidator extends ResponseValidator<RegisterAccountResponse> {
  protected override readonly expectedStatusCodes = [201, 400, 401, 403, 415, 429, 500];

  protected override readonly responseEntries: readonly ResponseEntry[] = [
    {
      name: "RegisterAccountSuccess",
      statusCode: 201,
      headerSchema: registerAccountSuccessDefinition.header,
      bodySchema: registerAccountSuccessDefinition.body,
    },

    {
      name: "ForbiddenError",
      statusCode: 403,
      headerSchema: forbiddenErrorDefinition.header,
      bodySchema: forbiddenErrorDefinition.body,
    },

    {
      name: "InternalServerError",
      statusCode: 500,
      headerSchema: internalServerErrorDefinition.header,
      bodySchema: internalServerErrorDefinition.body,
    },

    {
      name: "TooManyRequestsError",
      statusCode: 429,
      headerSchema: tooManyRequestsErrorDefinition.header,
      bodySchema: tooManyRequestsErrorDefinition.body,
    },

    {
      name: "UnauthorizedError",
      statusCode: 401,
      headerSchema: unauthorizedErrorDefinition.header,
      bodySchema: unauthorizedErrorDefinition.body,
    },

    {
      name: "UnsupportedMediaTypeError",
      statusCode: 415,
      headerSchema: unsupportedMediaTypeErrorDefinition.header,
      bodySchema: unsupportedMediaTypeErrorDefinition.body,
    },

    {
      name: "ValidationError",
      statusCode: 400,
      headerSchema: validationErrorDefinition.header,
      bodySchema: validationErrorDefinition.body,
    },
  ];
}
