/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

import type { IForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../shared/ValidationErrorResponse";

export type IRegisterAccountSuccessResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IRegisterAccountSuccessResponseBody = {
  id: string;
  email: string;
  createdAt: string;
  modifiedAt: string;
  createdBy: string;
  modifiedBy: string;
};

export type IRegisterAccountSuccessResponse = ITypedHttpResponse<
  "RegisterAccountSuccess",
  HttpStatusCode.CREATED,
  IRegisterAccountSuccessResponseHeader,
  IRegisterAccountSuccessResponseBody
>;

export const createRegisterAccountSuccessResponse = (
  input: Omit<IRegisterAccountSuccessResponse, "type" | "statusCode">,
): IRegisterAccountSuccessResponse => ({
  ...input,
  type: "RegisterAccountSuccess",
  statusCode: HttpStatusCode.CREATED,
});

export type RegisterAccountResponse =
  | IRegisterAccountSuccessResponse
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse;
