/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type {
  ResponseDefinition,
  SpecDefinition,
} from "@rexeus/typeweaver-core";
import { MissingOperationDefinitionError } from "./errors/MissingOperationDefinitionError.js";
import { MissingResponseDefinitionError } from "./errors/MissingResponseDefinitionError.js";

type MatchedOperationDefinition<
  TSpec extends SpecDefinition,
  TResourceName extends keyof TSpec["resources"] & string,
  TOperationId extends string,
> =
  Extract<
    NonNullable<TSpec["resources"][TResourceName]>["operations"][number],
    { readonly operationId: TOperationId }
  > extends never
    ? NonNullable<TSpec["resources"][TResourceName]>["operations"][number]
    : Extract<
        NonNullable<TSpec["resources"][TResourceName]>["operations"][number],
        { readonly operationId: TOperationId }
      >;

type MatchedResponseDefinition<
  TResponses extends readonly ResponseDefinition[],
> = TResponses[number];

export const getOperationDefinition = <
  TSpec extends SpecDefinition,
  TResourceName extends keyof TSpec["resources"] & string,
  TOperationId extends string,
>(
  spec: TSpec,
  resourceName: TResourceName,
  operationId: TOperationId
): MatchedOperationDefinition<TSpec, TResourceName, TOperationId> => {
  const operation = spec.resources[resourceName]?.operations.find(
    candidate => candidate.operationId === operationId
  );

  if (operation === undefined) {
    throw new MissingOperationDefinitionError(
      String(resourceName),
      String(operationId)
    );
  }

  return operation as MatchedOperationDefinition<
    TSpec,
    TResourceName,
    TOperationId
  >;
};

export const getResponseDefinition = <
  TResponses extends readonly ResponseDefinition[],
>(
  responses: TResponses,
  responseName: string
): MatchedResponseDefinition<TResponses> => {
  const response = responses.find(candidate => candidate.name === responseName);

  if (response === undefined) {
    throw new MissingResponseDefinitionError(String(responseName));
  }

  return response as MatchedResponseDefinition<TResponses>;
};
