/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type {
  HttpBodySchema,
  HttpHeaderSchema,
  IHttpResponse,
  IResponseValidator,
  ITypedHttpResponse,
  SafeResponseValidationResult,
} from "@rexeus/typeweaver-core";
import { ResponseValidationError } from "@rexeus/typeweaver-core";
import { Validator } from "./Validator";
import type { ZodSafeParseResult } from "zod";

type Mutable<T> = { -readonly [K in keyof T]: T[K] };

/**
 * Metadata entry describing a single expected response variant.
 *
 * Each entry maps a response name and status code to its Zod
 * header/body schemas from the operation definition.
 */
export type ResponseEntry = {
  readonly name: string;
  readonly statusCode: number;
  readonly headerSchema: HttpHeaderSchema | undefined;
  readonly bodySchema: HttpBodySchema | undefined;
};

/**
 * Abstract base class for HTTP response validation.
 *
 * This class provides the foundation for response validators that:
 * - Validate response status codes match expected values
 * - Validate response headers and body against schemas
 * - Support both safe (non-throwing) and unsafe (throwing) validation
 * - Integrate with Zod schemas for runtime validation
 *
 * Response validators are typically used in API clients to ensure
 * responses match the expected format before processing.
 *
 * Subclasses provide response metadata via `responseEntries` and
 * `expectedStatusCodes`. All validation logic lives in this base class.
 */
export abstract class ResponseValidator<
  TResponse extends ITypedHttpResponse = ITypedHttpResponse,
>
  extends Validator
  implements IResponseValidator
{
  /** Ordered list of response variants this validator recognizes. */
  protected abstract readonly responseEntries: readonly ResponseEntry[];
  /** Set of valid HTTP status codes for this operation. */
  protected abstract readonly expectedStatusCodes: readonly number[];

  /**
   * Validates a response without throwing errors.
   *
   * @param response - The HTTP response to validate
   * @returns A result object containing either the validated response or error details
   */
  public safeValidate(
    response: IHttpResponse
  ): SafeResponseValidationResult<TResponse> {
    const error = new ResponseValidationError(response.statusCode);

    for (const entry of this.responseEntries) {
      if (response.statusCode === entry.statusCode) {
        const result = this.validateResponseType<TResponse>(
          entry.name,
          entry.headerSchema,
          entry.bodySchema
        )(response, error);
        if (result.isValid) return result;
      }
    }

    if (!error.hasResponseIssues()) {
      error.addStatusCodeIssue([...this.expectedStatusCodes]);
    }

    return { isValid: false, error };
  }

  /**
   * Validates a response and throws if validation fails.
   *
   * @param response - The HTTP response to validate
   * @returns The validated response with proper typing
   * @throws {ResponseValidationError} If response structure fails validation
   */
  public validate(response: IHttpResponse): TResponse {
    const result = this.safeValidate(response);
    if (!result.isValid) throw result.error;
    return result.data;
  }

  /**
   * Validates a single response variant against its header and body schemas.
   *
   * @param responseName - Name of the response type for error reporting
   * @param headerSchema - Zod schema for header validation (optional)
   * @param bodySchema - Zod schema for body validation (optional)
   * @returns Function that validates response and returns result
   */
  protected validateResponseType<Response extends ITypedHttpResponse>(
    responseName: string,
    headerSchema: HttpHeaderSchema | undefined,
    bodySchema: HttpBodySchema | undefined
  ): (
    response: IHttpResponse,
    error: ResponseValidationError
  ) => SafeResponseValidationResult<Response> {
    return (response, error) => {
      let isValid = true;
      const validatedResponse: Mutable<ITypedHttpResponse> = {
        type: responseName,
        statusCode: response.statusCode,
        header: undefined,
        body: undefined,
      };

      if (bodySchema) {
        const validateBodyResult = bodySchema.safeParse(
          response.body
        ) as unknown as ZodSafeParseResult<Response["body"]>;

        if (!validateBodyResult.success) {
          error.addBodyIssues(responseName, validateBodyResult.error.issues);
          isValid = false;
        } else {
          validatedResponse.body = validateBodyResult.data;
        }
      }

      if (headerSchema) {
        const coercedHeader = this.coerceHeaderToSchema(
          response.header,
          this.getSchema(headerSchema)
        );
        const validateHeaderResult = headerSchema.safeParse(
          coercedHeader
        ) as unknown as ZodSafeParseResult<Response["header"]>;

        if (!validateHeaderResult.success) {
          error.addHeaderIssues(
            responseName,
            validateHeaderResult.error.issues
          );
          isValid = false;
        } else {
          validatedResponse.header = validateHeaderResult.data;
        }
      }

      if (!isValid) {
        return { isValid: false, error };
      }

      return { isValid: true, data: validatedResponse as Response };
    };
  }
}
