/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITaggedHttpResponse } from "@rexeus/typeweaver-core";

import type { IForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../shared/ValidationErrorResponse";

export type IDownloadFileContentSuccessResponseHeader = {
  "Content-Type": "application/octet-stream";
};

export type IDownloadFileContentSuccessResponseBody = any;

export type IDownloadFileContentSuccessResponse = ITaggedHttpResponse<
  "DownloadFileContentSuccess",
  IDownloadFileContentSuccessResponseHeader,
  IDownloadFileContentSuccessResponseBody
> & {
  readonly statusCode: HttpStatusCode.OK;
  readonly header: IDownloadFileContentSuccessResponseHeader;
  readonly body: IDownloadFileContentSuccessResponseBody;
};

export const createDownloadFileContentSuccessResponse = (
  input: Omit<IDownloadFileContentSuccessResponse, "_tag" | "statusCode">,
): IDownloadFileContentSuccessResponse => ({
  _tag: "DownloadFileContentSuccess",
  statusCode: HttpStatusCode.OK,
  ...input,
});

export type IDownloadFileContentSuccessResponses = IDownloadFileContentSuccessResponse;

export type DownloadFileContentSuccessResponses = IDownloadFileContentSuccessResponses;

export type IDownloadFileContentResponse =
  | IDownloadFileContentSuccessResponse
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse;

export type DownloadFileContentResponse = IDownloadFileContentResponse;
