/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import definition from "../definition/file/DownloadFileContentDefinition";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../lib/clients";
import { DownloadFileContentResponseValidator } from "./DownloadFileContentResponseValidator";
import type {
  IDownloadFileContentRequest,
  IDownloadFileContentRequestHeader,
  IDownloadFileContentRequestParam,
} from "./DownloadFileContentRequest";
import type { DownloadFileContentResponse } from "./DownloadFileContentResponse";

const responseValidator = new DownloadFileContentResponseValidator();

export class DownloadFileContentRequestCommand
  extends RequestCommand
  implements IDownloadFileContentRequest
{
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.GET;
  public override readonly path = definition.path;

  public override readonly header: IDownloadFileContentRequestHeader;
  public override readonly param: IDownloadFileContentRequestParam;
  declare public readonly query: undefined;
  declare public readonly body: undefined;

  public constructor(input: Omit<IDownloadFileContentRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.param = input.param;
  }

  public processResponse(response: IHttpResponse): DownloadFileContentResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
