/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import {
  HttpMethod,
  TypeweaverRouter,
  type RequestHandler,
  type TypeweaverRouterOptions,
} from "../lib/server/index.js";

import type { IUploadFileRequest } from "./UploadFileRequest.js";
import { UploadFileRequestValidator } from "./UploadFileRequestValidator.js";
import type { UploadFileResponse } from "./UploadFileResponse.js";
import { UploadFileResponseValidator } from "./UploadFileResponseValidator.js";

import type { IGetFileMetadataRequest } from "./GetFileMetadataRequest.js";
import { GetFileMetadataRequestValidator } from "./GetFileMetadataRequestValidator.js";
import type { GetFileMetadataResponse } from "./GetFileMetadataResponse.js";
import { GetFileMetadataResponseValidator } from "./GetFileMetadataResponseValidator.js";

import type { IDownloadFileContentRequest } from "./DownloadFileContentRequest.js";
import { DownloadFileContentRequestValidator } from "./DownloadFileContentRequestValidator.js";
import type { DownloadFileContentResponse } from "./DownloadFileContentResponse.js";
import { DownloadFileContentResponseValidator } from "./DownloadFileContentResponseValidator.js";

export type ServerFileApiHandler<TState extends Record<string, unknown> = Record<string, unknown>> =
  {
    /**
     * Upload a file
     */
    handleUploadFileRequest: RequestHandler<IUploadFileRequest, UploadFileResponse, TState>;

    /**
     * Get file metadata
     */
    handleGetFileMetadataRequest: RequestHandler<
      IGetFileMetadataRequest,
      GetFileMetadataResponse,
      TState
    >;

    /**
     * Download file content
     */
    handleDownloadFileContentRequest: RequestHandler<
      IDownloadFileContentRequest,
      DownloadFileContentResponse,
      TState
    >;
  };

export class FileRouter<
  TState extends Record<string, unknown> = Record<string, unknown>,
> extends TypeweaverRouter<ServerFileApiHandler<TState>> {
  public constructor(options: TypeweaverRouterOptions<ServerFileApiHandler<TState>>) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.route(
      "UploadFile",
      HttpMethod.POST,
      "/files",
      new UploadFileRequestValidator(),
      new UploadFileResponseValidator(),
      this.requestHandlers.handleUploadFileRequest.bind(this.requestHandlers),
    );

    this.route(
      "GetFileMetadata",
      HttpMethod.GET,
      "/files/:fileId",
      new GetFileMetadataRequestValidator(),
      new GetFileMetadataResponseValidator(),
      this.requestHandlers.handleGetFileMetadataRequest.bind(this.requestHandlers),
    );

    this.route(
      "DownloadFileContent",
      HttpMethod.GET,
      "/files/:fileId/content",
      new DownloadFileContentRequestValidator(),
      new DownloadFileContentResponseValidator(),
      this.requestHandlers.handleDownloadFileContentRequest.bind(this.requestHandlers),
    );
  }
}
