/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { Context } from "hono";
import {
  TypeweaverHono,
  type HonoRequestHandler,
  type TypeweaverHonoOptions,
} from "./../lib/hono/index.js";

import type { IUploadFileRequest } from "./UploadFileRequest.js";
import { UploadFileRequestValidator } from "./UploadFileRequestValidator.js";
import type { UploadFileResponse } from "./UploadFileResponse.js";
import { UploadFileResponseValidator } from "./UploadFileResponseValidator.js";

import type { IGetFileMetadataRequest } from "./GetFileMetadataRequest.js";
import { GetFileMetadataRequestValidator } from "./GetFileMetadataRequestValidator.js";
import type { GetFileMetadataResponse } from "./GetFileMetadataResponse.js";
import { GetFileMetadataResponseValidator } from "./GetFileMetadataResponseValidator.js";

import type { IDownloadFileContentRequest } from "./DownloadFileContentRequest.js";
import { DownloadFileContentRequestValidator } from "./DownloadFileContentRequestValidator.js";
import type { DownloadFileContentResponse } from "./DownloadFileContentResponse.js";
import { DownloadFileContentResponseValidator } from "./DownloadFileContentResponseValidator.js";

export type HonoFileApiHandler = {
  handleUploadFileRequest: HonoRequestHandler<IUploadFileRequest, UploadFileResponse>;

  handleGetFileMetadataRequest: HonoRequestHandler<
    IGetFileMetadataRequest,
    GetFileMetadataResponse
  >;

  handleDownloadFileContentRequest: HonoRequestHandler<
    IDownloadFileContentRequest,
    DownloadFileContentResponse
  >;
};

export class FileHono extends TypeweaverHono<HonoFileApiHandler> {
  public constructor(options: TypeweaverHonoOptions<HonoFileApiHandler>) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.post("/files", async (context: Context) =>
      this.handleRequest(
        context,
        "UploadFile",
        new UploadFileRequestValidator(),
        new UploadFileResponseValidator(),
        this.requestHandlers.handleUploadFileRequest.bind(this.requestHandlers),
      ),
    );

    this.get("/files/:fileId", async (context: Context) =>
      this.handleRequest(
        context,
        "GetFileMetadata",
        new GetFileMetadataRequestValidator(),
        new GetFileMetadataResponseValidator(),
        this.requestHandlers.handleGetFileMetadataRequest.bind(this.requestHandlers),
      ),
    );

    this.get("/files/:fileId/content", async (context: Context) =>
      this.handleRequest(
        context,
        "DownloadFileContent",
        new DownloadFileContentRequestValidator(),
        new DownloadFileContentResponseValidator(),
        this.requestHandlers.handleDownloadFileContentRequest.bind(this.requestHandlers),
      ),
    );
  }
}
