/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { Context } from "hono";
import {
  TypeweaverHono,
  type HonoRequestHandler,
  type TypeweaverHonoOptions,
} from "../lib/hono";

import type { IUploadFileRequest } from "./UploadFileRequest";
import { UploadFileRequestValidator } from "./UploadFileRequestValidator";
import type { UploadFileResponse } from "./UploadFileResponse";

import type { IGetFileMetadataRequest } from "./GetFileMetadataRequest";
import { GetFileMetadataRequestValidator } from "./GetFileMetadataRequestValidator";
import type { GetFileMetadataResponse } from "./GetFileMetadataResponse";

import type { IDownloadFileContentRequest } from "./DownloadFileContentRequest";
import { DownloadFileContentRequestValidator } from "./DownloadFileContentRequestValidator";
import type { DownloadFileContentResponse } from "./DownloadFileContentResponse";

export type HonoFileApiHandler = {
  handleUploadFileRequest: HonoRequestHandler<
    IUploadFileRequest,
    UploadFileResponse
  >;

  handleGetFileMetadataRequest: HonoRequestHandler<
    IGetFileMetadataRequest,
    GetFileMetadataResponse
  >;

  handleDownloadFileContentRequest: HonoRequestHandler<
    IDownloadFileContentRequest,
    DownloadFileContentResponse
  >;
};

export class FileHono extends TypeweaverHono<HonoFileApiHandler> {
  public constructor(options: TypeweaverHonoOptions<HonoFileApiHandler>) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.post("/files", async (context: Context) =>
      this.handleRequest(
        context,
        new UploadFileRequestValidator(),
        this.requestHandlers.handleUploadFileRequest.bind(this.requestHandlers),
      ),
    );

    this.get("/files/:fileId", async (context: Context) =>
      this.handleRequest(
        context,
        new GetFileMetadataRequestValidator(),
        this.requestHandlers.handleGetFileMetadataRequest.bind(
          this.requestHandlers,
        ),
      ),
    );

    this.get("/files/:fileId/content", async (context: Context) =>
      this.handleRequest(
        context,
        new DownloadFileContentRequestValidator(),
        this.requestHandlers.handleDownloadFileContentRequest.bind(
          this.requestHandlers,
        ),
      ),
    );
  }
}
