/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { ApiClient, type ApiClientProps } from "../lib/clients";

import { DownloadFileContentRequestCommand } from "./DownloadFileContentRequestCommand";
import type { DownloadFileContentResponse } from "./DownloadFileContentResponse";

import { GetFileMetadataRequestCommand } from "./GetFileMetadataRequestCommand";
import type { GetFileMetadataResponse } from "./GetFileMetadataResponse";

import { UploadFileRequestCommand } from "./UploadFileRequestCommand";
import type { UploadFileResponse } from "./UploadFileResponse";

export type FileRequestCommands =
  | DownloadFileContentRequestCommand
  | GetFileMetadataRequestCommand
  | UploadFileRequestCommand;

export type FileResponses =
  | DownloadFileContentResponse
  | GetFileMetadataResponse
  | UploadFileResponse;

export class FileClient extends ApiClient {
  public constructor(props: ApiClientProps) {
    super(props);
  }

  public async send(
    command: DownloadFileContentRequestCommand,
  ): Promise<DownloadFileContentResponse>;

  public async send(command: GetFileMetadataRequestCommand): Promise<GetFileMetadataResponse>;

  public async send(command: UploadFileRequestCommand): Promise<UploadFileResponse>;

  public async send(command: FileRequestCommands): Promise<FileResponses> {
    const response = await this.execute(command);
    return command.processResponse(response);
  }
}
