/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import definition from "../definition/file/GetFileMetadataDefinition";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  createUnknownResponse,
} from "@rexeus/typeweaver-core";
import { RequestCommand, type ProcessResponseOptions } from "../lib/clients";
import { GetFileMetadataResponseValidator } from "./GetFileMetadataResponseValidator";
import type {
  IGetFileMetadataRequest,
  IGetFileMetadataRequestHeader,
  IGetFileMetadataRequestParam,
  SuccessfulGetFileMetadataResponse,
} from "./GetFileMetadataRequest";

export class GetFileMetadataRequestCommand
  extends RequestCommand
  implements IGetFileMetadataRequest
{
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.GET;
  public override readonly path = definition.path;

  public override readonly header: IGetFileMetadataRequestHeader;
  public override readonly param: IGetFileMetadataRequestParam;
  declare public readonly query: undefined;
  declare public readonly body: undefined;

  private readonly responseValidator: GetFileMetadataResponseValidator;

  public constructor(input: Omit<IGetFileMetadataRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.param = input.param;

    this.responseValidator = new GetFileMetadataResponseValidator();
  }

  public processResponse(
    response: IHttpResponse,
    options: ProcessResponseOptions,
  ): SuccessfulGetFileMetadataResponse {
    try {
      const result = this.responseValidator.validate(response);

      if (result._tag === "GetFileMetadataSuccess") {
        return result as SuccessfulGetFileMetadataResponse;
      }

      throw result;
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        const unknownResponse = createUnknownResponse(
          response.statusCode,
          response.header,
          response.body,
          error,
        );

        if (
          options.unknownResponseHandling === "passthrough" &&
          options.isSuccessStatusCode(response.statusCode)
        ) {
          return unknownResponse as any;
        }

        throw unknownResponse;
      }
      throw error;
    }
  }
}
