/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

import type { IForbiddenErrorResponse } from "../responses/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../responses/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../responses/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../responses/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../responses/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../responses/ValidationErrorResponse";

export type IGetFileMetadataSuccessResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IGetFileMetadataSuccessResponseBody = {
  id: string;
  name: string;
  size: number;
  mimeType: string;
  createdAt: string;
};

export type IGetFileMetadataSuccessResponse = ITypedHttpResponse<
  "GetFileMetadataSuccess",
  HttpStatusCode.OK,
  IGetFileMetadataSuccessResponseHeader,
  IGetFileMetadataSuccessResponseBody
>;

export const createGetFileMetadataSuccessResponse = (
  input: Omit<IGetFileMetadataSuccessResponse, "type" | "statusCode">,
): IGetFileMetadataSuccessResponse => ({
  ...input,
  type: "GetFileMetadataSuccess",
  statusCode: HttpStatusCode.OK,
});

export type GetFileMetadataResponse =
  | IGetFileMetadataSuccessResponse
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse;
