/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import spec from "../spec/spec";
import { type ResponseEntry, ResponseValidator } from "../lib/types";
import type { GetFileMetadataResponse } from "./GetFileMetadataResponse";

const definition = spec.resources["file"]!.operations.find(
  (operation) => operation.operationId === "GetFileMetadata",
)!;
const responseDefinitions = new Map(
  definition.responses.map((response) => [response.name, response] as const),
);

export class GetFileMetadataResponseValidator extends ResponseValidator<GetFileMetadataResponse> {
  protected override readonly expectedStatusCodes = [200, 400, 401, 403, 415, 429, 500];

  protected override readonly responseEntries: readonly ResponseEntry[] = [
    {
      name: "GetFileMetadataSuccess",
      statusCode: 200,
      headerSchema: responseDefinitions.get("GetFileMetadataSuccess")?.header,
      bodySchema: responseDefinitions.get("GetFileMetadataSuccess")?.body,
    },

    {
      name: "ForbiddenError",
      statusCode: 403,
      headerSchema: responseDefinitions.get("ForbiddenError")?.header,
      bodySchema: responseDefinitions.get("ForbiddenError")?.body,
    },

    {
      name: "InternalServerError",
      statusCode: 500,
      headerSchema: responseDefinitions.get("InternalServerError")?.header,
      bodySchema: responseDefinitions.get("InternalServerError")?.body,
    },

    {
      name: "TooManyRequestsError",
      statusCode: 429,
      headerSchema: responseDefinitions.get("TooManyRequestsError")?.header,
      bodySchema: responseDefinitions.get("TooManyRequestsError")?.body,
    },

    {
      name: "UnauthorizedError",
      statusCode: 401,
      headerSchema: responseDefinitions.get("UnauthorizedError")?.header,
      bodySchema: responseDefinitions.get("UnauthorizedError")?.body,
    },

    {
      name: "UnsupportedMediaTypeError",
      statusCode: 415,
      headerSchema: responseDefinitions.get("UnsupportedMediaTypeError")?.header,
      bodySchema: responseDefinitions.get("UnsupportedMediaTypeError")?.body,
    },

    {
      name: "ValidationError",
      statusCode: 400,
      headerSchema: responseDefinitions.get("ValidationError")?.header,
      bodySchema: responseDefinitions.get("ValidationError")?.body,
    },
  ];
}
