/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod } from "@rexeus/typeweaver-core";
import type { GetFileMetadataResponse } from "./GetFileMetadataResponse";

import type { IForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../shared/ValidationErrorResponse";

export type IGetFileMetadataRequestHeader = {
  Accept: "application/json";
  Authorization: string;
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IGetFileMetadataRequestParam = {
  fileId: string;
};

export type IGetFileMetadataRequest = {
  path: string;
  method: HttpMethod.GET;
  header: IGetFileMetadataRequestHeader;
  param: IGetFileMetadataRequestParam;
};

export type SuccessfulGetFileMetadataResponse = Exclude<
  GetFileMetadataResponse,
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse
>;
