/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod } from "@rexeus/typeweaver-core";
import type { UploadFileResponse } from "./UploadFileResponse";

import type { IForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../shared/ValidationErrorResponse";

export type IUploadFileRequestHeader = {
  "Content-Type": "application/octet-stream";
  Authorization: string;
  "X-File-Name": string;
};

export type IUploadFileRequestBody = any;

export type IUploadFileRequest = {
  path: string;
  method: HttpMethod.POST;
  header: IUploadFileRequestHeader;

  body: IUploadFileRequestBody;
};

export type SuccessfulUploadFileResponse = Exclude<
  UploadFileResponse,
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse
>;
