export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  ALREADY_REPORTED = 208,
  IM_USED = 226,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  IM_A_TEAPOT = 418,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507,
  LOOP_DETECTED = 508,
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}

type HttpStatusCodeNameMapKey =
  (typeof HttpStatusCode)[keyof typeof HttpStatusCode];

export const HttpStatusCodeNameMap: Record<HttpStatusCodeNameMapKey, string> = {
  [HttpStatusCode.OK]: "Ok",
  [HttpStatusCode.CREATED]: "Created",
  [HttpStatusCode.ACCEPTED]: "Accepted",
  [HttpStatusCode.NO_CONTENT]: "NoContent",
  [HttpStatusCode.RESET_CONTENT]: "ResetContent",
  [HttpStatusCode.PARTIAL_CONTENT]: "PartialContent",
  [HttpStatusCode.MULTI_STATUS]: "MultiStatus",
  [HttpStatusCode.ALREADY_REPORTED]: "AlreadyReported",
  [HttpStatusCode.IM_USED]: "ImUsed",
  [HttpStatusCode.MULTIPLE_CHOICES]: "MultipleChoices",
  [HttpStatusCode.MOVED_PERMANENTLY]: "MovedPermanently",
  [HttpStatusCode.FOUND]: "Found",
  [HttpStatusCode.SEE_OTHER]: "SeeOther",
  [HttpStatusCode.NOT_MODIFIED]: "NotModified",
  [HttpStatusCode.TEMPORARY_REDIRECT]: "TemporaryRedirect",
  [HttpStatusCode.PERMANENT_REDIRECT]: "PermanentRedirect",
  [HttpStatusCode.BAD_REQUEST]: "BadRequest",
  [HttpStatusCode.UNAUTHORIZED]: "Unauthorized",
  [HttpStatusCode.PAYMENT_REQUIRED]: "PaymentRequired",
  [HttpStatusCode.FORBIDDEN]: "Forbidden",
  [HttpStatusCode.NOT_FOUND]: "NotFound",
  [HttpStatusCode.METHOD_NOT_ALLOWED]: "MethodNotAllowed",
  [HttpStatusCode.NOT_ACCEPTABLE]: "NotAcceptable",
  [HttpStatusCode.PROXY_AUTHENTICATION_REQUIRED]: "ProxyAuthenticationRequired",
  [HttpStatusCode.REQUEST_TIMEOUT]: "RequestTimeout",
  [HttpStatusCode.CONFLICT]: "Conflict",
  [HttpStatusCode.GONE]: "Gone",
  [HttpStatusCode.LENGTH_REQUIRED]: "LengthRequired",
  [HttpStatusCode.PRECONDITION_FAILED]: "PreconditionFailed",
  [HttpStatusCode.PAYLOAD_TOO_LARGE]: "PayloadTooLarge",
  [HttpStatusCode.URI_TOO_LONG]: "UriTooLong",
  [HttpStatusCode.UNSUPPORTED_MEDIA_TYPE]: "UnsupportedMediaType",
  [HttpStatusCode.RANGE_NOT_SATISFIABLE]: "RangeNotSatisfiable",
  [HttpStatusCode.EXPECTATION_FAILED]: "ExpectationFailed",
  [HttpStatusCode.IM_A_TEAPOT]: "ImATeapot",
  [HttpStatusCode.MISDIRECTED_REQUEST]: "MisdirectedRequest",
  [HttpStatusCode.UNPROCESSABLE_ENTITY]: "UnprocessableEntity",
  [HttpStatusCode.LOCKED]: "Locked",
  [HttpStatusCode.FAILED_DEPENDENCY]: "FailedDependency",
  [HttpStatusCode.UPGRADE_REQUIRED]: "UpgradeRequired",
  [HttpStatusCode.PRECONDITION_REQUIRED]: "PreconditionRequired",
  [HttpStatusCode.TOO_MANY_REQUESTS]: "TooManyRequests",
  [HttpStatusCode.REQUEST_HEADER_FIELDS_TOO_LARGE]:
    "RequestHeaderFieldsTooLarge",
  [HttpStatusCode.UNAVAILABLE_FOR_LEGAL_REASONS]: "UnavailableForLegalReasons",
  [HttpStatusCode.INTERNAL_SERVER_ERROR]: "InternalServerError",
  [HttpStatusCode.NOT_IMPLEMENTED]: "NotImplemented",
  [HttpStatusCode.BAD_GATEWAY]: "BadGateway",
  [HttpStatusCode.SERVICE_UNAVAILABLE]: "ServiceUnavailable",
  [HttpStatusCode.GATEWAY_TIMEOUT]: "GatewayTimeout",
  [HttpStatusCode.HTTP_VERSION_NOT_SUPPORTED]: "HttpVersionNotSupported",
  [HttpStatusCode.VARIANT_ALSO_NEGOTIATES]: "VariantAlsoNegotiates",
  [HttpStatusCode.INSUFFICIENT_STORAGE]: "InsufficientStorage",
  [HttpStatusCode.LOOP_DETECTED]: "LoopDetected",
  [HttpStatusCode.NOT_EXTENDED]: "NotExtended",
  [HttpStatusCode.NETWORK_AUTHENTICATION_REQUIRED]:
    "NetworkAuthenticationRequired",
};
