/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type IDownloadFileContentSuccessResponseHeader = {
  "Content-Type": "application/octet-stream";
};

export type IDownloadFileContentSuccessResponseBody = any;

export type IDownloadFileContentSuccessResponse = ITypedHttpResponse<
  "DownloadFileContentSuccess",
  HttpStatusCode.OK,
  IDownloadFileContentSuccessResponseHeader,
  IDownloadFileContentSuccessResponseBody
>;

export const createDownloadFileContentSuccessResponse = (input: {
  header: IDownloadFileContentSuccessResponseHeader;
  body: IDownloadFileContentSuccessResponseBody;
}): IDownloadFileContentSuccessResponse => ({
  type: "DownloadFileContentSuccess",
  statusCode: HttpStatusCode.OK,
  header: input.header,
  body: input.body,
});
