/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type IGetMetricLabelsSuccessResponseHeader = {
  "Content-Type": "application/json";
};

export type IGetMetricLabelsSuccessResponseBody = {
  metricId: number;
  labels: Record<string, number>;
  flags: Record<string, boolean>;
};

/**
 * The parsed metric label records
 */
export type IGetMetricLabelsSuccessResponse = ITypedHttpResponse<
  "GetMetricLabelsSuccess",
  HttpStatusCode.OK,
  IGetMetricLabelsSuccessResponseHeader,
  IGetMetricLabelsSuccessResponseBody
>;

/**
 * The parsed metric label records
 */
export const createGetMetricLabelsSuccessResponse = (input: {
  header: IGetMetricLabelsSuccessResponseHeader;
  body: IGetMetricLabelsSuccessResponseBody;
}): IGetMetricLabelsSuccessResponse => ({
  type: "GetMetricLabelsSuccess",
  statusCode: HttpStatusCode.OK,
  header: input.header,
  body: input.body,
});
