/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type IOptionsTodoSuccessResponseHeader = {
  Allow: string[];
  "Access-Control-Allow-Origin"?: string | undefined;
  "Access-Control-Allow-Methods"?: string[] | undefined;
  "Access-Control-Allow-Headers"?: string[] | undefined;
  "Access-Control-Max-Age"?: string | undefined;
};

export type IOptionsTodoSuccessResponse = ITypedHttpResponse<
  "OptionsTodoSuccess",
  HttpStatusCode.OK,
  IOptionsTodoSuccessResponseHeader,
  undefined
>;

export const createOptionsTodoSuccessResponse = (input: {
  header: IOptionsTodoSuccessResponseHeader;
}): IOptionsTodoSuccessResponse => ({
  type: "OptionsTodoSuccess",
  statusCode: HttpStatusCode.OK,
  header: input.header,
  body: undefined,
});
