/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type IQueryTodoSuccessResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IQueryTodoSuccessResponseBody = {
  results: {
    id: string;
    accountId: string;
    parentId?: string | undefined;
    title: string;
    description?: string | undefined;
    status: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    priority?: ("LOW" | "MEDIUM" | "HIGH") | undefined;
    createdAt: string;
    modifiedAt: string;
    createdBy: string;
    modifiedBy: string;
  }[];
  nextToken?: string | undefined;
};

export type IQueryTodoSuccessResponse = ITypedHttpResponse<
  "QueryTodoSuccess",
  HttpStatusCode.OK,
  IQueryTodoSuccessResponseHeader,
  IQueryTodoSuccessResponseBody
>;

export const createQueryTodoSuccessResponse = (input: {
  header: IQueryTodoSuccessResponseHeader;
  body: IQueryTodoSuccessResponseBody;
}): IQueryTodoSuccessResponse => ({
  type: "QueryTodoSuccess",
  statusCode: HttpStatusCode.OK,
  header: input.header,
  body: input.body,
});
