/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type ITodoStatusTransitionInvalidErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type ITodoStatusTransitionInvalidErrorResponseBody = {
  message: "Todo status transition is conflicting with current status";
  code: "TODO_STATUS_TRANSITION_INVALID_ERROR";
  context: {
    todoId: string;
    currentStatus: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
  };
  actualValues: {
    requestedStatus: "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
  };
  expectedValues: {
    allowedStatuses: ("TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED")[];
  };
};

/**
 * Todo status transition is conflicting with current status
 */
export type ITodoStatusTransitionInvalidErrorResponse = ITypedHttpResponse<
  "TodoStatusTransitionInvalidError",
  HttpStatusCode.CONFLICT,
  ITodoStatusTransitionInvalidErrorResponseHeader,
  ITodoStatusTransitionInvalidErrorResponseBody
>;

/**
 * Todo status transition is conflicting with current status
 */
export const createTodoStatusTransitionInvalidErrorResponse = (input: {
  header: ITodoStatusTransitionInvalidErrorResponseHeader;
  body: ITodoStatusTransitionInvalidErrorResponseBody;
}): ITodoStatusTransitionInvalidErrorResponse => ({
  type: "TodoStatusTransitionInvalidError",
  statusCode: HttpStatusCode.CONFLICT,
  header: input.header,
  body: input.body,
});
