/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type ITooManyRequestsErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type ITooManyRequestsErrorResponseBody = {
  message: "Too many requests";
  code: "TOO_MANY_REQUESTS_ERROR";
};

/**
 * Too many requests
 */
export type ITooManyRequestsErrorResponse = ITypedHttpResponse<
  "TooManyRequestsError",
  HttpStatusCode.TOO_MANY_REQUESTS,
  ITooManyRequestsErrorResponseHeader,
  ITooManyRequestsErrorResponseBody
>;

/**
 * Too many requests
 */
export const createTooManyRequestsErrorResponse = (input: {
  header: ITooManyRequestsErrorResponseHeader;
  body: ITooManyRequestsErrorResponseBody;
}): ITooManyRequestsErrorResponse => ({
  type: "TooManyRequestsError",
  statusCode: HttpStatusCode.TOO_MANY_REQUESTS,
  header: input.header,
  body: input.body,
});
