/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

export type IUnsupportedMediaTypeErrorResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IUnsupportedMediaTypeErrorResponseBody = {
  message: "Unsupported media type";
  code: "UNSUPPORTED_MEDIA_TYPE_ERROR";
  context: {
    contentType: string;
  };
  expectedValues: {
    contentTypes: ["application/json"];
  };
};

export type IUnsupportedMediaTypeErrorResponse = ITypedHttpResponse<
  "UnsupportedMediaTypeError",
  HttpStatusCode.UNSUPPORTED_MEDIA_TYPE,
  IUnsupportedMediaTypeErrorResponseHeader,
  IUnsupportedMediaTypeErrorResponseBody
>;

export const createUnsupportedMediaTypeErrorResponse = (input: {
  header: IUnsupportedMediaTypeErrorResponseHeader;
  body: IUnsupportedMediaTypeErrorResponseBody;
}): IUnsupportedMediaTypeErrorResponse => ({
  type: "UnsupportedMediaTypeError",
  statusCode: HttpStatusCode.UNSUPPORTED_MEDIA_TYPE,
  header: input.header,
  body: input.body,
});
