/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import {
  HttpMethod,
  TypeweaverRouter,
  type RequestHandler,
  type TypeweaverRouterOptions,
} from "../../lib/server/index.js";

import type { IAccessTokenRequest } from "../../types/auth/AccessTokenRequest.js";
import { AccessTokenRequestValidator } from "../../types/auth/AccessTokenRequestValidator.js";
import type { AccessTokenResponse } from "../../types/auth/AccessTokenResponse.js";
import { AccessTokenResponseValidator } from "../../types/auth/AccessTokenResponseValidator.js";

import type { IRefreshTokenRequest } from "../../types/auth/RefreshTokenRequest.js";
import { RefreshTokenRequestValidator } from "../../types/auth/RefreshTokenRequestValidator.js";
import type { RefreshTokenResponse } from "../../types/auth/RefreshTokenResponse.js";
import { RefreshTokenResponseValidator } from "../../types/auth/RefreshTokenResponseValidator.js";

export type ServerAuthApiHandler<TState extends Record<string, unknown> = Record<string, unknown>> =
  {
    handleAccessTokenRequest: RequestHandler<IAccessTokenRequest, AccessTokenResponse, TState>;

    handleRefreshTokenRequest: RequestHandler<IRefreshTokenRequest, RefreshTokenResponse, TState>;
  };

export class AuthRouter<
  TState extends Record<string, unknown> = Record<string, unknown>,
> extends TypeweaverRouter<ServerAuthApiHandler<TState>> {
  public constructor(options: TypeweaverRouterOptions<ServerAuthApiHandler<TState>>) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.route(
      "AccessToken",
      HttpMethod.POST,
      "/auth/access-token",
      new AccessTokenRequestValidator(),
      new AccessTokenResponseValidator(),
      this.requestHandlers.handleAccessTokenRequest.bind(this.requestHandlers),
    );

    this.route(
      "RefreshToken",
      HttpMethod.POST,
      "/auth/refresh-token",
      new RefreshTokenRequestValidator(),
      new RefreshTokenResponseValidator(),
      this.requestHandlers.handleRefreshTokenRequest.bind(this.requestHandlers),
    );
  }
}
