/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { IRefreshTokenSuccessResponse } from "../../responses/RefreshTokenSuccessResponse.js";

import type { IForbiddenErrorResponse } from "../../responses/ForbiddenErrorResponse.js";

import type { IInternalServerErrorResponse } from "../../responses/InternalServerErrorResponse.js";

import type { ITooManyRequestsErrorResponse } from "../../responses/TooManyRequestsErrorResponse.js";

import type { IUnauthorizedErrorResponse } from "../../responses/UnauthorizedErrorResponse.js";

import type { IUnsupportedMediaTypeErrorResponse } from "../../responses/UnsupportedMediaTypeErrorResponse.js";

import type { IValidationErrorResponse } from "../../responses/ValidationErrorResponse.js";

export type RefreshTokenResponse =
  | IRefreshTokenSuccessResponse
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse;
