/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../../lib/clients/index.js";
import { getOperationDefinition } from "../../lib/types/index.js";
import { RegisterAccountResponseValidator } from "../../types/account/RegisterAccountResponseValidator.js";
import type {
  IRegisterAccountRequest,
  IRegisterAccountRequestHeader,
  IRegisterAccountRequestBody,
} from "../../types/account/RegisterAccountRequest.js";
import type { RegisterAccountResponse } from "../../types/account/RegisterAccountResponse.js";

const definition = getOperationDefinition(spec, "account", "RegisterAccount");
const responseValidator = new RegisterAccountResponseValidator();

export class RegisterAccountRequestCommand
  extends RequestCommand
  implements IRegisterAccountRequest
{
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.POST;
  public override readonly path = definition.path;

  public override readonly header: IRegisterAccountRequestHeader;
  declare public readonly param: undefined;
  declare public readonly query: undefined;
  public override readonly body: IRegisterAccountRequestBody;

  public constructor(input: Omit<IRegisterAccountRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.body = input.body;
  }

  public processResponse(response: IHttpResponse): RegisterAccountResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
