/**
 * This file was automatically generated by TypeWeaver.
 * DO NOT EDIT. Modify the source contract and generate again.
 *
 * @generated by @rexeus/typeweaver-command
 */

import { runGeneratedCommandCli } from "../lib/command/index.js";
import { RegisterAccountCommand } from "./operations/RegisterAccountCommand.js";
import { AccessTokenCommand } from "./operations/AccessTokenCommand.js";
import { RefreshTokenCommand } from "./operations/RefreshTokenCommand.js";
import { UploadFileCommand } from "./operations/UploadFileCommand.js";
import { DownloadFileContentCommand } from "./operations/DownloadFileContentCommand.js";
import { GetFileMetadataCommand } from "./operations/GetFileMetadataCommand.js";
import { CreateSubTodoCommand } from "./operations/CreateSubTodoCommand.js";
import { CreateTodoCommand } from "./operations/CreateTodoCommand.js";
import { DeleteSubTodoCommand } from "./operations/DeleteSubTodoCommand.js";
import { DeleteTodoCommand } from "./operations/DeleteTodoCommand.js";
import { GetTodoCommand } from "./operations/GetTodoCommand.js";
import { HeadTodoCommand } from "./operations/HeadTodoCommand.js";
import { ListSubTodosCommand } from "./operations/ListSubTodosCommand.js";
import { ListTodosCommand } from "./operations/ListTodosCommand.js";
import { OptionsTodoCommand } from "./operations/OptionsTodoCommand.js";
import { PutTodoCommand } from "./operations/PutTodoCommand.js";
import { QuerySubTodoCommand } from "./operations/QuerySubTodoCommand.js";
import { QueryTodoCommand } from "./operations/QueryTodoCommand.js";
import { UpdateSubTodoCommand } from "./operations/UpdateSubTodoCommand.js";
import { UpdateTodoCommand } from "./operations/UpdateTodoCommand.js";
import { UpdateTodoStatusCommand } from "./operations/UpdateTodoStatusCommand.js";

process.exitCode = await runGeneratedCommandCli({
  programName: "typeweaver-api",
  commands: [
    RegisterAccountCommand,
    AccessTokenCommand,
    RefreshTokenCommand,
    UploadFileCommand,
    DownloadFileContentCommand,
    GetFileMetadataCommand,
    CreateSubTodoCommand,
    CreateTodoCommand,
    DeleteSubTodoCommand,
    DeleteTodoCommand,
    GetTodoCommand,
    HeadTodoCommand,
    ListSubTodosCommand,
    ListTodosCommand,
    OptionsTodoCommand,
    PutTodoCommand,
    QuerySubTodoCommand,
    QueryTodoCommand,
    UpdateSubTodoCommand,
    UpdateTodoCommand,
    UpdateTodoStatusCommand,
  ],
});
