/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { spec } from "../../spec/spec.js";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponseError,
} from "@rexeus/typeweaver-core";
import { RequestCommand } from "../../lib/clients/index.js";
import { getOperationDefinition } from "../../lib/types/index.js";
import { ListTodosResponseValidator } from "../../types/todo/ListTodosResponseValidator.js";
import type {
  IListTodosRequest,
  IListTodosRequestHeader,
  IListTodosRequestQuery,
} from "../../types/todo/ListTodosRequest.js";
import type { ListTodosResponse } from "../../types/todo/ListTodosResponse.js";

const definition = getOperationDefinition(spec, "todo", "ListTodos");
const responseValidator = new ListTodosResponseValidator();

export class ListTodosRequestCommand extends RequestCommand implements IListTodosRequest {
  public override readonly operationId = definition.operationId;
  public override readonly method = definition.method as HttpMethod.GET;
  public override readonly path = definition.path;

  public override readonly header: IListTodosRequestHeader;
  declare public readonly param: undefined;
  public override readonly query: IListTodosRequestQuery;
  declare public readonly body: undefined;

  public constructor(input: Omit<IListTodosRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.query = input.query;
  }

  public processResponse(response: IHttpResponse): ListTodosResponse {
    try {
      return responseValidator.validate(response);
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        throw new UnknownResponseError(response.statusCode, response.header, response.body, error);
      }
      throw error;
    }
  }
}
