/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

export type ApiClientConfigurationField = "baseUrl" | "timeoutMs";

export type ApiClientConfigurationReason =
  | "missing-base-url"
  | "unsupported-base-url-scheme"
  | "invalid-timeout";

export class ApiClientConfigurationError extends Error {
  public override readonly name = "ApiClientConfigurationError";
  public readonly baseUrl: string | undefined;
  public readonly scheme: string | undefined;
  public readonly timeoutMs: number | undefined;

  public constructor(
    public readonly field: ApiClientConfigurationField,
    public readonly reason: ApiClientConfigurationReason,
    options: {
      readonly baseUrl?: string;
      readonly scheme?: string;
      readonly timeoutMs?: number;
    } = {}
  ) {
    super(getApiClientConfigurationMessage(field, reason, options));
    this.baseUrl = options.baseUrl;
    this.scheme = options.scheme;
    this.timeoutMs = options.timeoutMs;
  }
}

const getApiClientConfigurationMessage = (
  field: ApiClientConfigurationField,
  reason: ApiClientConfigurationReason,
  options: {
    readonly baseUrl?: string;
    readonly scheme?: string;
    readonly timeoutMs?: number;
  }
): string => {
  if (field === "baseUrl" && reason === "missing-base-url") {
    return "ApiClient requires a non-empty baseUrl string.";
  }

  if (field === "baseUrl" && reason === "unsupported-base-url-scheme") {
    return `ApiClient baseUrl '${options.baseUrl ?? ""}' uses unsupported scheme '${options.scheme ?? "unknown"}'. Use http://, https://, or a relative base URL.`;
  }

  return `ApiClient timeoutMs must be a positive finite number when provided; received ${String(options.timeoutMs)}.`;
};
