/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { IHttpRequest } from "@rexeus/typeweaver-core";

/**
 * Context object passed through the middleware pipeline and to request handlers.
 *
 * The context carries the current request and a state map
 * that middleware can use to pass data downstream to handlers.
 *
 * All data is in typeweaver's native `IHttpRequest`/`IHttpResponse` format —
 * no framework-specific types leak into middleware or handlers.
 *
 * Responses are returned, not mutated on the context (return-based middleware).
 *
 * @example
 * ```typescript
 * // In middleware: set state and delegate
 * app.use(async (ctx, next) => {
 *   ctx.state.set("userId", "user_123");
 *   return next();
 * });
 *
 * // In handler: read state
 * handleCreateTodo: async (request, ctx) => {
 *   const userId = ctx.state.get("userId") as string;
 *   return { statusCode: 201, body: { id: "1", title: "..." } };
 * };
 * ```
 */
export type ServerContext = {
  /** The incoming HTTP request in typeweaver format. */
  request: IHttpRequest;

  /** Key-value store for sharing data between middleware and handlers. */
  state: Map<string, unknown>;
};
