/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type { IRequestValidator } from "@rexeus/typeweaver-core";
import type { RequestHandler } from "./RequestHandler";
import type {
  RouteDefinition,
  ServerErrorConfig,
  HttpResponseErrorHandler,
  ValidationErrorHandler,
  UnknownErrorHandler,
} from "./Router";

/**
 * Configuration options for TypeweaverServer instances.
 *
 * @template RequestHandlers - Object type containing all handler methods for this server
 */
export type TypeweaverServerOptions<RequestHandlers> = {
  /**
   * Request handler methods for each operation.
   * Each handler receives a validated request and the server context.
   */
  requestHandlers: RequestHandlers;

  /**
   * Enable request validation using generated validators.
   * When false, requests are passed through without validation.
   * @default true
   */
  validateRequests?: boolean;

  /**
   * Configure handling of HttpResponse errors thrown by handlers.
   * - `true`: Use default handler (returns the error as response)
   * - `false`: Let errors propagate
   * - `function`: Use custom error handler
   * @default true
   */
  handleHttpResponseErrors?: HttpResponseErrorHandler | boolean;

  /**
   * Configure handling of request validation errors.
   * - `true`: Use default handler (400 with error details)
   * - `false`: Let errors propagate
   * - `function`: Use custom error handler
   * @default true
   */
  handleValidationErrors?: ValidationErrorHandler | boolean;

  /**
   * Configure handling of unknown errors.
   * - `true`: Use default handler (500 Internal Server Error)
   * - `false`: Let errors propagate
   * - `function`: Use custom error handler
   * @default true
   */
  handleUnknownErrors?: UnknownErrorHandler | boolean;
};

/**
 * Abstract base class for typeweaver-generated server instances.
 *
 * Each generated server (e.g., `AccountServer`, `TodoServer`) extends this class
 * and registers its routes in the constructor via `this.route(...)`.
 *
 * The server does **not** handle HTTP directly — it collects route definitions
 * that are mounted onto a `TypeweaverApp` which provides the routing engine.
 *
 * All types are in typeweaver's native `IHttpRequest`/`IHttpResponse` format.
 * No framework-specific types are involved.
 *
 * @template RequestHandlers - Object type containing typed handler methods
 */
export abstract class TypeweaverServer<RequestHandlers> {
  protected readonly requestHandlers: RequestHandlers;
  private readonly routes: RouteDefinition[] = [];
  private readonly errorConfig: ServerErrorConfig;

  public constructor(options: TypeweaverServerOptions<RequestHandlers>) {
    const {
      requestHandlers,
      validateRequests = true,
      handleHttpResponseErrors = true,
      handleValidationErrors = true,
      handleUnknownErrors = true,
    } = options;

    this.requestHandlers = requestHandlers;

    this.errorConfig = {
      validateRequests,
      handleHttpResponseErrors,
      handleValidationErrors,
      handleUnknownErrors,
    };
  }

  /**
   * Register a route. Called by generated subclasses in their constructor.
   *
   * @param method - HTTP method (GET, POST, PUT, DELETE, etc.)
   * @param path - Path pattern with `:param` placeholders
   * @param validator - Request validator for this operation
   * @param handler - Type-safe request handler
   */
  protected route<TRequest, TResponse>(
    method: string,
    path: string,
    validator: IRequestValidator,
    handler: RequestHandler<any, any>
  ): void {
    this.routes.push({
      method: method.toUpperCase(),
      path,
      validator,
      handler,
      serverConfig: this.errorConfig,
    });
  }

  /**
   * Returns all registered routes. Used by `TypeweaverApp` when mounting this server.
   */
  public getRoutes(): readonly RouteDefinition[] {
    return this.routes;
  }
}
