/**
 * This file was automatically generated by TypeWeaver.
 * DO NOT EDIT. Modify the source contract and generate again.
 *
 * @generated by @rexeus/typeweaver-command
 */

import { HttpMethod } from "@rexeus/typeweaver-core";
import { defineGeneratedCommand } from "../../lib/command/index.js";
import { MetricClient } from "../../metric/MetricClient.js";
import { GetMetricLabelsRequestCommand } from "../../metric/GetMetricLabelsRequestCommand.js";
import { GetMetricLabelsRequestValidator } from "../../metric/GetMetricLabelsRequestValidator.js";

const requestValidator = new GetMetricLabelsRequestValidator();

export const GetMetricLabelsCommand = defineGeneratedCommand({
  name: "get-metric-labels",
  operationId: "GetMetricLabels",
  summary: "Read dynamic metric label records",
  inputs: [
    {
      flag: "path-metric-id",
      key: "metricId",
      target: "path",
      required: true,
      multiple: false,
    },
  ],
  headerDefaults: {},
  security: {
    requirements: [],
    schemes: [],
  },
  hasBody: false,

  execute: async (context) => {
    const validatedRequest = requestValidator.validate({
      method: HttpMethod.GET,
      path: "/metrics/:metricId/labels",
      header: { ...{}, ...context.defaultHeaders, ...context.request.header },
      param: context.request.param,
      query: { ...context.defaultQuery, ...context.request.query },
    });
    const client = new MetricClient({
      baseUrl: context.baseUrl,
      defaultHeaders: context.defaultHeaders,
      defaultQuery: context.defaultQuery,
      signal: context.signal,
    });
    return client.send(
      new GetMetricLabelsRequestCommand({
        header: validatedRequest.header,
        param: validatedRequest.param,
        query: validatedRequest.query,
      }),
    );
  },
});
