/**
 * This file was automatically generated by TypeWeaver.
 * DO NOT EDIT. Modify the source contract and generate again.
 *
 * @generated by @rexeus/typeweaver-command
 */

import { HttpMethod } from "@rexeus/typeweaver-core";
import { defineGeneratedCommand } from "../../lib/command/index.js";
import { TodoClient } from "../../todo/TodoClient.js";
import { UpdateTodoStatusRequestCommand } from "../../todo/UpdateTodoStatusRequestCommand.js";
import { UpdateTodoStatusRequestValidator } from "../../todo/UpdateTodoStatusRequestValidator.js";

const requestValidator = new UpdateTodoStatusRequestValidator();

export const UpdateTodoStatusCommand = defineGeneratedCommand({
  name: "update-todo-status",
  operationId: "UpdateTodoStatus",
  summary: "Update todo status",
  inputs: [
    {
      flag: "path-todo-id",
      key: "todoId",
      target: "path",
      required: true,
      multiple: false,
    },
    {
      flag: "header-x-single-value",
      key: "X-Single-Value",
      target: "header",
      required: false,
      multiple: false,
    },
    {
      flag: "header-x-multi-value",
      key: "X-Multi-Value",
      target: "header",
      required: false,
      multiple: true,
    },
  ],
  headerDefaults: {
    Accept: "application/json",
    "Content-Type": "application/json",
  },
  security: {
    requirements: [["bearerAuth"]],
    schemes: [
      {
        name: "bearerAuth",
        flag: "auth-bearer-auth",
        kind: "http",
        scheme: "bearer",
      },
    ],
  },
  hasBody: true,
  bodyTransport: "json",
  execute: async (context) => {
    const validatedRequest = requestValidator.validate({
      method: HttpMethod.PUT,
      path: "/todos/:todoId/status",
      header: {
        ...{ Accept: "application/json", "Content-Type": "application/json" },
        ...context.defaultHeaders,
        ...context.request.header,
      },
      param: context.request.param,
      body: context.request.body,
    });
    const client = new TodoClient({
      baseUrl: context.baseUrl,
      defaultHeaders: context.defaultHeaders,
      defaultQuery: context.defaultQuery,
      signal: context.signal,
    });
    return client.send(
      new UpdateTodoStatusRequestCommand({
        header: validatedRequest.header,
        param: validatedRequest.param,
        body: validatedRequest.body,
      }),
    );
  },
});
