/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import type {
  ClientHttpHeader,
  ClientHttpParam,
  ClientHttpQuery,
  IHttpHeader,
  IHttpResponse,
} from "@rexeus/typeweaver-core";
import { ApiClientConfigurationError } from "./errors/ApiClientConfigurationError.js";
import { NetworkError } from "./NetworkError.js";
import { PathParameterError } from "./PathParameterError.js";
import { RequestCommand } from "./RequestCommand.js";
import { RequestSerializationError } from "./RequestSerializationError.js";
import { ResponseParseError } from "./ResponseParseError.js";
import type { NetworkErrorCode } from "./NetworkError.js";

/**
 * Configuration options for ApiClient initialization.
 */
export type ApiClientProps = {
  /** Custom fetch function for HTTP requests. Defaults to globalThis.fetch */
  readonly fetchFn?: typeof globalThis.fetch;
  /** Base URL for API requests */
  readonly baseUrl: string;
  /** Headers applied to every request unless the command supplies the same key */
  readonly defaultHeaders?: Readonly<Record<string, string>>;
  /** Query values applied to every request unless the command supplies the same key */
  readonly defaultQuery?: Readonly<Record<string, string>>;
  /** External cancellation signal forwarded to every request */
  readonly signal?: AbortSignal;
  /** Request timeout in milliseconds. When set, requests will be aborted after this duration */
  readonly timeoutMs?: number;
};

type SerializedBody = {
  readonly body: NonNullable<RequestInit["body"]> | undefined;
  readonly isJsonSerialized: boolean;
};

const NETWORK_ERROR_MESSAGES = {
  ECONNREFUSED: "Connection refused",
  ECONNRESET: "Connection reset by peer",
  ENOTFOUND: "DNS lookup failed",
  ETIMEDOUT: "Connection timed out",
} as const satisfies Partial<Record<NetworkErrorCode, string>>;

const PATH_PARAMETER_PATTERN = /:([A-Za-z0-9_]+)/g;
const LEADING_URI_SCHEME_PATTERN = /^[A-Za-z][A-Za-z0-9+.-]*:/;
const DELETE_CONTROL_CHARACTER_CODE = 0x7f;
const SPACE_CHARACTER_CODE = 0x20;

type NetworkFailure = {
  readonly code: NetworkErrorCode;
  readonly description: string;
};

type PathParameters = NonNullable<ClientHttpParam>;

function hasAsciiControlCharacter(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const characterCode = value.charCodeAt(index);
    if (characterCode < SPACE_CHARACTER_CODE || characterCode === DELETE_CONTROL_CHARACTER_CODE) {
      return true;
    }
  }

  return false;
}

function hasErrorName(error: unknown, name: string): boolean {
  return (error instanceof DOMException || error instanceof Error) && error.name === name;
}

function isKnownNetworkErrorCode(code: string): code is keyof typeof NETWORK_ERROR_MESSAGES {
  return Object.hasOwn(NETWORK_ERROR_MESSAGES, code);
}

function getNodeNetworkErrorCode(error: unknown): keyof typeof NETWORK_ERROR_MESSAGES | undefined {
  if (!(error instanceof TypeError)) {
    return undefined;
  }

  const cause = error.cause;
  if (
    typeof cause !== "object" ||
    cause === null ||
    !("code" in cause) ||
    typeof cause.code !== "string"
  ) {
    return undefined;
  }

  return isKnownNetworkErrorCode(cause.code) ? cause.code : undefined;
}

function classifyNetworkFailure(error: unknown): NetworkFailure {
  if (hasErrorName(error, "TimeoutError")) {
    return { code: "TIMEOUT", description: "Request timed out" };
  }

  if (hasErrorName(error, "AbortError")) {
    return { code: "ABORT", description: "Request aborted" };
  }

  const nodeErrorCode = getNodeNetworkErrorCode(error);
  if (nodeErrorCode !== undefined) {
    return {
      code: nodeErrorCode,
      description: NETWORK_ERROR_MESSAGES[nodeErrorCode],
    };
  }

  return {
    code: "UNKNOWN",
    description: error instanceof Error ? error.message : String(error),
  };
}

function getPathParameterNames(path: string): readonly string[] {
  const names: string[] = [];
  for (const match of path.matchAll(PATH_PARAMETER_PATTERN)) {
    const name = match[1];
    if (name !== undefined) {
      names.push(name);
    }
  }
  return names;
}

/**
 * Abstract base class for type-safe API clients.
 *
 * This class provides HTTP request execution with:
 * - Automatic path parameter substitution (`:param` style)
 * - Query string building with array support
 * - Network error handling with specific error messages
 * - Integration with RequestCommand pattern for type safety
 */
export abstract class ApiClient {
  private readonly fetchFn: typeof globalThis.fetch;
  public readonly baseUrl: string;
  private readonly defaultHeaders: Readonly<Record<string, string>>;
  private readonly defaultQuery: Readonly<Record<string, string>>;
  private readonly signal: AbortSignal | undefined;
  private readonly timeoutMs: number | undefined;

  protected constructor(props: ApiClientProps) {
    this.fetchFn = props.fetchFn ?? globalThis.fetch.bind(globalThis);

    if (typeof props.baseUrl !== "string" || props.baseUrl.trim().length === 0) {
      throw new ApiClientConfigurationError("baseUrl", "missing-base-url", {
        baseUrl: props.baseUrl,
      });
    }

    const baseUrlValidationError = this.getBaseUrlValidationError(props.baseUrl);
    if (baseUrlValidationError !== undefined) {
      throw new ApiClientConfigurationError("baseUrl", baseUrlValidationError.reason, {
        baseUrl: props.baseUrl,
        scheme: baseUrlValidationError.scheme,
      });
    }

    this.baseUrl = props.baseUrl;
    this.defaultHeaders = props.defaultHeaders ?? {};
    this.defaultQuery = props.defaultQuery ?? {};
    this.signal = props.signal;

    if (
      props.timeoutMs !== undefined &&
      (props.timeoutMs <= 0 || !Number.isFinite(props.timeoutMs))
    ) {
      throw new ApiClientConfigurationError("timeoutMs", "invalid-timeout", {
        timeoutMs: props.timeoutMs,
      });
    }

    this.timeoutMs = props.timeoutMs;
  }

  protected async execute(request: RequestCommand): Promise<IHttpResponse> {
    const { method, path, header, query, param, body } = request;

    const pathWithParam = this.createPath(path, param);
    const relativeUrl = this.createUrl(pathWithParam, query);
    const fullUrl = this.buildFullUrl(relativeUrl);

    const serializedBody = this.serializeBody(body);
    const headers = this.createRequestHeaders(
      this.mergeRequestHeaders(this.flattenHeaders(header)),
      serializedBody.isJsonSerialized,
    );

    const response = await this.performFetch(method, fullUrl, {
      method,
      headers,
      body: serializedBody.body,
      signal: this.createRequestSignal(),
    });

    return await this.createResponse(response, method, fullUrl);
  }

  private async performFetch(method: string, url: string, init: RequestInit): Promise<Response> {
    try {
      return await this.fetchFn(url, init);
    } catch (error) {
      throw this.createNetworkError(error, method, url);
    }
  }

  private async createResponse(
    response: Response,
    method: string,
    url: string,
  ): Promise<IHttpResponse> {
    const header: IHttpHeader = {};
    response.headers.forEach((value, key) => {
      header[key] = value;
    });

    if (typeof response.headers.getSetCookie === "function") {
      const cookies = response.headers.getSetCookie();
      if (cookies.length > 0) {
        header["set-cookie"] = cookies;
      }
    }

    const body = await this.parseResponseBody(response, method, url);

    return {
      body,
      header,
      statusCode: response.status,
    };
  }

  private async readBody<T>(
    read: () => Promise<T>,
    response: Response,
    method: string,
    url: string,
  ): Promise<T> {
    try {
      return await read();
    } catch (error) {
      throw new ResponseParseError(
        `Failed to read response body (${method} ${url})`,
        response.status,
        "",
        { cause: error instanceof Error ? error : undefined },
      );
    }
  }

  private async parseResponseBody(
    response: Response,
    method: string,
    url: string,
  ): Promise<unknown> {
    if (response.status === 204 || response.status === 304) {
      return undefined;
    }

    const contentType = response.headers.get("content-type");

    if (this.isJsonContentType(contentType)) {
      const text = await this.readBody(() => response.text(), response, method, url);
      if (!text) return undefined;
      try {
        return JSON.parse(text);
      } catch (parseError) {
        throw new ResponseParseError(
          "Failed to parse JSON response",
          response.status,
          text.slice(0, 200),
          {
            cause: parseError instanceof Error ? parseError : undefined,
          },
        );
      }
    }

    if (this.isTextContentType(contentType) || !contentType) {
      const text = await this.readBody(() => response.text(), response, method, url);
      if (!text) return undefined;
      return text;
    }

    return await this.readBody(() => response.arrayBuffer(), response, method, url);
  }

  private isTextContentType(contentType: string | null): boolean {
    if (!contentType) return false;
    return contentType.toLowerCase().includes("text/");
  }

  private createNetworkError(error: unknown, method: string, url: string): NetworkError {
    const failure = classifyNetworkFailure(error);
    const context = `(${method} ${url})`;

    return new NetworkError(`Network error: ${failure.description} ${context}`, {
      cause: error,
      code: failure.code,
      method,
      url,
    });
  }

  private flattenHeaders(header: ClientHttpHeader): Record<string, string> | undefined {
    if (header === undefined) return undefined;

    const flattened: Record<string, string> = {};
    for (const [key, value] of Object.entries(header)) {
      if (value === undefined) {
        continue;
      }
      flattened[key] = Array.isArray(value)
        ? value.map((item) => this.serializeHttpScalar(item, "header", key)).join(", ")
        : this.serializeHttpScalar(value, "header", key);
    }
    return flattened;
  }

  private createRequestHeaders(
    headers: Record<string, string> | undefined,
    isJsonSerialized: boolean,
  ): Record<string, string> | undefined {
    if (!isJsonSerialized) return headers;

    const requestHeaders = headers ? { ...headers } : {};
    if (!this.hasContentTypeHeader(requestHeaders)) {
      requestHeaders["Content-Type"] = "application/json";
    }
    return requestHeaders;
  }

  private mergeRequestHeaders(
    headers: Record<string, string> | undefined,
  ): Record<string, string> | undefined {
    const hasDefaults = Object.keys(this.defaultHeaders).length > 0;
    if (!hasDefaults) return headers;
    const requestHeaderNames = new Set(
      Object.keys(headers ?? {}).map((headerName) => headerName.toLowerCase()),
    );
    const applicableDefaults = Object.fromEntries(
      Object.entries(this.defaultHeaders).filter(
        ([headerName]) => !requestHeaderNames.has(headerName.toLowerCase()),
      ),
    );
    return { ...applicableDefaults, ...headers };
  }

  private createRequestSignal(): AbortSignal | undefined {
    if (this.signal === undefined) {
      return this.timeoutMs === undefined ? undefined : AbortSignal.timeout(this.timeoutMs);
    }
    if (this.timeoutMs === undefined) {
      return this.signal;
    }
    return AbortSignal.any([this.signal, AbortSignal.timeout(this.timeoutMs)]);
  }

  private hasContentTypeHeader(headers: Record<string, string>): boolean {
    return Object.keys(headers).some((key) => key.toLowerCase() === "content-type");
  }

  private serializeBody(body: unknown): SerializedBody {
    if (body === null || body === undefined) {
      return { body: undefined, isJsonSerialized: false };
    }
    if (typeof body === "string") {
      return { body, isJsonSerialized: false };
    }
    if (this.isNativeBody(body))
      return {
        body: body as NonNullable<RequestInit["body"]>,
        isJsonSerialized: false,
      };
    return { body: JSON.stringify(body), isJsonSerialized: true };
  }

  private isNativeBody(body: unknown): boolean {
    return (
      body instanceof Blob ||
      body instanceof ArrayBuffer ||
      body instanceof FormData ||
      body instanceof URLSearchParams ||
      body instanceof ReadableStream ||
      ArrayBuffer.isView(body)
    );
  }

  private isJsonContentType(contentType: string | null): boolean {
    if (!contentType) return false;
    const normalizedContentType = contentType.toLowerCase();
    return (
      normalizedContentType.includes("application/json") || normalizedContentType.includes("+json")
    );
  }

  private buildFullUrl(relativePath: string): string {
    const base = this.baseUrl.endsWith("/") ? this.baseUrl.slice(0, -1) : this.baseUrl;
    const path = relativePath.startsWith("/") ? relativePath : `/${relativePath}`;
    return `${base}${path}`;
  }

  private getBaseUrlValidationError(baseUrl: string):
    | {
        readonly reason: "malformed-base-url" | "unsupported-base-url-scheme";
        readonly scheme?: string;
      }
    | undefined {
    const scheme = this.getBaseUrlScheme(baseUrl);

    if (hasAsciiControlCharacter(baseUrl)) {
      return { reason: "malformed-base-url", scheme };
    }

    const normalizedBaseUrl = baseUrl.trim();
    if (!LEADING_URI_SCHEME_PATTERN.test(normalizedBaseUrl)) {
      return undefined;
    }

    if (!URL.canParse(normalizedBaseUrl)) {
      return { reason: "malformed-base-url", scheme };
    }

    const url = new URL(normalizedBaseUrl);
    if (url.protocol === "http:" || url.protocol === "https:") {
      return undefined;
    }

    return { reason: "unsupported-base-url-scheme", scheme };
  }

  private getBaseUrlScheme(baseUrl: string): string | undefined {
    const normalizedBaseUrl = baseUrl.trim();
    const schemeMatch = LEADING_URI_SCHEME_PATTERN.exec(normalizedBaseUrl);

    if (schemeMatch?.[0] === undefined) {
      return undefined;
    }

    return schemeMatch[0].slice(0, -1).toLowerCase();
  }

  private createPath(path: string, param?: ClientHttpParam): string {
    const pathParameterSet = new Set(getPathParameterNames(path));
    const parameters: PathParameters = param ?? {};

    this.assertNoUnexpectedPathParameters(path, pathParameterSet, parameters);
    this.assertNoMissingPathParameters(path, pathParameterSet, parameters);

    return path.replace(PATH_PARAMETER_PATTERN, (_placeholder, key: string) =>
      this.encodePathParameter(key, parameters[key]!, path),
    );
  }

  private assertNoUnexpectedPathParameters(
    path: string,
    pathParameterNames: ReadonlySet<string>,
    parameters: PathParameters,
  ): void {
    for (const key of Object.keys(parameters)) {
      if (!pathParameterNames.has(key)) {
        throw new PathParameterError(
          `Path parameter '${key}' is not found in path '${path}'`,
          key,
          path,
        );
      }
    }
  }

  private assertNoMissingPathParameters(
    path: string,
    pathParameterNames: ReadonlySet<string>,
    parameters: PathParameters,
  ): void {
    for (const key of pathParameterNames) {
      if (!Object.hasOwn(parameters, key) || parameters[key] === undefined) {
        throw new PathParameterError(
          `Path parameter '${key}' is missing for path '${path}'`,
          key,
          path,
        );
      }
    }
  }

  private encodePathParameter(key: string, value: unknown, path: string): string {
    const serialized = this.serializeHttpScalar(value, "path", key);
    if (serialized === "." || serialized === "..") {
      throw new PathParameterError(
        `Path parameter '${key}' cannot be a URL dot-segment`,
        key,
        path,
      );
    }

    return encodeURIComponent(serialized);
  }

  private createUrl(path: string, query?: ClientHttpQuery): string {
    const normalizedPath = path.startsWith("/") ? path : `/${path}`;
    const queryString = this.buildQueryString(query);
    return queryString ? `${normalizedPath}?${queryString}` : normalizedPath;
  }

  private buildQueryString(query?: ClientHttpQuery): string {
    const hasDefaults = Object.keys(this.defaultQuery).length > 0;
    if (!query && !hasDefaults) {
      return "";
    }

    const params = new URLSearchParams();
    const mergedQuery: ClientHttpQuery = {
      ...this.defaultQuery,
      ...query,
    };
    for (const [key, value] of Object.entries(mergedQuery)) {
      if (value === undefined) {
        continue;
      }
      if (!Array.isArray(value)) {
        params.append(key, this.serializeHttpScalar(value, "query", key));
        continue;
      }
      for (const item of value) {
        if (item !== undefined) {
          params.append(key, this.serializeHttpScalar(item, "query", key));
        }
      }
    }
    return params.toString();
  }

  private serializeHttpScalar(
    value: unknown,
    location: "header" | "path" | "query",
    key: string,
  ): string {
    if (value === null) {
      throw new RequestSerializationError(location, key, value, "null-value");
    }
    if (Array.isArray(value)) {
      throw new RequestSerializationError(location, key, value, "nested-array");
    }
    if (value instanceof Date) {
      if (Number.isNaN(value.getTime())) {
        throw new RequestSerializationError(location, key, value, "invalid-date");
      }
      return value.toISOString();
    }

    switch (typeof value) {
      case "string":
        return value;
      case "number":
        if (!Number.isFinite(value)) {
          throw new RequestSerializationError(location, key, value, "non-finite-number");
        }
        return String(value);
      case "boolean":
      case "bigint":
        return String(value);
      default:
        throw new RequestSerializationError(location, key, value, "unsupported-type");
    }
  }
}
