import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import path from "node:path";
import {
  assertDoctorInFixture,
  assertPhantomImportsUnavailable,
  typecheckAndRunApp,
} from "./checks.mjs";
import {
  allProjectionDependencies,
  minimalDependencies,
  packedDependenciesFor,
  writeAppModule,
  writeConsumerManifest,
  writeConsumerSpec,
  writeEffectConsumerSource,
  writeFixtureManifest,
  writeGeneratedCommandTsconfig,
  writePlainProjectionsConfig,
  writeRuntimeConfig,
  writeStrictNpmrc,
  ZOD_VERSION,
} from "./fixtures.mjs";
import {
  assertGeneratorEffectPeerContract,
  assertNativeEffectIdentities,
  assertPackedPackages,
  assertPlatformNodeSharedIdentity,
  assertSingleEffectIdentity,
} from "./graph.mjs";
import {
  contract,
  installFixture,
  readJson,
  rootPackage,
  run,
  runExpectFailure,
  runNode,
  writeJson,
} from "./runtime.mjs";
import {
  assertNoForbiddenModuleSpecifiers,
  assertProjectionOutputsExist,
} from "./scanner.mjs";

/** @typedef {import("../tooling-types.mjs").PublicPackage} PublicPackage */

/** @typedef {{ archives: ReadonlyMap<string, string>, packages: readonly PublicPackage[] }} PackedMatrix */
/** @typedef {{ archives: ReadonlyMap<string, string>, effectVersion: string, packages: readonly PublicPackage[] }} ConsumerMatrix */
/** @typedef {ConsumerMatrix & { fixtureRoot: string }} ScaffoldMatrix */

/**
 * @param {string} fixtureRoot
 * @returns {string}
 */
const addPluginScaffold = fixtureRoot => {
  const scaffoldRoot = path.join(fixtureRoot, "scaffolded-plugin");
  run({
    args: [
      "exec",
      "typeweaver",
      "add",
      "plugin",
      "--name",
      "packed-starter",
      "--target",
      scaffoldRoot,
    ],
    cwd: fixtureRoot,
  });
  return scaffoldRoot;
};

/**
 * @param {{ archives: ReadonlyMap<string, string>, packages: readonly PublicPackage[], scaffoldRoot: string }} options
 * @returns {void}
 */
const configureScaffoldedPlugin = ({ archives, packages, scaffoldRoot }) => {
  const scaffoldManifestPath = path.join(scaffoldRoot, "package.json");
  const scaffoldManifest = readJson(scaffoldManifestPath);
  const packedDependencies = packedDependenciesFor({ archives, packages });
  assert.equal(
    scaffoldManifest.peerDependencies?.["effect"],
    contract.peerRange
  );
  assert(
    !/workspace:|catalog:/.test(JSON.stringify(scaffoldManifest)),
    "plugin scaffold retained a workspace-only dependency specifier"
  );
  writeJson(scaffoldManifestPath, {
    ...scaffoldManifest,
    packageManager: rootPackage.packageManager,
    pnpm: {
      overrides: packedDependencies,
    },
  });
  writeStrictNpmrc(scaffoldRoot);
};

/**
 * @param {string} scaffoldRoot
 * @returns {void}
 */
const assertScaffoldGeneratedOutput = scaffoldRoot => {
  assert.equal(
    readFileSync(
      path.join(
        scaffoldRoot,
        "test",
        "fixture",
        "generated",
        "packed-starter",
        "generated.txt"
      ),
      "utf8"
    ),
    "generated by packed-starter\n"
  );
};

/**
 * @param {ScaffoldMatrix} options
 * @returns {void}
 */
export const verifyScaffoldedPlugin = ({
  archives,
  effectVersion,
  fixtureRoot,
  packages,
}) => {
  const scaffoldRoot = addPluginScaffold(fixtureRoot);
  configureScaffoldedPlugin({ archives, packages, scaffoldRoot });
  installFixture(scaffoldRoot);
  assertPackedPackages({ fixtureRoot: scaffoldRoot, packages });
  assertGeneratorEffectPeerContract(scaffoldRoot);
  assertSingleEffectIdentity({
    effectVersion,
    fixtureRoot: scaffoldRoot,
    includeCompatPlugin: false,
    packages,
  });
  run({ args: ["run", "check"], cwd: scaffoldRoot });
  assertScaffoldGeneratedOutput(scaffoldRoot);
};

/**
 * @param {{ fixtureRoot: string, outputRoot: string }} options
 * @returns {void}
 */
export const verifyGeneratedCommandConsumer = ({ fixtureRoot, outputRoot }) => {
  writeEffectConsumerSource(outputRoot);
  const { generatedTsconfig, generatedDist } = writeGeneratedCommandTsconfig({
    fixtureRoot,
    outputRoot,
  });
  run({
    args: ["exec", "tsc", "--project", generatedTsconfig],
    cwd: fixtureRoot,
  });
  assert.equal(
    runNode({
      args: [
        "--input-type=module",
        "--eval",
        `await import(${JSON.stringify(path.join(generatedDist, "index.js"))}); if (process.exitCode !== undefined) throw new Error("generated barrel executed the command CLI"); process.stdout.write("generated-import-ok\\\\n");`,
      ],
      cwd: fixtureRoot,
    }),
    "generated-import-ok\\n"
  );
  assert.match(
    runNode({
      args: [path.join(generatedDist, "command", "cli.mjs"), "--help"],
      cwd: fixtureRoot,
    }),
    /ping\s+Ping/
  );
  assert.equal(
    runNode({
      args: [path.join(generatedDist, "effect-consumer.js")],
      cwd: fixtureRoot,
    }),
    "effect-adapter-ok\\n"
  );
};

/**
 * @param {string} fixtureRoot
 * @returns {void}
 */
const assertProgrammaticImports = fixtureRoot => {
  assert.equal(
    runNode({
      args: [
        "--input-type=module",
        "--eval",
        'const api = await import("@rexeus/typeweaver"); if (typeof api.Generator?.generate !== "function" || typeof api.effectRuntime?.runPromise !== "function") throw new Error("missing programmatic API"); if (process.exitCode !== undefined) throw new Error("package import changed process.exitCode"); process.stdout.write("import-ok\\n");',
      ],
      cwd: fixtureRoot,
    }),
    "import-ok\n"
  );
  assert.equal(
    runNode({
      args: [
        "--eval",
        'const api = require("@rexeus/typeweaver"); if (typeof api.Generator?.generate !== "function" || typeof api.effectRuntime?.runPromise !== "function") throw new Error("missing programmatic API"); if (process.exitCode !== undefined) throw new Error("package require changed process.exitCode"); process.stdout.write("require-ok\\n");',
      ],
      cwd: fixtureRoot,
    }),
    "require-ok\n"
  );
};

/**
 * @param {ConsumerMatrix & { matrixRoot: string }} options
 * @returns {void}
 */
export const verifySupportedConsumer = ({
  archives,
  effectVersion,
  matrixRoot,
  packages,
}) => {
  const fixtureRoot = path.join(matrixRoot, `effect-${effectVersion}`);
  mkdirSync(fixtureRoot, { recursive: true });
  writeConsumerManifest({
    archives,
    effectVersion,
    fixtureRoot,
    packages,
  });
  installFixture(fixtureRoot);
  assertPackedPackages({ fixtureRoot, packages });
  assertGeneratorEffectPeerContract(fixtureRoot);
  assertPlatformNodeSharedIdentity({ fixtureRoot });
  assertSingleEffectIdentity({ effectVersion, fixtureRoot, packages });
  run({
    args: ["exec", "tsc", "--project", "tsconfig.json"],
    cwd: fixtureRoot,
  });
  assertProgrammaticImports(fixtureRoot);

  const { configPath, outputRoot } = writeRuntimeConfig(fixtureRoot);
  const output = run({
    args: [
      "exec",
      "typeweaver",
      "generate",
      "--config",
      configPath,
      "--no-format",
    ],
    cwd: fixtureRoot,
  });
  assert.match(output, /Successfully loaded 5 plugin/);
  assert.equal(
    readFileSync(path.join(outputRoot, "packed-compat", "result.txt"), "utf8"),
    "packed-consumer-ok\n"
  );
  verifyGeneratedCommandConsumer({ fixtureRoot, outputRoot });
  verifyScaffoldedPlugin({
    archives,
    effectVersion,
    fixtureRoot,
    packages,
  });
};

/**
 * @param {{ archives: ReadonlyMap<string, string>, matrixRoot: string, packages: readonly PublicPackage[] }} options
 * @returns {void}
 */
export const verifyDuplicateGuard = ({ archives, matrixRoot, packages }) => {
  const fixtureRoot = path.join(matrixRoot, "duplicate-effect");
  mkdirSync(fixtureRoot, { recursive: true });
  writeConsumerManifest({
    archives,
    effectVersion: contract.runtimeVersion,
    fixtureRoot,
    packages,
    pluginEffectVersion: "3.21.2",
  });
  installFixture(fixtureRoot);
  assert.throws(
    () =>
      assertSingleEffectIdentity({
        effectVersion: contract.runtimeVersion,
        fixtureRoot,
        packages,
      }),
    /multiple Effect identities detected/
  );
};

// Direct deps are only the packed CLI and core, the exact RC, and the tooling
// and third-party runtime deps the fixture truthfully needs. Hono is absent to
// prove its peer is optional for a CLI-only consumer under strict peers.
/**
 * @param {ConsumerMatrix & { matrixRoot: string }} options
 * @returns {void}
 */
export const verifyMinimalStrictInstall = ({
  archives,
  effectVersion,
  matrixRoot,
  packages,
}) => {
  const fixtureRoot = path.join(matrixRoot, "effect-4-minimal-strict");
  mkdirSync(fixtureRoot, { recursive: true });
  writeFixtureManifest({
    dependencies: minimalDependencies({ archives, effectVersion, packages }),
    fixtureRoot,
    name: "typeweaver-effect-4-minimal-strict",
    overrides: packedDependenciesFor({ archives, packages }),
  });
  writeStrictNpmrc(fixtureRoot);
  installFixture(fixtureRoot);
  assertPackedPackages({ fixtureRoot, packages });
  assert(
    !existsSync(path.join(fixtureRoot, "node_modules", "hono")),
    "the minimal strict fixture unexpectedly installed hono"
  );
  assertNativeEffectIdentities({ effectVersion, fixtureRoot, packages });
};

// Direct deps add hono because all advertised plain projections are exercised
// here; the generated Hono output imports it, so it is a truthful runtime dep.
/**
 * @param {ConsumerMatrix & { matrixRoot: string }} options
 * @returns {void}
 */
export const verifyAllPlainProjectionsConsumer = ({
  archives,
  effectVersion,
  matrixRoot,
  packages,
}) => {
  const fixtureRoot = path.join(matrixRoot, "effect-4-all-plain");
  mkdirSync(fixtureRoot, { recursive: true });
  writeFixtureManifest({
    dependencies: allProjectionDependencies({
      archives,
      effectVersion,
      packages,
    }),
    fixtureRoot,
    name: "typeweaver-effect-4-all-plain",
    overrides: packedDependenciesFor({ archives, packages }),
  });
  writeStrictNpmrc(fixtureRoot);
  writeConsumerSpec(fixtureRoot);
  installFixture(fixtureRoot);
  assertPackedPackages({ fixtureRoot, packages });
  assertGeneratorEffectPeerContract(fixtureRoot);
  assertNativeEffectIdentities({ effectVersion, fixtureRoot, packages });
  assertPhantomImportsUnavailable(fixtureRoot);
  const { configPath, outputRoot } = writePlainProjectionsConfig(fixtureRoot);
  const generated = run({
    args: [
      "exec",
      "typeweaver",
      "generate",
      "--config",
      configPath,
      "--no-format",
    ],
    cwd: fixtureRoot,
  });
  assert.match(generated, /Successfully loaded/u);
  assertProjectionOutputsExist(outputRoot);
  assertNoForbiddenModuleSpecifiers(outputRoot);
  writeAppModule(fixtureRoot);
  typecheckAndRunApp({ fixtureRoot, outputRoot });
  assertDoctorInFixture(fixtureRoot);
};

/**
 * @param {Omit<ConsumerMatrix, "effectVersion"> & { matrixRoot: string }} options
 * @returns {void}
 */
export const verifyNativeEffectStrictPeerNegative = ({
  archives,
  matrixRoot,
  packages,
}) => {
  const incompatibleEffectVersion = "4.0.0-rc.115";
  assert.notEqual(
    incompatibleEffectVersion,
    contract.runtimeVersion,
    "strict-peer negative Effect version must differ from the runtime contract"
  );
  const fixtureRoot = path.join(
    matrixRoot,
    "native-effect-strict-peer-negative"
  );
  mkdirSync(fixtureRoot, { recursive: true });
  const packedDependencies = packedDependenciesFor({ archives, packages });
  writeFixtureManifest({
    fixtureRoot,
    name: "typeweaver-native-effect-strict-peer-negative",
    overrides: packedDependencies,
    dependencies: {
      "@rexeus/typeweaver-core": packedDependencies["@rexeus/typeweaver-core"],
      "@rexeus/typeweaver-effect":
        packedDependencies["@rexeus/typeweaver-effect"],
      "@rexeus/typeweaver-gen": packedDependencies["@rexeus/typeweaver-gen"],
      "@rexeus/typeweaver-server":
        packedDependencies["@rexeus/typeweaver-server"],
      effect: incompatibleEffectVersion,
      zod: ZOD_VERSION,
    },
  });
  writeStrictNpmrc(fixtureRoot);
  const output = runExpectFailure({
    args: ["install", "--ignore-scripts"],
    cwd: fixtureRoot,
  });
  assert.match(
    output,
    new RegExp(`effect@${contract.runtimeVersion}`),
    `strict-peer install did not fail on the exact native Effect peer:\n${output}`
  );
  assert.match(
    output,
    /unmet peer|PEER_DEP_ISSUES/iu,
    `strict-peer install did not fail as a peer conflict:\n${output}`
  );
};

/**
 * @param {string} peerRange
 * @returns {string}
 */
export const peerVersion = peerRange => {
  assert(
    peerRange === contract.runtimeVersion,
    `unsupported Effect peer contract: ${peerRange}`
  );
  return peerRange;
};
