/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import definition from "../definition/auth/AccessTokenDefinition";
import {
  HttpMethod,
  type IHttpResponse,
  ResponseValidationError,
  UnknownResponse,
} from "@rexeus/typeweaver-core";
import { RequestCommand, type ProcessResponseOptions } from "../lib/clients";
import { AccessTokenResponseValidator } from "./AccessTokenResponseValidator";
import type {
  IAccessTokenRequest,
  IAccessTokenRequestHeader,
  IAccessTokenRequestBody,
  SuccessfulAccessTokenResponse,
} from "./AccessTokenRequest";

import { AccessTokenSuccessResponse } from "./AccessTokenResponse";

export class AccessTokenRequestCommand extends RequestCommand implements IAccessTokenRequest {
  public override readonly method = definition.method as HttpMethod.POST;
  public override readonly path = definition.path;

  public override readonly header: IAccessTokenRequestHeader;
  declare public readonly param: undefined;
  declare public readonly query: undefined;
  public override readonly body: IAccessTokenRequestBody;

  private readonly responseValidator: AccessTokenResponseValidator;

  public constructor(input: Omit<IAccessTokenRequest, "method" | "path">) {
    super();

    this.header = input.header;

    this.body = input.body;

    this.responseValidator = new AccessTokenResponseValidator();
  }

  public processResponse(
    response: IHttpResponse,
    options: ProcessResponseOptions,
  ): SuccessfulAccessTokenResponse {
    try {
      const result = this.responseValidator.validate(response);

      if (result instanceof AccessTokenSuccessResponse) {
        return result;
      }

      throw result;
    } catch (error) {
      if (error instanceof ResponseValidationError) {
        const unknownResponse = new UnknownResponse(
          response.statusCode,
          response.header,
          response.body,
          error,
        );

        if (
          options.unknownResponseHandling === "passthrough" &&
          options.isSuccessStatusCode(response.statusCode)
        ) {
          return unknownResponse as any;
        }

        throw unknownResponse;
      }
      throw error;
    }
  }
}
