/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpStatusCode } from "@rexeus/typeweaver-core";
import type { ITypedHttpResponse } from "@rexeus/typeweaver-core";

import type { IForbiddenErrorResponse } from "../shared/ForbiddenErrorResponse";

import type { IInternalServerErrorResponse } from "../shared/InternalServerErrorResponse";

import type { ITooManyRequestsErrorResponse } from "../shared/TooManyRequestsErrorResponse";

import type { IUnauthorizedErrorResponse } from "../shared/UnauthorizedErrorResponse";

import type { IUnsupportedMediaTypeErrorResponse } from "../shared/UnsupportedMediaTypeErrorResponse";

import type { IValidationErrorResponse } from "../shared/ValidationErrorResponse";

export type IAccessTokenSuccessResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IAccessTokenSuccessResponseBody = {
  accessToken: string;
  refreshToken: string;
};

export type IAccessTokenSuccessResponse = ITypedHttpResponse<
  "AccessTokenSuccess",
  HttpStatusCode.OK,
  IAccessTokenSuccessResponseHeader,
  IAccessTokenSuccessResponseBody
>;

export const createAccessTokenSuccessResponse = (
  input: Omit<IAccessTokenSuccessResponse, "type" | "statusCode">,
): IAccessTokenSuccessResponse => ({
  ...input,
  type: "AccessTokenSuccess",
  statusCode: HttpStatusCode.OK,
});

export type AccessTokenResponse =
  | IAccessTokenSuccessResponse
  | IForbiddenErrorResponse
  | IInternalServerErrorResponse
  | ITooManyRequestsErrorResponse
  | IUnauthorizedErrorResponse
  | IUnsupportedMediaTypeErrorResponse
  | IValidationErrorResponse;
