/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import {
  HttpMethod,
  TypeweaverRouter,
  type RequestHandler,
  type TypeweaverRouterOptions,
} from "./../lib/server";

import type { IAccessTokenRequest } from "./AccessTokenRequest";
import { AccessTokenRequestValidator } from "./AccessTokenRequestValidator";
import type { AccessTokenResponse } from "./AccessTokenResponse";
import { AccessTokenResponseValidator } from "./AccessTokenResponseValidator";

import type { IRefreshTokenRequest } from "./RefreshTokenRequest";
import { RefreshTokenRequestValidator } from "./RefreshTokenRequestValidator";
import type { RefreshTokenResponse } from "./RefreshTokenResponse";
import { RefreshTokenResponseValidator } from "./RefreshTokenResponseValidator";

export type ServerAuthApiHandler<TState extends Record<string, unknown> = Record<string, unknown>> =
  {
    handleAccessTokenRequest: RequestHandler<IAccessTokenRequest, AccessTokenResponse, TState>;

    handleRefreshTokenRequest: RequestHandler<IRefreshTokenRequest, RefreshTokenResponse, TState>;
  };

export class AuthRouter<
  TState extends Record<string, unknown> = Record<string, unknown>,
> extends TypeweaverRouter<ServerAuthApiHandler<TState>> {
  public constructor(options: TypeweaverRouterOptions<ServerAuthApiHandler<TState>>) {
    super(options);
    this.setupRoutes();
  }

  protected setupRoutes(): void {
    this.route(
      "AccessToken",
      HttpMethod.POST,
      "/auth/access-token",
      new AccessTokenRequestValidator(),
      new AccessTokenResponseValidator(),
      this.requestHandlers.handleAccessTokenRequest.bind(this.requestHandlers),
    );

    this.route(
      "RefreshToken",
      HttpMethod.POST,
      "/auth/refresh-token",
      new RefreshTokenRequestValidator(),
      new RefreshTokenResponseValidator(),
      this.requestHandlers.handleRefreshTokenRequest.bind(this.requestHandlers),
    );
  }
}
