/**
 * This file was automatically generated by TypeWeaver.
 * DO NOT EDIT. Modify the source contract and generate again.
 *
 * @generated by @rexeus/typeweaver-effect
 */

import type {
  EffectHandlerErrorMapper,
  EffectHandlerRuntime,
  EffectRequestHandler,
} from "@rexeus/typeweaver-effect";
import type { ServerContext } from "../lib/server/index.js";
import type { ServerAuthApiHandler } from "./AuthRouter.js";
import type { IAccessTokenRequest } from "./AccessTokenRequest.js";
import type { AccessTokenResponse } from "./AccessTokenResponse.js";
import type { IRefreshTokenRequest } from "./RefreshTokenRequest.js";
import type { RefreshTokenResponse } from "./RefreshTokenResponse.js";

export type EffectAuthApiHandler<
  TError,
  TRequirements,
  TState extends Record<string, unknown> = Record<string, unknown>,
> = {
  readonly handleAccessTokenRequest: EffectRequestHandler<
    IAccessTokenRequest,
    AccessTokenResponse,
    TError,
    TRequirements,
    ServerContext<TState>
  >;
  readonly handleRefreshTokenRequest: EffectRequestHandler<
    IRefreshTokenRequest,
    RefreshTokenResponse,
    TError,
    TRequirements,
    ServerContext<TState>
  >;
};

export type EffectAuthErrorMappers<
  TError,
  TState extends Record<string, unknown> = Record<string, unknown>,
> = {
  readonly handleAccessTokenRequest: EffectHandlerErrorMapper<
    TError,
    AccessTokenResponse,
    ServerContext<TState>
  >;
  readonly handleRefreshTokenRequest: EffectHandlerErrorMapper<
    TError,
    RefreshTokenResponse,
    ServerContext<TState>
  >;
};

export const adaptAuthEffectHandlers = <
  TError,
  TRequirements,
  TState extends Record<string, unknown> = Record<string, unknown>,
>(
  runtime: EffectHandlerRuntime<TRequirements>,
  handlers: EffectAuthApiHandler<TError, TRequirements, TState>,
  errorMappers: EffectAuthErrorMappers<TError, TState>,
): ServerAuthApiHandler<TState> => ({
  handleAccessTokenRequest: (request, context) =>
    runtime.run(
      handlers.handleAccessTokenRequest,
      request,
      context,
      errorMappers.handleAccessTokenRequest,
    ),
  handleRefreshTokenRequest: (request, context) =>
    runtime.run(
      handlers.handleRefreshTokenRequest,
      request,
      context,
      errorMappers.handleRefreshTokenRequest,
    ),
});
