/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod, type IHttpRequest, type IRawHttpRequestFor } from "@rexeus/typeweaver-core";

export type IRefreshTokenRequestHeader = Readonly<{
  "Content-Type": "application/json";
  Accept: "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
}>;

export type IRefreshTokenRequestBody = {
  refreshToken: string;
};

/**
 * Refresh access token by refresh token
 */
export type IRefreshTokenRequest = IHttpRequest<
  IRefreshTokenRequestHeader,
  undefined,
  undefined,
  IRefreshTokenRequestBody
> & {
  readonly path: string;
  readonly method: HttpMethod.POST;
  readonly header: IRefreshTokenRequestHeader;

  readonly body: IRefreshTokenRequestBody;
};

export type IRawRefreshTokenRequest = IRawHttpRequestFor<IRefreshTokenRequest>;
