/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpMethod } from "@rexeus/typeweaver-core";

export type IRefreshTokenRequestHeader = {
  "Content-Type": "application/json";
  Accept: "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IRefreshTokenRequestBody = {
  refreshToken: string;
};

/**
 * Refresh access token by refresh token
 */
export type IRefreshTokenRequest = {
  path: string;
  method: HttpMethod.POST;
  header: IRefreshTokenRequestHeader;

  body: IRefreshTokenRequestBody;
};
