/* eslint-disable */
/**
 * This file was automatically generated by typeweaver.
 * DO NOT EDIT. Instead, modify the source definition file and generate again.
 *
 * @generated by @rexeus/typeweaver
 */

import { HttpResponse, HttpStatusCode } from "@rexeus/typeweaver-core";

import type { ISharedErrorResponse, SharedErrorResponse } from "../shared/SharedErrorResponses";

export type IRefreshTokenSuccessResponseHeader = {
  "Content-Type": "application/json";
  "X-Single-Value"?: string | undefined;
  "X-Multi-Value"?: string[] | undefined;
};

export type IRefreshTokenSuccessResponseBody = {
  accessToken: string;
  refreshToken: string;
};

export type IRefreshTokenSuccessResponse = {
  statusCode: HttpStatusCode.OK;
  header: IRefreshTokenSuccessResponseHeader;
  body: IRefreshTokenSuccessResponseBody;
};

export class RefreshTokenSuccessResponse
  extends HttpResponse<IRefreshTokenSuccessResponseHeader, IRefreshTokenSuccessResponseBody>
  implements IRefreshTokenSuccessResponse
{
  public override readonly statusCode: HttpStatusCode.OK;

  public constructor(response: IRefreshTokenSuccessResponse) {
    super(response.statusCode, response.header, response.body);

    if (response.statusCode !== HttpStatusCode.OK) {
      throw new Error(
        `Invalid status code: '${response.statusCode}' for RefreshTokenSuccessResponse`,
      );
    }

    this.statusCode = response.statusCode;
  }
}

export type IRefreshTokenSuccessResponses = IRefreshTokenSuccessResponse;

export type RefreshTokenSuccessResponses = RefreshTokenSuccessResponse;

export type IRefreshTokenResponse = IRefreshTokenSuccessResponse | ISharedErrorResponse;

export type RefreshTokenResponse = RefreshTokenSuccessResponse | SharedErrorResponse;
